### ISSUE TITLE
Move .consul domain to a var

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#100]
Instead of hardcoding .consul for dns lookups, make it a var

List of roles that use .consul dns for local lookup:
- [ ] dnsmasq
- [ ] consul
- [ ] zookeeper
- [ ] mesos
- [ ] marathon

**Comment by keithchambers** [comment]
Fixed with https://github.com/CiscoCloud/microservices-infrastructure/commit/6201e7cb3c28e8413e5f7fb97c7d93534c4869c8

Thanks @ChrisAubuchon !
