### ISSUE TITLE
Vagrant provision.sh broken by release of pip 8.0.0

### ISSUE THREAD

**Issue by bradpe** [CiscoCloud/microservices-infrastructure#1008]
pip version 8.0.0 was released today and it appears to be breaking the vagrant/provision.sh execution. 

I changed line 24 to 
```
pip --version > /dev/null || easy_install pip==7.1.2
``` 
to keep it at version 7.1.2.

It was throwing errors when trying to update PyYAML from version 3.10 to version 3.11

**Comment by siddharthist** [comment]
I have also noticed this issue. Would you like to open a PR, @bradpe? I think it is this issue: https://github.com/pypa/pip/issues/3384.

**Comment by ryane** [comment]
It looks like this was fixed upstream: https://pip.pypa.io/en/stable/news/

I am getting 8.0.2 on a fresh vagrant install and am not seeing any errors:

```
$ pip --version
pip 8.0.2 from /usr/lib/python2.7/site-packages/pip-8.0.2-py2.7.egg (python 2.7)
```

Is there any reason to still fix the version at 7.x?
