### ISSUE TITLE
Ansible version documentation

### ISSUE THREAD

**Issue by tdeckers** [CiscoCloud/microservices-infrastructure#103]
I've had some issue running the deployment using ansible 1.8.4 (error with host_vars usage, etc.).  With 1.9.0.1 (latest today) everything works smoothly.  Would be good to indicate which version of ansible the team uses to validate/test.

**Comment by ChrisAubuchon** [comment]
1.8.4 here. What issues are you seeing?

**Comment by tdeckers** [comment]
```
TASK: [dnsmasq | configure dnsmasq for consul] ********************************
fatal: [tdeckers-26032015] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'ansible_default_ipv4'", 'failed': True}
fatal: [tdeckers-26032015] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'ansible_default_ipv4'", 'failed': True}
```

At that time I was troubleshooting another issue, and running a playbook against a single host.  So it's possible that it's a combination of things.

**Comment by tdeckers** [comment]
Here's one of the other changes I noticed with this new version.
One the controller nodes, first mesos gets installed.  No specific version is defined, so we get the latest.  It also seems to bring in marathon 0.8.1, the latest version.  Next, marathon is installed and a specific version is specified: 0.7.6.  Somehow it appears that ansible 1.8.4 didn't correctly downgrade marathon to 0.7.6.  With this new version of ansible that seems to work as expected.

**Comment by stevendborrelli** [comment]
@tdeckers we removed the 0.7.6 hardcoding in the 0.2-dev branch (which we are merging into master today). 0.8.1 rpms were not available when we cut 0.1, and we had issues with 0.8.0.

**Comment by tdeckers** [comment]
Cool.  For this issue, if you're validating with ansible 1.8.4, then there must be something else on my side that I'm messing up.  Feel free to close this issue.  I'll validate later with a fresh install and if I run into the same issues I'll reopen, and we can work on it then. Thx.

**Comment by keithchambers** [comment]
Closing per @tdeckers request.
