### ISSUE TITLE
traefik UI not functional

### ISSUE THREAD

**Issue by ryane** [CiscoCloud/microservices-infrastructure#1072]
since #1035, the traefik UI is broken. Recent releases of traefik (v1.0.alpha.392+) introduced a new web build system that is no long compatible with our proxy. The issue needs to be fixed in nginx-mantlui (see https://github.com/CiscoCloud/nginx-mantlui/issues/12) and then integrated back into Mantl

**Comment by mcapuccini** [comment]
Hi @ryane, does this have to do with the warning: "API contains no information. If this is not expected, try restarting traefik." that I get in the healt checks? Or should I open a new issue for that?

**Comment by ryane** [comment]
Hi @mcapuccini. I think that might be a different issue but I actually haven't run across that one (at least not in recent releases). The issue here is that when you load the traefik UI, it won't reflect the correct state b/c all of the API requests are resulting in 404s.

**Comment by mcapuccini** [comment]
Ok, I better use the 0.5.1 version instead of the master branch. Thanks.
