### ISSUE TITLE
Authentication in Vagrant Environments

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#108]
NOTE that this issue has morphed -- which is fine. The original issue is now solved.

```
TASK: [nginx | create tls directory structure] ******************************** 
changed: [default]

TASK: [nginx | deploy tls files] ********************************************** 
fatal: [default] => input file not found at /Users/kechambe/Documents/code/microservices-infrastructure/roles/nginx/files/ssl/certs/nginx.cert.pem or /Users/kechambe/Documents/code/microservices-infrastructure/ssl/certs/nginx.cert.pem

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
common | install httpd-tools ------------------------------------------- 48.54s
docker | install docker ------------------------------------------------- 8.80s
dnsmasq | install dnsmasq and bind-utils -------------------------------- 8.05s
dnsmasq | configure dnsmasq for consul ---------------------------------- 0.21s
docker | enable docker -------------------------------------------------- 0.20s
nginx | create tls directory structure ---------------------------------- 0.15s
common | configure hosts file ------------------------------------------- 0.14s
common | configure members of wheel group for passwordless sudo --------- 0.14s
common | set timezone to etc/utc ---------------------------------------- 0.14s
docker | configure docker consul dns ------------------------------------ 0.14s
           to retry, use: --limit @/Users/kechambe/vagrant.retry

default                    : ok=16   changed=11   unreachable=1    failed=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by stevendborrelli** [comment]
Let me try to duplicate the error.

**Comment by stevendborrelli** [comment]
We need to have the same check as in site.yml to make sure that auth-setup is called before running vagrant up (or have it run as part of bringing up the VM).

**Comment by keithchambers** [comment]
I wonder if we should have this come up with no-auth on Vagrant?  How much rework is required?

**Comment by BrianHicks** [comment]
I've addressed this is 70d9925 - it would have been great to have the script run automatically, but apparently Vagrant ships with it's own version of OpenSSL so shelling out to it from the script fails.

Leaving open to discuss @keithchambers no-auth suggestion. My opinion: it's simple enough to require the users to run a script, and it results in a secure-by-default state.

**Comment by keithchambers** [comment]
I recommend we tweek our implementation so we can maintain our simple "vagrant up".

I like the idea of no-auth for the Mesos, Marathon, Consul UIs for vagrant dev environments because it's simpler for dev users. Security is less important in these local dev sandboxes.

**Comment by maier** [comment]
Running `./auth-setup` prior to the first invocation of `vagrant up` doesn't add significant friction. But, it seems it would offer several tangible benefits. 

* Ensures security isn't a 2nd class citizen. 
* If the environment is secure by default, even in dev, it  makes configuring other components less complex (fragile). e.g. automatically redirecting to https, only having to describe access/usage for examples and documentation in one context (rather than, if you have security do it this way, if you don't do it this way).
* Awareness for centralized security control. So that when people do want/need to alter their security posture they already know where to do it.

**Comment by keithchambers** [comment]
@maier fair points about security in dev.  I can get on board with the idea that security should exist in dev so that it's more closely mirrors production. 

I just looked at your commit https://github.com/maier/microservices-infrastructure/commit/19fb9773dc72d2c8bb44b2de7d257374adddd63f where to favor the settings in `security.json` over the static `admin`:`vagrant` values for UI authentication.  I'd like to get your thoughts on https://github.com/CiscoCloud/microservices-infrastructure/issues/109.  As it stands the JSON file is not easy enough to read IMO.  If you #1 goal was user adoption, how would you approach this?

**Comment by maier** [comment]
I personally prefer either to XML. Currently, the vast majority of configuration files are already YAML for Ansible (as was mentioned in #109). Given that coupled with striving for the lowest level of friction, it makes sense to me personally, to leverage YAML across the board for persisted configurations. Coherence in manner and method of configuration seems like it would be a win.

**Comment by maier** [comment]
Re-reading the README "getting started" section. Keeping in mind to make things as simple as possible, yet also maintaining coherence. It would seem there are a few options (each with drawbacks):

1. Have `auth-setup` use `admin:vagrant` as the default credentials.
1. Have users reference `security.(json|yaml)` to retrieve correct credentials.
1. Have Vagrantfile load, change, and save the security settings.

It really depends on where the added complexity makes the most sense. In case one, a non-vagrant deployment *must* edit the security settings and generate/replace multiple credentials. In the second case someone just wishing to kick the tires needs to pull the correct credentials to use out of a file. The third case puts the burden of complexity into the Vagrantfile (adding some fragility). But, the third option does offer: an easy set of credentials for casual user, higher coherence with configuration files, documentation, and user experience, as well as, keeps the more secure random generated credentials for non-Vagrant deployments.

**Comment by keithchambers** [comment]
Steve and I discussed extending `auth-setup` to prompt the user for an admin account password. This should make the situation less confusing the for the user since they pick the password themselves. Once this change is committed I'd remove the password overwrites from `Vagrantfile` and update the README.

**Comment by keithchambers** [comment]
This went in to the 0.2 release.
