### ISSUE TITLE
upgrade-packages.yml serial vs parallel mode

### ISSUE THREAD

**Issue by zoza1982** [CiscoCloud/microservices-infrastructure#1084]
I ran into the case, where I do no see a reason of why would I run upgrade-packages.yml in serial mode 1 by 1 which is default.

a) upgrade-packages.yml is kind of pre-requirement to a fresh cluster install to reach required CentOS version. Hence, doing 1 at a time....would take forever ...even with a cluster of 3. ( 1 egde, 1 control, 1 worker). 

b) Fresh cluster OS package upgrade does not really requires serial mode, as you are not doing mesos/marathon/consul rolling upgrade. You are doing fresh install...and hence there is no risk.

c) If there is a need for upgrade of OS packages on existing cluster, then OK...but we should have condition in the upgrade-packages.yml  to check for presence of existing installation , and then proceed with rolling upgrade or full blown parallel upgrade.

d) I also suggest to rename upgrade-packages.yml to upgrade-os-packages.yml as its we are not thinking of mantl ( mesos/marathon/chronos/mantl ) we just think of OS packages.

**Comment by sehqlr** [comment]
We set `serial=1` as the default, because of damage from running the playbook in parallel mode on an existing cluster. 

We have the `-e 'serial=0` version of the command in our documentation, in it's own Warning box, but I like your suggestion of having the playbook make that decision automatically. Do you have an idea of an implementation?

**Comment by zoza1982** [comment]
@sehqlr  there are many ways I guess of probing if cluster has no software on it  or it's existing.
Perhaps probing for several ports (just like you do when you wait service to come up after reboot)  ....e.g mesos 5050 port , consul 8500 and marathon 8080 on control nodes...registering new ansible variable based on result.....and based on that, suggest ( prompt user to type "yes" or "no") or auto make decision of parallel or serial.

I will try to implemented it and share the code.

**Comment by zoza1982** [comment]
@sehqlr  Oh and by the way , I haven't had a clue about -e 'serial=0' ...thats also a good feature.  I missed that part in the docs.

**Comment by sehqlr** [comment]
I think that the simplest way to go about this is to have the playbook check Mantl API's `health` endpoint. If the check is `200`, then `serial=1`. Otherwise, `serial=0`.

**Comment by zoza1982** [comment]
I was thinking the exactly the same...and I tried it to implement it.  But the problem I am facing is that I cannot make playbook setting "serial" a dynamic variable. Ansible-playbook does not allow me. It says something "not valid playbook method" or something like that. It could be the order of in which I am setting the variable. I just have to try harder.

One more thing I want to try is to setting external yml file e.g check_cluster_existance.yml which would check for mantl api health endpoint and then set variable serial=0 or 1. Then include that yml on the top of upgrade-packages.yml before the actual serial setting...and try if that works.

Or maybe I am just complicating it....

**Comment by sehqlr** [comment]
I was overcomplicating it too, but I ended up making a different playbook, which is close to what you're doing. Take a look at the PR and see if there are other things we could change.

**Comment by zoza1982** [comment]
+1 Looks good! Thanks
