### ISSUE TITLE
hosted_zone_id is not listed as a variable

### ISSUE THREAD

**Issue by TanyaCouture** [CiscoCloud/microservices-infrastructure#1085]
hosted_zone_id is not listed as a variable in this tf file.

https://github.com/CiscoCloud/microservices-infrastructure/blob/master/terraform/aws.sample.tf#L155

The id "XXXXXXXXX" leads to this error during terraform apply:

```* aws_route53_record.dns-edge.1: NoSuchHostedZone: No hosted zone found with ID: XXXXXXXXXXXX
	status code: 404, request id:```

**Comment by anners** [comment]
this is fixed in PR https://github.com/CiscoCloud/microservices-infrastructure/pull/1074

**Comment by ryane** [comment]
yep, fixed by #1074
