### ISSUE TITLE
No support for latest version of calico/mesos-marathon

### ISSUE THREAD

**Issue by ajays20078** [CiscoCloud/microservices-infrastructure#1094]
Hi,

Currently there is no support for recent versions of mesos. 

Mesos 0.26.0 is not supported (since it doesn't support DOCKER_HOST env variable anymore). The repo is using Mesos 0.23
Similarly Calico 0.10.0 is not supported (since it doesn't support powerstrip anymore).The repo is using Calico 0.4.9

So are there any attempts to keep Mesos and Calico updated to keep them bug free?

**Comment by siddharthist** [comment]
See #995 for context on Mesos version. We currently use 0.25.

@Zogg can you provide more information re: Calico?

**Comment by stevendborrelli** [comment]
@ajays20078 there is a branch for using calico that was developed with help from the metaswitch team https://github.com/CiscoCloud/microservices-infrastructure/pull/1011. Right now we can't merge it due to an elasticsearch framework issue, but you are free to test it.

**Comment by stevendborrelli** [comment]
I'm going to close this issue as we have newer versions of mesos and Calico built.
