### ISSUE TITLE
Mesos UI does not require authentication to view

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#110]

**Comment by stevendborrelli** [comment]
This may have to be pushed back to a later release. Still doing research on this. 

https://issues.apache.org/jira/browse/MESOS-1923
https://issues.apache.org/jira/browse/MESOS-809

**Comment by stevendborrelli** [comment]
With pull #135, closing this issue.

**Comment by keithchambers** [comment]
Great! Thx Steve
