### ISSUE TITLE
Better instructions in the 'Checking Your Deployment' section of the docs

### ISSUE THREAD

**Issue by sehqlr** [CiscoCloud/microservices-infrastructure#1100]
It'd be helpful if we included more instructions in the Checking Your Deployment section of the docs. Right now it just says to check the ports for individual services, but we could provide more info, like how to use the terraform.py tool to get the `hostfile`, how to use Mantl UI for health checks, and so on.

**Comment by siddharthist** [comment]
Anything that could be included in this section should probably just be incorporated into `testing/healthchecks.py`.
