### ISSUE TITLE
Can't run vagrant up or init

### ISSUE THREAD

**Issue by ashmehro** [CiscoCloud/microservices-infrastructure#1101]
Hi,
My setup is Ubuntu 14.04
I checked out from github and was able to run the security-setup, but havent been able to run the "vagrant up" or "vagrant init". The command always comes back with --
```
vm:
* The box 'CiscoCloud/microservices-infrastructure' could not be found.
```
I couldn't file a .box location for the above branch. 
I have tried with default/CiscoCloud as --provider with vagrant up, that doesnt help either.
Do I have to do any "vagrant box add"?
ANy working set of steps should help

**Comment by siddharthist** [comment]
Try running:
```
vagrant box add CiscoCloud/microservices-infrastructure
```

**Comment by ashmehro** [comment]
Throws usage error - expects provider, URL, etc. just like there is a precise.box,  is there any URL for this?

**Comment by siddharthist** [comment]
@ashmehro Does this help? https://atlas.hashicorp.com/CiscoCloud/boxes/microservices-infrastructure

**Comment by ashmehro** [comment]
That's what I was following along with the GitHub documentation when I started seeing this error.
The link doesn't give a URL for any .box

**Comment by ryane** [comment]
can you paste in the output of `vagrant box list` on your machine?

**Comment by siddharthist** [comment]
This link gives instructions: https://atlas.hashicorp.com/CiscoCloud/boxes/microservices-infrastructure/versions/0.7
```
vagrant init CiscoCloud/microservices-infrastructure; vagrant up --provider virtualbox
```

**Comment by ashmehro** [comment]
Content of Vagrantfile -   config.vm.provider "virtualbox"  config.vm.provider "vmware_fusion"
  config.vm.box = "CiscoCloud/microservices-infrastructure"
On CLI - $ vagrant upBringing machine 'default' up with 'virtualbox' provider...There are errors in the configuration of this machine. Please fixthe following errors and try again:
vm:* The box 'CiscoCloud/microservices-infrastructure' could not be found.
$ vagrant box add CiscoCloud/microservices-infrastructureThis command was not invoked properly. The help for this command isavailable below.
Usage: vagrant box add <name> <url> [--provider provider] [-h]
        --checksum VALUE             Checksum        ....$ vagrant box add microservices-infrastructure --provider CiscoCloudThis command was not invoked properly. The help for this command isavailable below.
Usage: vagrant box add <name> <url> [--provider provider] [-h]
        --checksum VALUE             Checksum        Even for a new folder and trying to create a Vagrant file and getting it up - 
$ vagrant init CiscoCloud/microservices-infrastructure; vagrant up --provider virtualboxA `Vagrantfile` has been placed in this directory. You are nowready to `vagrant up` your first virtual environment! Please readthe comments in the Vagrantfile as well as documentation on`vagrantup.com` for more information on using Vagrant.Bringing machine 'default' up with 'virtualbox' provider...There are errors in the configuration of this machine. Please fixthe following errors and try again:
vm:* The box 'CiscoCloud/microservices-infrastructure' could not be found.
$ vagrant init CiscoCloud/microservices-infrastructure; vagrant up --provider CiscoCloudA `Vagrantfile` has been placed in this directory. You are nowready to `vagrant up` your first virtual environment! Please readthe comments in the Vagrantfile as well as documentation on`vagrantup.com` for more information on using Vagrant.The provider 'CiscoCloud' could not be found, but was requested toback the machine 'default'. Please use a provider that exists.
 

    On Monday, February 8, 2016 6:18 PM, Ryan Eschinger <notifications@github.com> wrote:
 

 can you paste in the output of vagrant box list on your machine?—

**Comment by ashmehro** [comment]
Looks like finally I am able to at least get the box!Checked out a fresh branch and DID NOT do the "git tag" step.After the security-setup, it checked for vagrant version which was (1.4.3, so apt-get removed it and installed 1.8.1 - using the gdebi and .deb file from vagrantup.com).That made it work!The .box location can be noted from below, it was not available anywhere - not in http://vagrantbox.es or the github wiki.
$ vagrant upVagrant is upgrading some internal state for the latest version.Please do not quit Vagrant at this time. While upgrading, Vagrantwill need to copy all your boxes, so it will use a considerableamount of disk space. After it is done upgrading, the temporary diskspace will be freed.
Press ctrl-c now to exit if you want to remove some boxes or freeup some disk space.
Press the Enter or Return key to continue.No vagrant-config.yml found, using defaultsBringing machine 'worker-001' up with 'virtualbox' provider...Bringing machine 'control-01' up with 'virtualbox' provider...==> worker-001: Box 'CiscoCloud/microservices-infrastructure' could not be found. Attempting to find and install...    worker-001: Box Provider: virtualbox    worker-001: Box Version: >= 0==> worker-001: Loading metadata for box 'CiscoCloud/microservices-infrastructure'    worker-001: URL: https://atlas.hashicorp.com/CiscoCloud/microservices-infrastructure==> worker-001: Adding box 'CiscoCloud/microservices-infrastructure' (v0.7) for provider: virtualbox    worker-001: Downloading: https://atlas.hashicorp.com/CiscoCloud/boxes/microservices-infrastructure/versions/0.7/providers/virtualbox.box    worker-001: Progress: 6% (Rate: 915k/s, Estimated time remaining: 0:17:34) 

    On Monday, February 8, 2016 6:44 PM, Ashish Mehrotra <ashmehro@yahoo.com> wrote:
 

 Content of Vagrantfile -   config.vm.provider "virtualbox"  config.vm.provider "vmware_fusion"
  config.vm.box = "CiscoCloud/microservices-infrastructure"
On CLI - $ vagrant upBringing machine 'default' up with 'virtualbox' provider...There are errors in the configuration of this machine. Please fixthe following errors and try again:
vm:* The box 'CiscoCloud/microservices-infrastructure' could not be found.
$ vagrant box add CiscoCloud/microservices-infrastructureThis command was not invoked properly. The help for this command isavailable below.
Usage: vagrant box add <name> <url> [--provider provider] [-h]
        --checksum VALUE             Checksum        ....$ vagrant box add microservices-infrastructure --provider CiscoCloudThis command was not invoked properly. The help for this command isavailable below.
Usage: vagrant box add <name> <url> [--provider provider] [-h]
        --checksum VALUE             Checksum        Even for a new folder and trying to create a Vagrant file and getting it up - 
$ vagrant init CiscoCloud/microservices-infrastructure; vagrant up --provider virtualboxA `Vagrantfile` has been placed in this directory. You are nowready to `vagrant up` your first virtual environment! Please readthe comments in the Vagrantfile as well as documentation on`vagrantup.com` for more information on using Vagrant.Bringing machine 'default' up with 'virtualbox' provider...There are errors in the configuration of this machine. Please fixthe following errors and try again:
vm:* The box 'CiscoCloud/microservices-infrastructure' could not be found.
$ vagrant init CiscoCloud/microservices-infrastructure; vagrant up --provider CiscoCloudA `Vagrantfile` has been placed in this directory. You are nowready to `vagrant up` your first virtual environment! Please readthe comments in the Vagrantfile as well as documentation on`vagrantup.com` for more information on using Vagrant.The provider 'CiscoCloud' could not be found, but was requested toback the machine 'default'. Please use a provider that exists.
 

    On Monday, February 8, 2016 6:18 PM, Ryan Eschinger <notifications@github.com> wrote:
 

 can you paste in the output of vagrant box list on your machine?—

**Comment by siddharthist** [comment]
@ashmehro Glad it worked out :) let us know if you have any other problems/questions!
