### ISSUE TITLE
Consul UI unavailable

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#111]
https://<address>:8500 returns an error

**Comment by ChrisAubuchon** [comment]
Use :8700 for the /ui/. The UI is blocked on 8500.

**Comment by keithchambers** [comment]
Thanks Chris. I see.

Could we change consul-ui to listen on some other port so that Nginx can proxy on the standard 8500?

**Comment by keithchambers** [comment]
Hmmm 8700 is not working for me either with Vagrant or OpenStack.

**Comment by ChrisAubuchon** [comment]
Are you using https?

I'm testing a fix that will put /ui/ on 8500.

**Comment by keithchambers** [comment]
Yea I was testing with https.

**Comment by keithchambers** [comment]
Fixed.
