### ISSUE TITLE
Need to update example/hello-world to support Marathon auth

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#112]

**Comment by maier** [comment]
Would you prefer automated, as in if security.json exists, or command line parameters for user and password (e.g. -u and -p) or both (automate and -u/-p override if supplied)?

**Comment by keithchambers** [comment]
Hey Matt!

We love all ideas that make like easier for users. :+1:

Just command line parameters for user and password (e.g. -u and -p) for [```launch.sh```](https://github.com/CiscoCloud/microservices-infrastructure/blob/master/examples/hello-world/launch.sh) makes sense for now.

The ```security.json``` concept is brand spanking new and we will probably make changes to the structure of the JSON (e.g., https://github.com/CiscoCloud/microservices-infrastructure/issues/109).  What we could do is add a reference to ```security.json``` to ```usage``` for [```launch.sh```](https://github.com/CiscoCloud/microservices-infrastructure/blob/master/examples/hello-world/launch.sh).
