### ISSUE TITLE
Automatically redirect http requests to https

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#113]
From a usability perspective it would be nice if we automatically redirected http requests to https.

Let's consider this for 0.2.

**Comment by keithchambers** [comment]
This works for Consul now.  Thank you @ChrisAubuchon.

@ChrisAubuchon You mentioned there was an issue with Marathon and HTTPS on the phone the other day.  Did I hear correct? Is there an issue logged against Marathon? If it's a hard limitation of Marathon, should we redirect calls to https://*:8080 to http://*:8080 ?

**Comment by ChrisAubuchon** [comment]
The limitation is that the current release of marathon doesn't allow for selecting the IP address that it listens on. It will always bind at *:{port}. I suppose we could have it listen on 8081 (or something) and then forward from https://8080->http://8081 but that isn't really secure.

**Comment by keithchambers** [comment]
It would be secure from the server to the client -- correct?

    ----------------                         ----------------------------------------------
    |    client    |                         |                    server                  |
    |              |                         |                                            |
    |  [  curl  ]  | ----- 8080 https ---->  |  [ nginx ] --- 8081 http --> [ marathon ]  |
    |              |                         |                                            |
    ----------------                         ----------------------------------------------

**Comment by ChrisAubuchon** [comment]
There is nothing to stop the client from connecting directly to 8081 in that scenario. At that point we're relying on security by obscurity.

**Comment by keithchambers** [comment]
OK I see.  Is there an GitHub issue opened against Marathon?  Is it something trivial where we can submit a PR?

Perhaps this is something @kensipe can help us drive.

**Comment by ChrisAubuchon** [comment]
The fix is already in the marathon code tree via https://github.com/mesosphere/marathon/commit/7608bc2f4c86442d69c50a22a3c687b3e6d017ed. It was committed after the 0.8.1 release though.

**Comment by keithchambers** [comment]
I gotcha.

What are our other options? 

Use Nginx for SSL on port 8080 and use the OS firewall to block port 8081?

Or we could redirect requests to https:8080 to http:8080?

**Comment by stevendborrelli** [comment]
Another option is to create another JKS ssl key and use it until the next release of Marathon is out.

**Comment by ChrisAubuchon** [comment]
Of the two I'd rather go with nginx on 8080 and firewall'd 8081.
* It is closer to our desired end state of a public:8080->localhost:8080 proxy
* We can use our nginx-consul container to manage the nginx configuration and the users

**Comment by keithchambers** [comment]
@ChrisAubuchon sound good.

Should I open another issue or do you want to use this issue to track it?

**Comment by stevendborrelli** [comment]
@ChrisAubuchon can we close this issue?

**Comment by ChrisAubuchon** [comment]
Is there anything else besides consul and marathon that we want to use https for?

**Comment by stevendborrelli** [comment]
We need to protect the mesos leader and follower endpoints (ports 5050, 5051). The challenge there is protecting the endpoint without interfering with communication between the nodes.

**Comment by stevendborrelli** [comment]
With pull request #135, closing this issue.
