### ISSUE TITLE
Multi-datacenter deployment on CCS

### ISSUE THREAD

**Issue by tdeckers** [CiscoCloud/microservices-infrastructure#114]
I need some guidance on multi-DC setup on Cisco Cloud.  I've read the docs [here](microservices-infrastructure/docs/getting_started/openstack.rst), but I'm missing a few details.

According to the doc, I create a private network and use a router to connect to the internet. This of course works for fetching *from* the internet, but how does this for example allow consul servers from two data centers to communicate?

What's the preferred setup to ensure hosts in one DC can communicate with hosts in another?

**Comment by keithchambers** [comment]
@tdeckers 

You're right.  I just skimmed through the [documentation](https://github.com/CiscoCloud/microservices-infrastructure/blob/master/docs/getting_started/openstack.rst) and it's missing a key piece of information: [```site.yml```](https://github.com/CiscoCloud/microservices-infrastructure/blob/master/site.yml) provisioning the hosts for you

Let me know if this works for you:  ```ansible-playbook -i /inventory/2-datacenter site.yml```

BTW ... ```site.yml``` also calls [```playbooks/consul-join-wan.yml```](https://github.com/CiscoCloud/microservices-infrastructure/blob/master/playbooks/consul-join-wan.yml) which verifies WAN connectivity and automatically joins the consul clusters together!

**Comment by tdeckers** [comment]
I did get site.yml to provision my hosts, but this is more a question about IP connectivity between the data centers.  I assume from your answer that I have to first ensure networks in both data centers are setup in such a way that hosts can access each other.  The documentation mentions creating a private network in the 10.x.x.x range. So this means I have to either associate floating IPs or configure other routing, no?  The other options is that I put all my hosts on the publicly accessible network (and not use a private network), but that doesn't sound like a good plan.

**Comment by stevendborrelli** [comment]
In general, network connectivity is required between the DC's, whether that is an internal network, routing through a VPN or via public IPs. 

For out testing environment, we are on public subnets, so we are using security groups to limit access only at a subnet level.

I think this is a good place to improve our documentation. Tools like terraform can provision security groups and networks, so we could look at more automation around the network setup.

**Comment by tdeckers** [comment]
Just spoke with Keith about this, and indeed - for the current version, I'll provision hosts on the public network (public-floating-60x).  The documentation can be optimized to highlight this.
For later versions it would be good to support deployment of hosts on a private network with explicit exposure of application endpoints as required.

**Comment by keithchambers** [comment]
@tdeckers [This](https://github.com/hashicorp/consul/pull/816) Consul pull request would resolve the WAN gossip advertisement limitation I was eluding to on the phone yesterday.

**Comment by siddharthist** [comment]
The link in the first comment is broken. I believe it should point [here](http://microservices-infrastructure.readthedocs.org/en/latest/getting_started/openstack.html).

**Comment by michaeltchapman** [comment]
Some detail around provisioning with private networks + floating IPs:

1. All the required resources (router, floating_ip, network, subnet, router_interface) are already in Terraform. (yay!)
2. The default quota for routers in CCS is 1. (boo)
3. Terraform currently doesn't seem to be able to consume an existing resource if it exists and create otherwise. (boo)

This means that any tenant that has already made a private network and set up floating IPs won't be able to boot the microservices stack due to a quota error, which is not good.

The quota of 1 is because it consumes a floating IP for SNAT purposes, which is generally a paid resource.

https://github.com/hashicorp/terraform/issues/581 would theoretically fix (3) but is probably not going to be done quickly enough for our needs.

I'm going to make a new .tf for this use case, but it's going to have the quota limitation for the time being.

**Comment by siddharthist** [comment]
[We now have floating IP support](https://github.com/CiscoCloud/microservices-infrastructure/pull/483), is there anything else we can do to improve Mantl for multi-DC on CCS?

**Comment by siddharthist** [comment]
Closing for now, please reopen if we can improve support for multi-DC on CCS!
