### ISSUE TITLE
Update Controller Node and Compute Nodes docs and diagrams for 0.2

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#120]
The diagrams on our [GH landing page](ttps://github.com/CiscoCloud/microservices-infrastructure) are likely outdate with the changes we have made for 0.2.

The originals are available at: https://github.com/CiscoCloud/microservices-infrastructure/blob/master/docs/_static/diagrams.key

**Comment by stevendborrelli** [comment]
Do you have the updated .key files? I can update this.

**Comment by stevendborrelli** [comment]
WIP at https://github.com/CiscoCloud/microservices-infrastructure/tree/feature%2Fupdate-graphics

**Comment by stevendborrelli** [comment]
Fixed in #150
