### ISSUE TITLE
Error: variables: 'nginx_admin_password_encrypted' is undefined

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#123]
Trying to run a build off master and getting this error:

TASK: [nginx | set admin password variable] *********************************** 
fatal: [host-03] => One or more undefined variables: 'nginx_admin_password_encrypted' is undefined

**Comment by stevendborrelli** [comment]
Looks like Chris may have addressed this with https://github.com/CiscoCloud/microservices-infrastructure/commit/2f808f457004ddcd9a54d29beaac3df6d4b27231

**Comment by keithchambers** [comment]
Probably my bad. :-(

**Comment by keithchambers** [comment]
Fixed on master with https://github.com/CiscoCloud/microservices-infrastructure/commit/d23b5c0402a22142e885e29e2dd7e9838d7b01ae.

It's probably time that we get religious about about using PRs with automated testing. :-)
