### ISSUE TITLE
Move nginx Encryption into auth-setup

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#125]
Currently the nginx admin password is encrypted via bcrypt in a couple of tasks in the nginx role. We're going to move the creation of the password into auth-setup.

- [x] add bcrypt requirement to requirements.txt
- [x] update auth-setup to bcrypt password nginx_admin_password_encrypted
- [x] clean up nginx admin password creation tasks in nginx/tasks/main.yml

**Comment by keithchambers** [comment]
And we need to remove:

```
roles/common/tasks/mail.yml

- name: update yum cache
  sudo: yes
  command: yum makecache
```

**Comment by stevendborrelli** [comment]
passlib has issues on my OS X, should we import bcrypt instead?

**Comment by BrianHicks** [comment]
what issues are you having?

**Comment by stevendborrelli** [comment]
Maybe I was calling it wrong:
```
>>> from passlib.hash import bcrypt
>>> bcrypt.encrypt("password")
'$2a$12$0506aTiTIxLBzT8dW.JUB.bF2En8MwMh1nYzTMig/Krdz5xlCejjm'
```

**Comment by stevendborrelli** [comment]
@keithchambers do we still want to remove `yum makecache`? Otherwise this is ready to merge via #130.

**Comment by stevendborrelli** [comment]
Closing after merging in #130.
