### ISSUE TITLE
TASK: [nginx | deploy tls files] failed

### ISSUE THREAD

**Issue by Y4Rv1K** [CiscoCloud/microservices-infrastructure#127]
Latest release failed at vagrant 

After vagrant up I got: 

    TASK: [nginx | deploy tls files] **********************************************
    failed: [default] => (item={'dest': '/etc/nginx/ssl/nginx.cert', 'src': 'ssl/certs/nginx.cert.pem'}) => {"details":       "invalid literal for int() with base 8: 'u=r'", "failed": true, "gid": 0, "group": "root", "item": {"dest":    "/etc/nginx/ssl/nginx.cert", "src": "ssl/certs/nginx.cert.pem"}, "md5sum":      "06d426643b6e0780a97c732c010bc90a", "mode": "0644", "owner": "root", "path": "/etc/nginx/ssl/nginx.cert", "secontext": "system_u:object_r:httpd_config_t:s0", "size": 1578, "state": "file", "uid": 0}
    msg: mode needs to be something octalish
    failed: [default] => (item={'dest': '/etc/nginx/ssl/nginx.key', 'src': 'ssl/private/nginx.key.pem'}) => {"details": "invalid literal for int() with

**Comment by Y4Rv1K** [comment]
Works after ansible upgrade from version 1.7.1 to latest 

Looks like bug in ansible https://github.com/ansible/ansible/issues/7839#issuecomment-49311909

Would be nice to have "Software requirements" for toolset to README.md

**Comment by BrianHicks** [comment]
@Y4Rv1K it is documented (in [requirements.txt](https://github.com/CiscoCloud/microservices-infrastructure/blob/master/requirements.txt)) but it definitely could be clearer. I'm reopening this as a doc bug.

**Comment by Y4Rv1K** [comment]
Thank you. Would be nice for lazy ops like me :)

**Comment by keithchambers** [comment]
lol
