### ISSUE TITLE
auth-setup refinements

### ISSUE THREAD

**Issue by BrianHicks** [CiscoCloud/microservices-infrastructure#128]
From Keiths' comments on #108 and #109:

 - [x] switch from JSON to YAML in the `security` file
 - [x] use a single unified password for the `admin` account across Consul, Marathon, and Mesos
 - [x] Prompt the user for `admin` account password during `auth-setup`.

**Comment by BrianHicks** [comment]
@keithchambers @stevendborrelli any other refinements y'all discussed?

**Comment by BrianHicks** [comment]
prompt in be5060e8ef8cd29bf11d792ea886136707f7a823

**Comment by BrianHicks** [comment]
`auth-setup` has now grown a `--change-admin-password` flag as well. Does what it says on the tin.

**Comment by keithchambers** [comment]
LGTM

**Comment by BrianHicks** [comment]
closed by #129
