### ISSUE TITLE
Consul "Failed connect to 127.0.0.1:8080; Connection refused"

### ISSUE THREAD

**Issue by Y4Rv1K** [CiscoCloud/microservices-infrastructure#131]
We are deploying micro services on top of OpenStack using dc1 inventory example
As result when cluster is running with 3 marathon servers we got false positive error at consul

Consul check script `roles/marathon/templates/marathon-consul.j2` using

    "script": "curl --silent --show-error  --fail --dump-header /dev/stderr --retry 2 {% if marathon_http_credentials is defined %}-u {{ marathon_http_credentials }}{% endif %} http://127.0.0.1:8080/ping",

And because in cluster server is running on external IP we got false positive result

    [centos@host-01 ~]$ sudo netstat -nlupt | grep 8080
    tcp        0      0 17x.xx.xx.x84:8080     0.0.0.0:*               LISTEN      20477/nginx: master

In this case make sense to change validation rules to proper one (but using templates it can be problematic, does it?)

Docker: 

    /usr/bin/docker run --rm --name=nginx-marathon --net=host --privileged=true -v   /etc/nginx/ssl:/etc/nginx/ssl -e NGINX_KV=service/nginx/templates/marathon -e NGINX_ENABLE_AUTH=true -e NGINX_PUBLIC_IP=17x.xx.xx.x84 asteris/nginx-consul:latest

**Comment by stevendborrelli** [comment]
Thanks for raising the issue. There is currently a problem with the marathon check in consul and the way marathon proxies requests to the leader node. 

There are some fixes on the https://github.com/CiscoCloud/microservices-infrastructure/tree/feature/nginx-proxy branch, and I'll see if I can update the consul check in that branch.

**Comment by stevendborrelli** [comment]
After merging in #135, consul checks on marathon are now green.

**Comment by OleksandrBerchenko** [comment]
The changes look good, thank you!
