### ISSUE TITLE
nginx-consul.services dependency failed to start after cluster reboot

### ISSUE THREAD

**Issue by Y4Rv1K** [CiscoCloud/microservices-infrastructure#132]
We build basic cluster on top of OpenStack using branch https://github.com/CiscoCloud/microservices-infrastructure/tree/feature/nginx-proxy  (thank you @stevendborrelli ) . But after restart consul UI failed to start. As result: 

    nginx-consul.service - nginx-consul
       Loaded: loaded (/usr/lib/systemd/system/nginx-consul.service; enabled)
       Active: active (running) since Fri 2015-04-03 12:08:47 UTC; 11min ago
      Process: 2452 ExecStop=/usr/bin/docker kill nginx-consul (code=exited, status=0/SUCCESS)
      Process: 2482 ExecStartPre=/usr/bin/docker pull asteris/nginx-consul:latest (code=exited,  status=0/SUCCESS)
      Process: 2475 ExecStartPre=/usr/bin/docker rm nginx-consul (code=exited, status=1/FAILURE)
     Main PID: 2511 (docker)
       CGroup: /system.slice/nginx-consul.service
               └─2511 /usr/bin/docker run --rm --name=nginx-consul --net=host --privileged=true -v   /etc/nginx/ssl:/etc/nginx/ssl -e NGINX_KV=service/nginx/templates/consul -e     NGINX_ENABLE_AUTH=true -e NGINX_PUBLIC_IP=173.39.241.111 asteris...

Docker container is running but I have errors related to missed `storeKeyPrefix(service/nginx/auth/users)`:

    2015/04/03 12:13:08 [DEBUG] (view) "storeKeyPrefix(service/nginx/auth/users)" starting fetch
    2015/04/03 12:13:08 [DEBUG] ("storeKeyPrefix(service/nginx/auth/users)") querying Consul with &{Datacenter: AllowStale:false RequireConsistent:false WaitIndex:0 WaitTime:1m0s Token:}
    2015/04/03 12:13:08 [ERR] (view) "storeKeyPrefix(service/nginx/auth/users)" Unexpected response code: 500
    2015/04/03 12:13:08 [INFO] (view) "storeKeyPrefix(service/nginx/auth/users)" errored, retrying in 5s
    2015/04/03 12:13:08 [ERR] (runner) watcher reported error: Unexpected response code: 500
    2015/04/03 12:13:08 [INFO] (runner) running

Any clue?

**Comment by keithchambers** [comment]
@Y4Rv1K Thank you for all this great testing! We'll take a look shortly.

**Comment by ChrisAubuchon** [comment]
500 is internal server error coming from Consul. Is there anything in the consul logs?

**Comment by Y4Rv1K** [comment]
Good point 

    [centos@host-01 ~]$ systemctl status consul.service
    consul.service - Consul is a tool for service discovery and configuration. Consul is distributed, highly     available, and extremely scalable.
       Loaded: loaded (/usr/lib/systemd/system/consul.service; enabled)
       Active: active (running) since Fri 2015-04-03 12:05:11 UTC; 1h 7min ago
         Docs: http://www.consul.io
      Process: 7522 ExecReload=/bin/kill -HUP $MAINPID (code=exited, status=0/SUCCESS)
     Main PID: 615 (consul)
       CGroup: /system.slice/consul.service
               └─615 /usr/bin/consul agent -config-dir /etc/consul

    Apr 03 13:12:54 host-01.novalocal consul[615]: 2015/04/03 13:12:54 [ERR] http: Request     /v1/kv/service/nginx/templates/marathon?wait=60000ms, error: No cluster leader
    Apr 03 13:12:54 host-01.novalocal consul[615]: 2015/04/03 13:12:54 [ERR] http: Request /v1/kv/service/nginx/auth/users?recurse=&wait=60000ms, error: No cluster leader
    Apr 03 13:12:55 host-01.novalocal consul[615]: 2015/04/03 13:12:55 [ERR] http: Request /v1/kv/service/nginx/templates/mesos-leader?wait=60000ms, error: No cluster leader
    Apr 03 13:12:55 host-01.novalocal consul[615]: 2015/04/03 13:12:55 [ERR] http: Request /v1/kv/service/nginx/auth/users?recurse=&wait=60000ms, error: No cluster leader
    Apr 03 13:12:55 host-01.novalocal consul[615]: 2015/04/03 13:12:55 [ERR] http: Request /v1/kv/service/nginx/templates/consul?wait=60000ms, error: No cluster leader
    Apr 03 13:12:55 host-01.novalocal consul[615]: 2015/04/03 13:12:55 [ERR] http: Request /v1/kv/service/nginx/auth/users?recurse=&wait=60000ms, error: No cluster leader
    Apr 03 13:12:56 host-01.novalocal consul[615]: 2015/04/03 13:12:56 [ERR] dns: rpc error: No cluster leader
    Apr 03 13:12:56 host-01.novalocal consul[615]: 2015/04/03 13:12:56 [ERR] dns: rpc error: No cluster leader
    Apr 03 13:12:56 host-01.novalocal consul[615]: 2015/04/03 13:12:56 [WARN] agent: Check 'service:marathon' is now critical
    Apr 03 13:12:56 host-01.novalocal consul[615]: 2015/04/03 13:12:56 [ERR] agent: failed to sync remote state: No cluster leader`

**Comment by ChrisAubuchon** [comment]
Did you happen to reboot two or more of the control nodes at the same time? That's considered an outage to Consul. Follow these instructions to recover: http://www.consul.io/docs/guides/outage.html

**Comment by OleksandrBerchenko** [comment]
We have used "reboot-hosts.yml" playbook:

ansible-playbook -i inventory/1-datacenter openstack/reboot-hosts.yml

**Comment by stevendborrelli** [comment]
@OleksandrBerchenko thanks for bringing this to our attention. I think we need to configure our reboot playbook to serial=1 for consul servers, which means that only one will be rebooted at at time. 

As @ChrisAubuchon indicated, if more than one server is down in a 3-node cluster, the consul cluster loses quorum.

**Comment by keithchambers** [comment]
I wish consol had a better way of dealing with this. I don't think ZooKeeper has the same limitation.

 I can work on a fix this morning to the reboot playbook if nobody else has started.

**Comment by stevendborrelli** [comment]
@keithchambers I've started on one....basically do a serial=1 for consul servers
```
- hosts: consul_servers,zookeeper_servers,mesos_leaders
  gather_facts: no
  serial: 1
  tasks:
   - common/reboot.yml

- hosts: !consul_servers 
  gather_facts: no
  tasks:
    - common/reboot.yml
```

**Comment by keithchambers** [comment]
@stevendborrelli after thinking about this a bit I wouldn't want to reboot all the resource nodes at the same time either.  So I figure we should just do a rolling reboot of all hosts regardless of roles they run.  Make sense?

**Comment by keithchambers** [comment]
By the way I verified consul bootstraps fine when rebooting with Vagrant.

**Comment by OleksandrBerchenko** [comment]
The changes look good, thank you!
