### ISSUE TITLE
Missing or incorrect information in getting started documents

### ISSUE THREAD

**Issue by OleksandrBerchenko** [CiscoCloud/microservices-infrastructure#133]
docs/getting_started/openstack.rst

1. Change "inventory/dc1" to "inventory/group_vars/dc1" and "inventory/dc2" to "inventory/group_vars/dc2"

2. "neutron router-gateway-set router1 external" - it may be helpful to emphasize that "external" should be replaced with an actual name of your external network

3. Change "neutron router-show router" to "neutron router-show router1".

4. "You should see IPs in external_fixed_ips" - it seems there is no "external_fixed_ips" field:

```
+-----------------------+-----------------------------------------------------------------------------+
| Field                 | Value                                                                       |
+-----------------------+-----------------------------------------------------------------------------+
| admin_state_up        | True                                                                        |
| external_gateway_info | {"network_id": "56e3d1ac-44d6-43d7-bea3-e2f334aa8f86", "enable_snat": true} |
| id                    | 73f1a1c8-6363-4408-9d7e-7f8ef239e07f                                        |
| name                  | router1                                                                     |
| routes                |                                                                             |
| status                | ACTIVE                                                                      |
| tenant_id             | 7a11dc0218dd47a2a30d08015491396e                                            |
+-----------------------+-----------------------------------------------------------------------------+
```

5. There is no "provision-image.yml" file.

6. Change "inventory/my_dc1" to "inventory/1-datacenter"

docs/getting_started/index.rst

It may be helpful to mention that "./auth-setup" must be run before "ansible-playbook -i inventory/1-datacenter site.yml" and that command must be actually run as "ansible-playbook -i inventory/1-datacenter site.yml -e @security.yaml".

Thanks!

**Comment by BrianHicks** [comment]
regarding the getting started docs, are you looking at the latest version? It has these instructions, we added them yesterday. http://microservices-infrastructure.readthedocs.org/en/latest/getting_started/index.html#setting-up-authentication-and-authorization

**Comment by OleksandrBerchenko** [comment]
Well, I performed all the steps yesterday (before your changes).  Today I double checked that, but using "nginx-proxy" branch that still has the old files :)  That was a ground of confusion.

Anyway, openstack.rst issues are probably still actual.

Thanks!

**Comment by PeterLamar** [comment]
Thanks for your feedback! I did an editing pass, please take a look and let me know if you still have any issues,

**Comment by OleksandrBerchenko** [comment]
Everything looks good, except for:

1. You still need to change "inventory/dc1" to "inventory/group_vars/dc1", "inventory/dc2" to "inventory/group_vars/dc2" and "neutron router-show router" to "neutron router-show router1".

2. You have changed "neutron router-gateway-set router1 external" to "neutron router-gateway-set router1 network1".  That's probably not correct.  Instead of "network1" there should be the name of some existing network, which is publicly accessible.  I just suggested to explain what "external" exactly means.

Thanks!

**Comment by PeterLamar** [comment]
I put network1 so that someone following the previous tutorial section, may have created a public facing network named 'network1'. I added your suggestion and changed the language to hopefully make it more clear. Let me know your thoughts.

**Comment by OleksandrBerchenko** [comment]
This makes sense, thank you.

**Comment by OleksandrBerchenko** [comment]
So, only this typo remains:

Change "neutron router-show router" to "neutron router-show router1"

Thanks!

**Comment by PeterLamar** [comment]
Done

**Comment by stevendborrelli** [comment]
@OleksandrBerchenko @PeterLamar can this issue be closed?

**Comment by OleksandrBerchenko** [comment]
Looks perfect now.  Thanks!
