### ISSUE TITLE
Localhost can't resolve hostnames of provisioned machines without external DNS

### ISSUE THREAD

**Issue by OleksandrBerchenko** [CiscoCloud/microservices-infrastructure#134]
I have provisioned a cluster following the getting started instructions.  The problem is that my local machine where Ansible is installed is not able to resolve hostnames of the provisioned machines ("host-01", etc.)

Even when I moved Ansible to a new machine in Openstack cluster itself, that machine was not able to resolve them as well.  That was expected, I just wanted to make sure there is no "magic" here.

Provisioned machines are able to reach each other because the hostnames have been added to their /etc/hosts files.

My solution was to add them in my local /etc/hosts as well.  To do that I have added the following code into provision-hosts.yml:

- hosts: localhost
  gather_facts: no
  connection: local
  sudo: yes
  tasks:
    - name: update /etc/hosts file
      local_action: lineinfile
        dest=/etc/hosts
        regexp=".*{{ item }}$"
        line="{{ hostvars[item].ansible_ssh_host }} {{ item }}"
        state=present
      when: hostvars[item].ansible_ssh_host is defined
      with_items: groups['all']
      always_run: yes
      tags: host

Please consider applying a fix like that (or you can create a separate playbook not to mix up with existing provision-hosts.yml) or suggest a better solution.

Thanks!

**Comment by stevendborrelli** [comment]
This is a good idea. I've been using a shell script that talks to openstack, but this might be a nicer solution. Especially if we can query multiple DCs.

**Comment by keithchambers** [comment]
@OleksandrBerchenko can you submit a pull request please?
