### ISSUE TITLE
Cosul template for HAproxy to support non web traffic

### ISSUE THREAD

**Issue by npateriya** [CiscoCloud/microservices-infrastructure#136]
Current ha proxy works fine for web traffic load balancing but Cassandra or Mysql ( data service) load balance traffic using current config have issues. Discussed details with @steve, adding issue to keep track.

**Comment by stevendborrelli** [comment]
Adding @BrianHicks. 

I think our longer term goal should be to have an IP for every container/pod, as in the [Kubernetes network model](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/networking.md)

For the short term, my proposal is to use cluster-wide port assignments for each app. 

For example, user1 launches a cassanda.cluster, they are assigned a connection string of `cassandra.service.consul:8900`, likewise
user2 launches a cassandra cluster and they get `cassandra.service.cluster:9900`. 

We'd need to use the consul k/v store along with the service registry to hold this information.
1) service port: what port does HAproxy listen in on for this service
2) container port: this is the actual port that the container is using (i.e. 46153) 

Ideas:
1)  Use consul k/v to store forwarding information
/services/proxy/app
/services/proxy/app/port = 9042
(optional) /services/proxy/app/url matching http url 

2) Use consul service tags to store port:
Launch tasks with a `port_xxxx` in SERVICE_TAGS.
haproxy config would look like
listen {{ consul get port }}

backend: 
backend {{ server }} {{ port }}

**Comment by BrianHicks** [comment]
Long term, an IP per container makes a lot of sense - you can "just connect" on the ports you want. Would [weave](https://github.com/zettio/weave) be appropriate for this?

I think it'd make more sense to put this data in Consul services, as in idea 2. We can set up healthchecks that way as well, and turn them off in HAProxy.

**Comment by BrianHicks** [comment]
Tags won't work here, unfortunately. The template language is a little too limited in that regard. Here's how the template looks for running a bunch of redis services as "db":

```
global
  daemon
  maxconn 2048

defaults
  mode tcp
  timeout connect 5000ms
  timeout client 50000ms
  timeout server 50000ms

{{range services}}frontend {{.Name}}_frontend
  bind *:{{ key (printf "service/%s/port" .Name)}}{{range service .Name "any"}}
  server {{.Node}} {{.Address}}:{{.Port}}{{end}}

{{end}}
```

produces:

```
global
  daemon
  maxconn 2048

defaults
  mode tcp
  timeout connect 5000ms
  timeout client 50000ms
  timeout server 50000ms

frontend db_frontend
  bind *:5555
  server testbed 10.240.148.1:10001
  server testbed 10.240.148.1:10002
  server testbed 10.240.148.1:10003
  server testbed 10.240.148.1:10004
  server testbed 10.240.148.1:10005
```

Now the question is: how are we going to get that service information into haproxy (from, say, Marathon?) I'd like feedback:

 - would it make sense for this to be patched into registrator?
 - or would it be better to be another daemon?

**Comment by kenjones-cisco** [comment]
@BrianHicks have you considered or looked at https://github.com/kelseyhightower/confd for handling updating the haproxy configurations? It already supports etcd and consul both for pulling updated data to regenerate/update the configuration file from template and then restart the instance.

**Comment by stevendborrelli** [comment]
@kenjones-cisco we're using consul-template to update haproxy configurations. We have a base container that you use for consul-template at https://github.com/CiscoCloud/docker-consul-template. 

consul-template is very similar to confd, and was developed because confd does not support consul service discovery endpoints (and has no plans to do so, see https://github.com/kelseyhightower/confd/pull/102)

**Comment by kenjones-cisco** [comment]
Makes sense. Based on the open questions Brian had listed, I figured I'd offer input based on previous experience. Sounds like the questions have been already resolved. Looking forward to this change! :thumbsup:

**Comment by BrianHicks** [comment]
OK, to update this rather old ticket and get it closed: we now have [marathon-consul](https://github.com/CiscoCloud/marathon-consul) for forwarding app information to Consul and [a new branch of haproxy-consul](https://github.com/CiscoCloud/haproxy-consul/pull/1) to play with. If @npateriya and @kenjones-cisco could review the documentation on that PR, that'd be helpful in getting this merged and closed.

**Comment by npateriya** [comment]
Can you please add in document how would multiple logically isolated instance of cassandra (ContainerPort: 9042), would be deployed and configured. For example 
customer1-env1-cassandra
customer1-env2-cassandra
customer2-env1-cassandra
customer2-env2-cassandra
I am not able to follow changes closely, but  based on quick document reading. For each of above cassandra instance while creating marathon  APP, we need to assign unique hostPort. Is this right interpretation?  Non http example in README will help.

**Comment by stevendborrelli** [comment]
@BrianHicks is this ready to close?

**Comment by BrianHicks** [comment]
This is actually probably the last one to close of the three. It depends on the changes to marathon-consul and haproxy-consul being merged. If that stuff looks good to everyone else though, I'll get all of it merged today.

**Comment by kenjones-cisco** [comment]
My interest originally was the where it seemed to relate to potentially including weave and not having to deal with service offer ports. That way I don't have to lookup what port my container has but know it will always have port 27017 if it is mongodb. And then understanding how this proxy can or will work with the proxy I setup for my actual service being deployed within microservices-infrastructure such that when going to https://my.example.com is routed to my specific service.

**Comment by stevendborrelli** [comment]
@kenjones-cisco The plan is to include IP level resources into Mesos so that each task can get an IP assigned. There's a few groups getting together around that effort. For the short term we haven't decided on using weave or flocker, so we'll probably ask folks to use the marathon proxy until the Mesos networking picture becomes more clear.

**Comment by BrianHicks** [comment]
@npateriya I added a [clarifying sentence](https://github.com/CiscoCloud/haproxy-consul/commit/4281a490d7be5222250a425332564cdd2f62aa4b) there. Basically, Marathon will show what "global" port it has assigned and haproxy-consul will forward those.

@stevendborrelli I think that's ready to merge if you wouldn't mind giving it a last lookover before we merge.

**Comment by stevendborrelli** [comment]
@BrianHicks merged & the docker container  (ciscocoud/haproxy-consul) was built with tag 0.1 for the merge.

**Comment by stevendborrelli** [comment]
@BrianHicks can we close this issue?

**Comment by BrianHicks** [comment]
I think the variables need to be set to Marathon still.

**Comment by stevendborrelli** [comment]
-  haproxy-consul was updated to support this via https://github.com/CiscoCloud/haproxy-consul/pull/1
- marathon consul runs by default

For 0.3, the consul backend will be used. 0.4 will use marathon backend as default. See #427.
