### ISSUE TITLE
UI default ports:  8080 vs. 18080 and 5050 vs. 15050

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#137]
@stevendborrelli what do you think about sticking with port 8080 for Marathon UI and 5050 for Marathon UI?

Are there any technical limitations that would prevent this?

**Comment by ChrisAubuchon** [comment]
This should be doable. Both Mesos and Marathon support changing the port that they listen on. Testing a patch now.

**Comment by keithchambers** [comment]
Cool. Thanks Chris!

**Comment by ChrisAubuchon** [comment]
Closing via https://github.com/CiscoCloud/microservices-infrastructure/commit/db03af1575b4e22f28f64542b6923b95d0d72925
