### ISSUE TITLE
security-setup: on OSX bcrypt install fails without xcodebuild

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#138]
Issue:  `sudo pip install -r requirements' fails with the following error if xcodebuild not installed.

```
Collecting pycparser (from cffi>=0.8->bcrypt==1.1.1->-r requirements.txt (line 6))
  Downloading pycparser-2.10.tar.gz (206kB)
    100% |################################| 208kB 1.8MB/s 
Installing collected packages: pycparser, cffi, bcrypt
  Running setup.py install for pycparser
    error: could not create '/Library/Python/2.7/site-packages/pycparser': Permission denied
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/fr/dt03ln8j66nblz0z3f0yf6540000gn/T/pip-build-qlcsoi/pycparser/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/fr/dt03ln8j66nblz0z3f0yf6540000gn/T/pip-lZryvJ-record/install-record.txt --single-version-externally-managed --compile:
    running install
    
    running build
    
    running build_py
    
    creating build
    
    creating build/lib
    
    creating build/lib/pycparser
    
    copying pycparser/__init__.py -> build/lib/pycparser
    
    copying pycparser/_ast_gen.py -> build/lib/pycparser
    
    copying pycparser/_build_tables.py -> build/lib/pycparser
    
    copying pycparser/ast_transforms.py -> build/lib/pycparser
    
    copying pycparser/c_ast.py -> build/lib/pycparser
    
    copying pycparser/c_generator.py -> build/lib/pycparser
    
    copying pycparser/c_lexer.py -> build/lib/pycparser
    
    copying pycparser/c_parser.py -> build/lib/pycparser
    
    copying pycparser/lextab.py -> build/lib/pycparser
    
    copying pycparser/plyparser.py -> build/lib/pycparser
    
    copying pycparser/yacctab.py -> build/lib/pycparser
    
    creating build/lib/pycparser/ply
    
    copying pycparser/ply/__init__.py -> build/lib/pycparser/ply
    
    copying pycparser/ply/cpp.py -> build/lib/pycparser/ply
    
    copying pycparser/ply/ctokens.py -> build/lib/pycparser/ply
    
    copying pycparser/ply/lex.py -> build/lib/pycparser/ply
    
    copying pycparser/ply/yacc.py -> build/lib/pycparser/ply
    
    copying pycparser/_c_ast.cfg -> build/lib/pycparser
    
    running install_lib
    
    creating /Library/Python/2.7/site-packages/pycparser
    
    error: could not create '/Library/Python/2.7/site-packages/pycparser': Permission denied
    
    ----------------------------------------
    Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/fr/dt03ln8j66nblz0z3f0yf6540000gn/T/pip-build-qlcsoi/pycparser/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/fr/dt03ln8j66nblz0z3f0yf6540000gn/T/pip-lZryvJ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/fr/dt03ln8j66nblz0z3f0yf6540000gn/T/pip-build-qlcsoi/pycparser
```

Workaround: `sudo xcode-select --install`

@stevendborrelli I'm concerned about adding complexity for new users that are trying to get started.  I almost wonder if we should revert back to installing bcrypt on the hosts ... thoughts?

**Comment by stevendborrelli** [comment]
I'm thinking about it. 

Passlib has a native bcrypt implementation, but on my mac it takes about 52 seconds to run: 
``` code=python
>>> t= timeit.Timer('bcrypt.encrypt("password")', "from passlib.hash import bcrypt")
>>> t.timeit(number=1)
51.58764600753784
```

Decent performance is going to require native code, which makes the install more complicated. 

I think we need to revert the changes and run it on a host again.

**Comment by BrianHicks** [comment]
it's pretty standard to have to set up xcode on a Mac to install pretty much anything. IMO It would be OK to just add a warning in the relevant places.

**Comment by keithchambers** [comment]
52 seconds is fine -- the xcodeinstall thing took nearly 5 minutes to download and install. Maybe just add a message saying "encrypting ... this will take about 1 minute ...". Security / encryption related tasks are perceived by many users to take a long time away. :+1:

**Comment by BrianHicks** [comment]
It'd probably be possible to make a small wrapper function over it and then catch an `ImportError` if the native version isn't available.

What I meant by saying that xcode is a common task is that I would imagine that a lot of our users would have it installed already. If they've installed anything from Homebrew, it's the first step.

**Comment by stevendborrelli** [comment]
I reverted the change until we get a solution. 

I think always using the pure python method is too slow. I like the fact that the script sets everything up quickly. The script also may be encrypting more than one password in the future.

The import/ImportError pattern is something we can do. Basically try to import bcrypt, and if it fails, put out a warning that native is being used and takes much longer to complete, with a solution of pip install bcrypt.

In order to use the pure python version the env. variable `PASSLIB_BUILTIN_BCRYPT=enabled` has to be set.

**Comment by keithchambers** [comment]
I like this idea.

**Comment by BrianHicks** [comment]
@keithchambers looking at your original error again, that's a permission thing. I'm curious how installing xcode was the workaround there?

**Comment by keithchambers** [comment]
I posted the wrong error.  The error was something like [this](http://stackoverflow.com/questions/22875270/error-installing-bcrypt-with-pip-on-os-x-cant-find-ffi-h-libffi-is-installed) and I found the solution [here](https://github.com/mopidy/pyspotify/issues/135).

**Comment by keithchambers** [comment]
@stevendborrelli do you want to move this out to a later release?

**Comment by stevendborrelli** [comment]
Moving to 0.3 for now.

**Comment by siddharthist** [comment]
We are still encrypting the password on the nodes themselves. Are we interested in trying @BrianHicks's suggestion of a try/catch import and doing something [like this](https://github.com/CiscoCloud/microservices-infrastructure/commit/1dbaf544f519bd7ae7e6dab4aca7f6848c79e6e4) again? I'd be happy to set that up.

**Comment by BrianHicks** [comment]
First-time setup can now be performed in Docker or Vagrant. Closing, please open another ticket if it's still an issue.
