### ISSUE TITLE
Use Centos docker package 

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#141]
Currently we are installing Docker via: http://cbs.centos.org/kojifiles/packages/docker/1.5.0/1.el7/x86_64/docker-1.5.0-1.el7.x86_64.rpm

However, Centos has a 1.5 package available: 

http://mirror.centos.org/centos/7/extras/x86_64/Packages/docker-1.5.0-28.el7.centos.x86_64.rpm

**Comment by keithchambers** [comment]
Makes sense.
