### ISSUE TITLE
DNS service for Mesos frameworks 

### ISSUE THREAD

**Issue by Y4Rv1K** [CiscoCloud/microservices-infrastructure#149]
Just raised problem related to DNS. I try to run HDFS on top of cluster using [mesos-hdfs project](https://github.com/mesosphere/hdfs) and just realised that name resolving is depending on [mesos-dns solution](https://github.com/mesosphere/mesos-dns). 

Just wondering what your plans regarding DNS management for services that will be runing on top of Mesos?

**Comment by keithchambers** [comment]
I think we need to build a bridge from Mesos to Consul similar to [mesos-dns](https://github.com/mesosphere/mesos-dns).

I'm not sure if this would eliminate the need for [Registrator](https://github.com/gliderlabs/registrator) in our environment.

**Comment by stevendborrelli** [comment]
@keithchambers +1....we'll need this very soon for hdfs and elasticsearch

some ideas: 
- using mesos modules (I think this is too complex)
- running a docker container in marathon that talks to the master and updates consul via the api
- updating registrator to connect to 5051 on each follower and pull data to sent to the agent

**Comment by stevendborrelli** [comment]
We're going to target a mesos-consul bridge for the next release, and start working on it right away.

**Comment by dublx** [comment]
+1

**Comment by stevendborrelli** [comment]
@dublx: take a look at https://github.com/CiscoCloud/mesos-consul

**Comment by BrianHicks** [comment]
mesos-consul will be released as part of 0.3.0, it will provide DNS for all services registered in Mesos. This will be in combination with marathon-consul, which will provide enough information to forward to Marathon apps from Haproxy. I think that covers all our bases for discoverability.
