### ISSUE TITLE
security-setup script hangs on low entropy linux hosts due to /dev/random

### ISSUE THREAD

**Issue by matjohn2** [CiscoCloud/microservices-infrastructure#153]
/dev/random blocks in the following code segment when not enough true random entropy is available:

        try:
            with open('/dev/random') as ran:
                bytes = ran.read(size)

It may be worth migrating this to /dev/urandom to ensure we don't block, at the cost of lower quality randomness for the keys generated.

Users experiencing this issue will hang at the following part of the ./security-setup output:

```consul certificate is valid
----> Default ACL policy
set consul_default_acl_policy
=============== Marathon ===============
----> marathon framework authentication ```

**Comment by benschumacher** [comment]
Depending on the utilization, the conversation of /dev/random vs. /dev/urandom is likely incorrect. The issue typically isn't "lower quality", but how can those interfaces be attacked. Two good reads on the subject:

http://www.2uo.de/myths-about-urandom/
http://insanecoding.blogspot.com/2014/05/a-good-idea-with-bad-usage-devurandom.html

That said, I don't think we need these to be absolutely cryptographically secure, just highly unpredictable. Using /dev/urandom (or even Python PRNG) is likely sufficient for these purposes. Alternatively, we could take 256-bits as a seed from /dev/random, and run it through a more secure key expansion algorithm like arc4random:

https://github.com/rolandshoemaker/py-arc4random

 (OpenBSD recently swapped the algorithm under their 'arc4random' implementation to use ChaCha20. http://arc4random.com/)

**Comment by BrianHicks** [comment]
welp, I learned something about randomness sources today. I'll take care of this by grabbing values from `os.urandom`, since it'll work most everywhere. That's probably unpredictable enough to generate secret keys for.
