### ISSUE TITLE
Support overriding logstash/monitoring roles to external destination

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#157]
Support forwarding all collector output to a remote destination if internal ELK is not the preferred solution for the end user/deployment

Support forwarding all logs from Rsyslog to centralized syslog server via TCP or UDP.
Support multiple destination syslog receivers (e.g., log.cisco.com:2515 logging.aas.com:2715)

Support different TCP / UDP ports for each receiver.

Support TLS. TLS is an optional configuration (not mandatory to use this feature).

**Comment by stevendborrelli** [comment]
We'll target Logstash for 0.3, and this feature for 0.4

**Comment by matjohn2** [comment]
@cdmitri is working on different approaches to supporting logging and analytics. This issue is now more generic, there will always be the option to redirect logging to an external syslog-based location

**Comment by mwl** [comment]
Some work here is already carried out in the _Alpha_ repository.

**Comment by stevendborrelli** [comment]
Closing with the merge of #782. Additional providers can be added to the feature backlog.
