### ISSUE TITLE
Route all logs to local logstash agent

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#159]
Ensure all processes and services logs flow to logstash.  In situations where processes/services do not have native rsyslog over TCP/UDP support, configure logstash to read the log file from disk.

Processes/services include (but are not limited to)
* Consul
* Consul Template
* Mesos
* Marathon
* Everything in /var/log

**Comment by loshkovskyi** [comment]
It looks like this task has been already completed.

Here is a list of our roles using `journald`:
````
consul
consul-template
dnsmasq
haproxy
marathon
nginx
vault
zookeeper
````
`collectd` sends logs directly to Logstash.
`mesos` sends logs both to `journald` and `rsyslog`.

We use globbing to forward logs with `rsyslog`:
`*.* @@localhost:1514`
