### ISSUE TITLE
Monitors for load, memory, free disk space

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#160]
![image](https://cloud.githubusercontent.com/assets/1405432/7044312/fbcbbe3c-dda6-11e4-83ae-562d0ba767fb.jpg)

Let's copy these consul checks.

**Comment by corebug** [comment]
I guess this is covered by #53.

**Comment by steel4ge** [comment]
Task has been completed. Here is pull request #252 for this issue.
