### ISSUE TITLE
Deploy logstash 1.5 container to all nodes with rsyslog input and output support

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#164]
Investigate running logstash 1.5 in https://github.com/gliderlabs/docker-alpine.  Time limit to 1-2 days.

Demo: logstash 1.5 in an alpine container receiving and forwarding messages in rsyslog format

Note:  If this is easy to do we will pivot on the rsyslog stories in 0.3 to logstash

**Comment by keithchambers** [comment]
I did some work on this:  https://github.com/keithchambers/docker-logstash

I wasn't able to get it `gliderlabs/alpine` working but I did get `progrium/busybox` to work.

**Comment by loshkovskyi** [comment]
Hello. I did manage to run Logstash 1.5 with Alpine. Please check this repo https://github.com/loshkovskyi/docker-alpine-logstash
Thank you.

**Comment by keithchambers** [comment]
Awesome!  Would you like me to create a new repo in our CiscoCloud organization for it?

**Comment by loshkovskyi** [comment]
Thank you for creating the repo, I will push once my key is added.

On Wed, Apr 15, 2015 at 5:04 PM, Keith Chambers <notifications@github.com>
wrote:

> Awesome! Would you like me to create a new repo in our CiscoCloud
> organization for it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CiscoCloud/microservices-infrastructure/issues/164#issuecomment-93414255>
> .
>



-- 
Kind regards,
Andrii Loshkovskyi

**Comment by loshkovskyi** [comment]
I have put my code here: https://github.com/CiscoCloud/docker-logstash

**Comment by cdmitri** [comment]
Here is the general architecture that we've discussed:

1. Producer (cluster metrics, app, other)
2. Forwarder (dockerized logstash deployed in mi)
3. Collector (LaaS, custom, OSS)

(2) Should be implemented as a `role` in microservices-architecure which after deployment configures everything ready for aut-of-the-box use, based on initial configuration in variables following current conventions for role and other config settings.

Deliverable (definition of done) for this task should be:

* `spark-framework` role
* 'hdfs-standalone' role
* `logging` role with docker implementation discussed
* demo spark app that will run without additional config right after cluster provisioning with logs directed to LaaS

**Comment by loshkovskyi** [comment]
I have committed to branch https://github.com/CiscoCloud/microservices-infrastructure/tree/feature/logstash-role
Why do we need Logstash server on all nodes? I thought it's supposed to be managed from a central place.

**Comment by loshkovskyi** [comment]
Please consider if can close this issue in regard to [d977e](https://github.com/CiscoCloud/microservices-infrastructure/commit/d977ee3dd0b9965dc319285da36a1c8b61d3c574)

**Comment by stevendborrelli** [comment]
Logstash was merged. Closing.
