### ISSUE TITLE
Sample configurations

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#166]
Create inventory files for different configurations. This might be easier to do in terraform with a var:

Single:
1 compute

Small: 
1 leader, 3 followers (medium instance size)

Medium
3 leaders, 3 followers

Large:
3 leaders, 7 followers (large instance size)

@keithchambers let me know your thoughts

**Comment by keithchambers** [comment]
Thinking ...

**Comment by BrianHicks** [comment]
Now that we have Terraform this is pretty easy. A playbook:

```
- hosts: all
  roles: ...

- hosts: role=worker
  roles: ...

- hosts: role=control
  roles: ...
```

We no longer have to worry about inventory files because of the dynamic inventory module. ([plugins/inventory/terraform.py](https://github.com/CiscoCloud/microservices-infrastructure/blob/master/plugins/inventory/terraform.py))

**Comment by siddharthist** [comment]
Is this issue still valid? We now have Terraform configuration for control and worker counts and sizes, and it's pretty well-documented.
