### ISSUE TITLE
Test harness

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#167]
Let's make this a list of things we can set up tests for:

- Nginx
  - force ssl
  - consul auth
  - marathon auth
  - mesos auth

- Consul
  - consul running on each host
  - consul has healthy services
     - each host is green
     - mesos leader
     - zookeeper
     - mesos follower

- Mesos
   - proper number of leaders
   - proper number of followers
   - firewalls in place

- Marathon
    - each marathon node is up
    - create job
    - firewalls in place

- Zookeeper
    - zookeeper nodes are up
    - znode acs are correct

**Comment by cdmitri** [comment]
SS QA team is looking at this

**Comment by stevendborrelli** [comment]
We're developing a consul-friendly framework to do this.  This will be part of 0.3.1 or  0.4.

**Comment by ohal** [comment]
we've already started automated tests developing.
pls, see section - Robot-framework automated testing - here https://github.com/CiscoCloud/microservices-infrastructure/blob/qa/features-master-integration/docs/jenkins_ci.md

**Comment by stevendborrelli** [comment]
@ohai How far have you gotten with the test creation? Is that document up to date?

**Comment by ohal** [comment]
I've updated document.
So far the next components are covered by automated testing:
- Consul
- HDFS
- Mesos
- Marathon

Currently Spark and Kafka components tests are under investigation/development.
Here you can find test report http://173.39.214.186/job/PR-to-qa-features-master-integration-CCS-MI-US-INTERNAL-1-QA-1/49/robot/report/log.html

**Comment by ohal** [comment]
from now each PR and COMMIT to master branch are going to be deployed and tested as cluster with core services, also zookeeper smoke and latency tests are configured as post deployment step.
here you can find report: [robot framework report](http://173.39.214.186/view/CCS-MI-US-INTERNAL-1-QA-1/job/COMMIT-to-master-CCS-MI-US-INTERNAL-1-QA-1/63/robot/report/report.html "robot framework report")
after testing of PR status will be set by the testing results.

**Comment by siddharthist** [comment]
Distributive has been integrated entirely, new tests should be added there. We do need more coverage, but this issue doesn't really touch on our new strategy.
