### ISSUE TITLE
How can I shutdown framework? 

### ISSUE THREAD

**Issue by Y4Rv1K** [CiscoCloud/microservices-infrastructure#168]
I had ability to terminate framework at mesos using `/master/shutdown` 
But at latest build have success

     http -a admin:admin  --verify=no --form POST  https://master.mesos:5050/master/shutdown frameworkId=20150409-145309-452011949-15050-21032
    
    No framework found with specified ID

Just wondering how can I terminate framework at MI?

**Comment by ChrisAubuchon** [comment]
Can you verify that `master.mesos` is the leader? I received the `No framework found with specified ID` when connecting to one of the the non-leader masters and success when connecting to the leader.

**Comment by Y4Rv1K** [comment]
You have point. Now `master.mesos` point to 3 mesos masters and `leader.mesos`  to leader.

**Comment by ChrisAubuchon** [comment]
So is it working using `leader.mesos`?

**Comment by Y4Rv1K** [comment]
Actually it's not. Still digging into it.

**Comment by Y4Rv1K** [comment]
Yes it did. Now I can't go though authentication:)

   $ http -a  admin:admin  --verify=no --form POST  https://leader.mesos:5050/master/shutdown frameworkId=20150406-173829-4210108333-15050-24101-0000                   │
    HTTP/1.1 401 Unauthorized                                                                        
    Connection: keep-alive                                                                         
    Content-Length: 30                                                                               
    Date: Fri, 10 Apr 2015 10:12:26 GMT                                                       
    Server: nginx/1.6.2                                                                           
    WWW-authenticate: Basic realm="Mesos master"                                            
                                                                                     
    Could not authenticate 'admin'

So looks like issue can be closed.
