### ISSUE TITLE
Not able to authenticate at mesos using cURL/HTTPie

### ISSUE THREAD

**Issue by Y4Rv1K** [CiscoCloud/microservices-infrastructure#171]
Can be simple misuse but I'm not able terminate framework by using URI `master/shutdown` and cURL/HTTPie tools: 

    http --verify=no -a admin:admin --form POST https://leader.mesos:5050/master/shutdown frameworkId=20150406-173829-4210108333-15050-24101-0000
    WWW-authenticate: Basic realm="Mesos master”

    Could not authenticate 'admin'

Any thoughts about it?

**Comment by stevendborrelli** [comment]
Let me test on one of our clusters.

**Comment by ChrisAubuchon** [comment]
This is internal to Mesos. It does its own authentication on a framework shutdown request. The admin account has to be in /etc/mesos/credentials to work.

**Comment by Y4Rv1K** [comment]
I see. In this case even if I installed hdfs as framework without authentication I have no easy way to shutdown it because mesos [framework authentication](http://mesos.apache.org/documentation/latest/authorization/) still working? 

    In the same vein, when a user/principal attempts to shutdown a framework through the “/shutdown” 
    HTTP endpoint on the master, “shutdown_frameworks” ACLs are checked to see if the principal
    is authorized to shutdown the given framework. 
    If not authorized, the shutdown is rejected and the user receives an Unauthorized HTTP response.

**Comment by ChrisAubuchon** [comment]
I think we have two possible solutions here.

1. Add the admin account to `/etc/mesos/credentials`
2. Add the Mesos credentials to the nginx proxy

Of the two, I prefer 2 because Mesos' credentials file is stored in plain text on the file system and, in 0.3, in plain text in Consul.

**Comment by ChrisAubuchon** [comment]
Check out https://github.com/CiscoCloud/microservices-infrastructure/tree/0.3/mesos-consul-creds
That adds the admin account to Mesos' credentials file and adds the Mesos credentials to the nginx proxy.

**Comment by ChrisAubuchon** [comment]
@Y4Rv1K Have you tried with the 0.3/mesos-consul-creds branch? If it's working I'll submit a pull request.

**Comment by Y4Rv1K** [comment]
Will proceed with validation as soon as possible.

**Comment by keithchambers** [comment]
I'm going to assume this issues is resolved and close it out.

@Y4Rv1K please re-open this issue is it is not.

Thanks!

**Comment by Y4Rv1K** [comment]
Yes. It is. Thank you
