### ISSUE TITLE
security-setup: Add additional confirmation prompt for password

### ISSUE THREAD

**Issue by benschumacher** [CiscoCloud/microservices-infrastructure#173]
Currently running the `security-setup` asks for a password:

```
----> admin password
Admin Password: 
set nginx admin password
```

But it doesn't prompt for confirmation of that password. This means that if user mistypes their password, we would end up recording typo'd version. While they can simply rerun the utility, it'd be simple (and consistent with similar tools) to simply prompt for confirmation:

```
----> admin password
Admin Password: 
Confirm Admin Password:
set nginx admin password
```

**Comment by keithchambers** [comment]
+1

**Comment by tymofii-polekhin** [comment]
https://github.com/CiscoCloud/microservices-infrastructure/pull/184

**Comment by keithchambers** [comment]
Merged!
