### ISSUE TITLE
security-setup: disable auth in command line

### ISSUE THREAD

**Issue by cdmitri** [CiscoCloud/microservices-infrastructure#176]
Since we're working through authentication for some of the components, we should have a fast way to disable it if necessary.

Proposing:
```
$ security-setup --help
...
--no-authenticate-followers
                           no follower authentication
--no-authenticate-frameworks
                           no framework authentication
...
```

Which will disable writing out credentials for followers and/or frameworks to `security.yml` which in turn will disable authentication,

Ex.:

```
security.yml:
...
#marathon_principal: marathon
#marathon_secret: <secret>
#mesos_credentials:
#- {principal: marathon, secret: <secret>}
#mesos_follower_principal: follower
#mesos_follower_secret: <secret>
...
```

Related to: #145

**Comment by keithchambers** [comment]
I think this is reasonable. Of cours we want everything to be tight a secure but we also community adoption.

I'd like to see us add this feature AND, for every framework that doesn't support authentication, open an issue on our side and against the framework's project.

Thoughts?

**Comment by Y4Rv1K** [comment]
Have proposition from @cdmitri =)

    --no-firewall

**Comment by cdmitri** [comment]
@keithchambers yes, definitely, we'll follow with all the security development for frameworks and tracking an issue. Some frameworks including spark not only are working on mesos security, but also have their own security mechanisms (SSL, ACL in multiple modes), so there is a lot of interesting development there that we should leverage for production use.

These 3 options to disable security completely is mostly for development and running frameworks that don't have that support as exception - I actually like that fact that we have auth on by default, as it adds the focus on it form the start.

D.

**Comment by ObjectiveJoe** [comment]
No security is almost always a bad idea. Once you start that direction and people start developing to it you may have a hard time rolling it back.

Joe

**Comment by cdmitri** [comment]
Hi Joe,

I agree with you, we should have security on for default and have a strong focus on supporting and developing secure frameworks. It's good to have an option to isolate the issues quickly however, for example you can always turn off SELinux with a single config line if you need to :)

Cheers,
D.

**Comment by keithchambers** [comment]
@ObjectiveJoe I agree with your point but it's a balancing act.  I'd rather have no security than no adoption. :-1:

Security is always going to be a focus for our project.  We need to start where we can and build up from there.  It's going to take a little time but we will get there.

**Comment by Y4Rv1K** [comment]
Can we start with draft "List of MI ports"   that should be open at firewall?

**Comment by tymofii-polekhin** [comment]
https://github.com/CiscoCloud/microservices-infrastructure/tree/feature/disable-auth

**Comment by ChrisAubuchon** [comment]
Can we look at https://github.com/CiscoCloud/microservices-infrastructure/pull/239 and see if it addresses the issue?

**Comment by tymofii-polekhin** [comment]
I think we may close this issue since PR #239 was merged into master?

**Comment by BrianHicks** [comment]
Closing, this was taken care of by #239.
