### ISSUE TITLE
Different flavors for control nodes vs. resource nodes

### ISSUE THREAD

**Issue by kenjones-cisco** [CiscoCloud/microservices-infrastructure#177]
I did a manual workaround for this yesterday but was looking to create put something in place to enable the functionality today.

The provided inventory files indicate via comments the control groups and the resource groups but there are not groups specifically defined by those group names. For the openstack provision process some variables are defined at the dc level and the others at the all level.

```
all --> os_flavor_include, image, etc.
|
dc1 --> tenant/auth variables

The need is for something like this:

all --> os_flavor_include (default), image, etc.
|
dc1 --> tenant/auth variables
|
control --> os_flavor_include
|
resource --> os_flavor_include
```

Having small/medium control nodes is appropriate but the resource nodes should be able to support many services running within them and will probably be larger in size.

I'm still thinking through the implementation, but wanted to take feedback before starting to make any changes.

**Comment by cdmitri** [comment]
+1, we're had some thoughts around that on the framework side as well, will have open some issues and proposals tomorrow, in general we could use at least one more iteration/testing of this structure.

Cheers,
D.

**Comment by keithchambers** [comment]
I'm open to this for sure.

**Comment by kenjones-cisco** [comment]
FYI, I made some changes to enable the above. Going to test it out tomorrow morning and then I'll submit the a PR for feedback.

**Comment by stevendborrelli** [comment]
This was added to the Terraform configuration, via #367. Marking as closed.
