### ISSUE TITLE
ansible: increase debugging verbosity, perform logging and cluster deployment automated test execution.

### ISSUE THREAD

**Issue by dimmk0** [CiscoCloud/microservices-infrastructure#178]
**Problem:**

Recent testing shows that there are periodic/intermittent issues that we need to address.

* /etc/hosts files are not always updated on all maches
* after the completed run not all hosts can be pinged with ansible
* multiple runs of the same playbook fix the issue
* OpenStack nova API version wrong
* possible other issues

As we're testing and deploying to multiple DC's, we need to gather all the necessary data to analyze and fix the issues in both scripts and infrastructure itself.

**Proposal:**

For microservices-infrastructure provisioning in test and staging mode:

1. Increase verbosity ex. ```ansible -vvvv ...```
2. In above is not sufficient add instrumentation to select ansible tasks

For example:
```
- name: Provision VM
...
security_groups: default
register: provision_vm_result
- debug: var=provision_vm_result
  when: debug == "yes"
...
````
3. Gather run results with above options enabled and analyze them for patters of network or other issues.
  * Present statistical aggregated data in table and/or graph format, such as location, time and frequency of the particular occurring issue. 
  * Present specific issue detail for root cause and followup with infrastructure teams

4. Create an process and environments for continuous execution of the above methodology to gather extensive results across time for a full actionable picture and subsequent root cause and improvement by the infrastructure teams and/or provisioning code.

SoftServe team will take this task when the scope is approved.

**Comment by keithchambers** [comment]
This makes sense to me @cdmitri

Anything that improves usability is :+1: !

**Comment by dimmk0** [comment]
I'm working on this issue.

**Comment by siddharthist** [comment]
This issue is not broken down enough. CI is now being done through Distributive, and deployment via mi-deploy which will eventually become a separate Ansible/Terraform testing suite.
