### ISSUE TITLE
os_flavor_ram value may be silently ignored

### ISSUE THREAD

**Issue by OleksandrBerchenko** [CiscoCloud/microservices-infrastructure#182]
-1. Provision hosts using the following configuration in all.yml:

os_flavor_ram: 4096
os_flavor_include: GP2-Medium
os_image_name: centos-7_x86_64-2015-01-27-v6

Result: GP2-Medium | 4GB RAM | 1 VCPU | 50.0GB Disk [as expected]

-2. Provision hosts using the following configuration in all.yml:

os_flavor_ram: 8192
os_flavor_include: GP2-Large
os_image_name: centos-7_x86_64-2015-01-27-v6

Result: GP2-Large | 8GB RAM | 2 VCPU | 50.0GB Disk [as expected]

-3. Provision hosts using the following configuration in all.yml:

os_flavor_ram: 8192
os_flavor_include: GP2-Medium
os_image_name: centos-7_x86_64-2015-01-27-v6

Result:

TASK: [nova_compute ] *********************************************************
failed: [test-host-02] => {"failed": true}
msg: Error finding flavor with 8192MB of RAM
failed: [test-host-01] => {"failed": true}
msg: Error finding flavor with 8192MB of RAM

FATAL: all hosts have already failed -- aborting

This is probably an expected result too: GP2-Medium flavor can't have so much RAM.

-4. Provision hosts using the following configuration in all.yml:

os_flavor_ram: 4096
os_flavor_include: GP2-Large
os_image_name: centos-7_x86_64-2015-01-27-v6

Result: GP2-Large | 8GB RAM | 2 VCPU | 50.0GB Disk

OpenStack silently ignored "4096" value and created a usual GP2-Large host with 8GB RAM.

Do we ever need os_flavor_ram value?  Is there any flavor that may have several RAM options?

Thanks!

**Comment by ChrisAubuchon** [comment]
os_flavor_ram is required by Ansible to determine the flavor to use. os_flavor_include is used to differentiate between different flavors with the same amount of RAM. 

Relevant code from OpenStack Ansible module
```
        for flavor in sorted(nova.flavors.list(), key=operator.attrgetter('ram')):
            if (flavor.ram >= module.params['flavor_ram'] and
                    (not module.params['flavor_include'] or module.params['flavor_include'] in flavor.name)):
                return flavor.id
```

**Comment by OleksandrBerchenko** [comment]
Ok, thank for the explanation.

So, "os_flavor_ram" actually woks as a "minimum ram", correct?  That's a bit confusing.  Can we display a warning, when a different amount of RAM is actually allocated?  Or possibly rename "os_flavor_ram" to something like "minimum_os_flavor_ram" in our file?  Or let me know, if it's confusing only for me :)

Thanks!

**Comment by keithchambers** [comment]
@OleksandrBerchenko can you create a PR please?

**Comment by galanoff** [comment]
Dear all,

> That's a bit confusing.

Just have a look at original Ansible doc and you would not need to debug / look in code for obvious things.

http://docs.ansible.com/nova_compute_module.html 

```
flavor_ram - 
The minimum amount of ram in MB that the flavor in which the new VM has to be created must have. Mutually exclusive with flavor_id (added in Ansible 1.8)
```

--
Kyryl

**Comment by keithchambers** [comment]
@galanoff good point.  Do you recommend we keep the variable name as is?

**Comment by OleksandrBerchenko** [comment]
Thanks, Kirill!  Yes, sometimes it makes sense to look into documentation.

Possibly it makes sense not to change anything.
