### ISSUE TITLE
Restart cluster

### ISSUE THREAD

**Issue by kenjones-cisco** [CiscoCloud/microservices-infrastructure#183]
The underlying environment was affected by maintenance last night, and as such some processes were no longer running. I performed a soft reboot on my VMs and then to restore everything back to working order I re-ran the ansible site.yml. Everything seems to go well up to the point where it tries to do the Zookeeper ACLs. The error was similar to the problem I saw originally, during installation last week, that there was no consul leader.

Since creating a fresh cluster works with no issues it is obviously not a security group issue where ports are not open.

It seems that process to create the cluster does not also handle starting the cluster backup again if processes are down.

Is that normal and expected behavior, and reload/restart and even upgrade processes will be coming in the future?

**Comment by ChrisAubuchon** [comment]
Did you use playbooks/reboot-hosts.yml to reboot the hosts? Sounds like Consul lost quorum and couldn't recover easily.

**Comment by kenjones-cisco** [comment]
No I did not, I had used the soft reboot in the horizon UI.

After looking at the reboot hosts playbook I can see that would have been a preferred approach for doing a reboot.

**Comment by kenjones-cisco** [comment]
#187 merged; I'll consider this as a documentation issue and user error, closing issue.
Thanks
