### ISSUE TITLE
Ansible uses "all.yml.new" instead of "all.yml"

### ISSUE THREAD

**Issue by OleksandrBerchenko** [CiscoCloud/microservices-infrastructure#185]
-1. There is a single "all.yml":

```
[oberchen@gluon-int-edge-01 microservices-infrastructure]$ ls inventory/group_vars/all/
all.yml  users.yml
```

```
[oberchen@gluon-int-edge-01 microservices-infrastructure]$ cat inventory/group_vars/all/all.yml
---
ansible_ssh_user: centos
ansible_ssh_key: ansible_key
ansible_ssh_pubkey: "{{ lookup('file','~/.ssh/id_rsa.pub') }}"

os_flavor_ram: 4096
os_flavor_include: GP2-Medium
os_image_name: centos-7_x86_64-2015-01-27-v6

consul_servers_group: consul_servers
consul_dns_domain: consul
```

Run provision-hosts.yml.  Everything works as expected: "GP2-Medium | 4GB RAM | 2 VCPU | 50.0GB Disk" hosts have been created.

-2. Destroy the hosts.  Put some backup version of "all.yml" in the some folder, for example "all.yml.new":

```
[oberchen@gluon-int-edge-01 microservices-infrastructure]$ ls inventory/group_vars/all/
all.yml  all.yml.new  users.yml
```

```
[oberchen@gluon-int-edge-01 microservices-infrastructure]$ cat inventory/group_vars/all/all.yml.new
---
ansible_ssh_user: centos
ansible_ssh_key: ansible_key
ansible_ssh_pubkey: "{{ lookup('file','~/.ssh/id_rsa.pub') }}"

os_flavor_ram: 8192
os_flavor_include: GP2-Large
os_image_name: centos-7_x86_64-2015-01-27-v6

consul_servers_group: consul_servers
consul_dns_domain: consul
```

Run provision-hosts.yml.  Unexpectedly, "GP2-Large | 8GB RAM | 2 VCPU | 50.0GB Disk" hosts have been created, using the information from "all.yml.new" not "all.yml".

It's extremely confusing.  At least for me, who had several copies of "all.yml" :)

Thanks!

**Comment by stevendborrelli** [comment]
Ansible docs are not really clear about this in http://docs.ansible.com/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable, but what I have seen is that when a var is defined more than once, the last update to the var is the one that gets used. 

My guess is that all.yml.new is being read after all.yml.

**Comment by OleksandrBerchenko** [comment]
So, Ansible just reads all the files, even those which don't have "yml" extension, correct?

**Comment by keithchambers** [comment]
I'm going to close this since there is nothing we can do to prevent this.
