### ISSUE TITLE
"dc1" and "dc2" are hardcoded in site.yml

### ISSUE THREAD

**Issue by OleksandrBerchenko** [CiscoCloud/microservices-infrastructure#186]
My "naive" idea to create my own DC files (like "dc_rillaar" and "dc_spark") didn't work because both "dc1" and "dc2" are simply hardcoded in site.yml.

Is it possible not to hardcode any DCs in site.yml, but to extract actual names from the passed inventory file?

```
# datacenters
[dc_rillaar]
```

Also I have revealed that "." (dot) is not an allowed char for the DC name. "dc_rillaar.new" crashed with the following error:

```
TASK: [consul | wait for leader] **********************************************
failed: [spark-master-02] => {"elapsed": 300, "failed": true}
msg: Timeout when waiting for 127.0.0.1:8301
...
```

Not sure whether it is possible to fix the second issue or not (it might be a reasonable limitation if "." is used as a separator somewhere).

What do you think?

Thanks!

**Comment by stevendborrelli** [comment]
Maybe we can use groups of groups? Here is the ansible doc: http://docs.ansible.com/intro_inventory.html#groups-of-groups-and-group-variables

So our inventory file could be something like: 

```
[dc1] 
dc_rillaar

[dc2]
dc_spark
```

As for part the "." issue, that might cause problems because host matching can also be against dns names.

**Comment by OleksandrBerchenko** [comment]
I will try it, thank you.

Well, what if I want to create a cluster that spreads through 3 or more datacenters?  site.yml is still not very flexible.

**Comment by stevendborrelli** [comment]
@OleksandrBerchenko have you been able to test this?

**Comment by OleksandrBerchenko** [comment]
Unfortunately, not yet :(  I will do my best to try it tomorrow.

Thanks!

**Comment by OleksandrBerchenko** [comment]
Hm...  Reading http://docs.ansible.com/intro_inventory.html.  Could you please describe your idea again?

For example, I have inventory/test-datacenter:

```
# all
[all]
test-master-[01:03]
test-slave-[01:02]

# datacenters
[dc1]
test-master-[01:03]
test-slave-[01:02]

...
```

and I have inventory/group_vars/rillaar:

```
os_auth_url: https://eu-amsterdam-1.cloud.cisco.com:5000/v2.0
os_tenant_name: RILLAAR-EU-AMSTERDAM-1-SAND
os_tenant_id: 7a11dc0218dd47a2a30d08015491396e
os_net_id: e7b1be4f-e0d2-4024-948f-b9e6c4911123
consul_dc: rillaar
security_group: microservice
```

What exactly should I change?

Thanks!

**Comment by cdmitri** [comment]
@OleksandrBerchenko in this example, you use config like @stevendborrelli  has mentioned, but your inventory/group_vars/rillaar becomes inventory/group_vars/dc_rillaar or similar, just another level of vars that will get picked up by higher level. You can definitely do it if you move the vars in inventory/group_vars/rillaar directly into the same file as the ansible docs describe - try to do that first and then see if the same happens when you move them to a file

**Comment by BrianHicks** [comment]
This is supported by the new Terraform configuration options. See the docs on the feature/terraform-docs branch.
