### ISSUE TITLE
firewalld prevents consul communication

### ISSUE THREAD

**Issue by bketelsen** [CiscoCloud/microservices-infrastructure#193]
Centos ships with firewalld enabled by default.  Consul can't make quorum with firewalld enabled.  

Best fix:  Create a playbook to enable all required ports for consul in firewalld
Workaround fix: disable firewalld

**Comment by stevendborrelli** [comment]
@bketelsen we'll take a look, as we haven't seen this in our base Centos 7.0 images. 

What CentOS image are you using?

**Comment by bketelsen** [comment]
this happened with both the CentOS ISO i pulled directly from centos, and my Rackspace cloud account which is CentOS Linux release 7.1.1503 (Core)

**Comment by stevendborrelli** [comment]
I think we should disable firewalld for iptables service for now, as we have some iptables-specific code. 

We're moving towards using 7.1.1503 with (hopefully) overlay support, so this issue needs to re addressed.

**Comment by bketelsen** [comment]
Where is the iptables code?

On Mon, Apr 20, 2015 at 11:24 AM, Steven Borrelli <notifications@github.com>
wrote:

> I think we should disable firewalld for iptables service for now, as we
> have some iptables-specific code.
>
> We're moving towards using 7.1.1503 with (hopefully) overlay support, so
> this issue needs to re addressed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CiscoCloud/microservices-infrastructure/issues/193#issuecomment-94482835>
> .
>



-- 

----
Brian Ketelsen
bketelsen <at> gmail <dot> com

**Comment by stevendborrelli** [comment]
Marathon and Mesos use consul-template to dynamically change iptables, by dropping config files in `/etc/consul-template/config.d`:

See the mesos/marathon default tasks and these template files:

Mesos:
https://github.com/CiscoCloud/microservices-infrastructure/blob/master/roles/mesos/templates/mesos-leader-iptables.tmpl.j2

Marathon: 
https://github.com/CiscoCloud/microservices-infrastructure/blob/master/roles/marathon/templates/marathon-iptables.tmpl.j2

**Comment by bketelsen** [comment]
Thanks!
I'll send a PR in a minute to disable firewalld


On Mon, Apr 20, 2015 at 11:32 AM, Steven Borrelli <notifications@github.com>
wrote:

> Marathon and Mesos use consul-template to dynamically change iptables, by
> dropping config files in /etc/consul-template/config.d:
>
> See the mesos/marathon default tasks and these template files:
>
> Mesos:
>
> https://github.com/CiscoCloud/microservices-infrastructure/blob/master/roles/mesos/templates/mesos-leader-iptables.tmpl.j2
>
> Marathon:
>
> https://github.com/CiscoCloud/microservices-infrastructure/blob/master/roles/marathon/templates/marathon-iptables.tmpl.j2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CiscoCloud/microservices-infrastructure/issues/193#issuecomment-94484633>
> .
>



-- 

----
Brian Ketelsen
bketelsen <at> gmail <dot> com
