### ISSUE TITLE
Non-HTTPS Homepage Link in Readme.md and Description

### ISSUE THREAD

**Issue by afmsavage** [CiscoCloud/microservices-infrastructure#2030]
The link provided to the Mantl homepage in the repo description as well as the two links for Getting Started Guide and Documentation are all non-HTTPS.  Would love to see these updated to use HTTPS or have your site redirect to HTTPS when visitors access the HTTP version.

**Comment by Theaxiom** [comment]
Unfortunately @afmsavage we have no way to update the homepage. Mantl is pretty much dead in favor of Rancher.

**Comment by somethingwithproof** [comment]
I know none of us have had time to work on it. Which sucks.
