### ISSUE TITLE
Make 1.9 the minimum version of ansible

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#209]
1.8 doesn't seem to detect Centos systemd services correctly, and will try to run `initctl`. 

@BrianHicks: any problems with updating requirements.txt to 1.9?

**Comment by BrianHicks** [comment]
We've already had people fixing various issues by upgrading to 1.9. I'd say go ahead and make it `==1.9`.

**Comment by keithchambers** [comment]
Merged.
