### ISSUE TITLE
Spark email address bounces

### ISSUE THREAD

**Issue by bbaassssiiee** [CiscoCloud/microservices-infrastructure#217]
"The team collaborates on Cisco Spark and GitHub Issues. Send an email to microservices-infrastructure-spark-room@external.cisco.com and we’ll add you to our Cisco Spark room!"

This email address does not exist.

Final-Recipient: rfc822;microservices-infrastructure-spark-room@external.cisco.com
Action: failed
Status: 5.0.0 (permanent failure)
Remote-MTA: dns; [173.36.13.143]
Diagnostic-Code: smtp; 5.1.0 - Unknown address error 550-'5.1.1 <microservices-infrastructure-spark-room@external.cisco.com>... User unknown' (delivery attempts: 0)

**Comment by keithchambers** [comment]
Hmmm let me check.

**Comment by keithchambers** [comment]
@bbaassssiiee check out https://github.com/CiscoCloud/microservices-infrastructure/commit/29a1775593df93359890565eb4633a4f6ff494f0 ... we're on Gitter now!  Hit us up!
