### ISSUE TITLE
Vault failed to restart on Vagrant up current master

### ISSUE THREAD

**Issue by andreimc** [CiscoCloud/microservices-infrastructure#231]
NOTIFIED: [vault | restart vault] *********************************************
failed: [default] => {"changed": true, "cmd": ["systemctl", "reload", "vault"], "delta": "0:00:00.038964", "end": "2015-05-01 09:23:49.018432", "rc": 1, "start": "2015-05-01 09:23:48.979468", "warnings": []}
stderr: Job for vault.service failed. See 'systemctl status vault.service' and 'journalctl -xn' for details.

Works if provisioned again

**Comment by ChrisAubuchon** [comment]
Try changing in `roles/vault/handlers/main.yml` the command of the `restart vault` handler from `systemctl reload vault` to `systemctl restart vault`.
