### ISSUE TITLE
Port range missing in Vagrant file (4000..5000)

### ISSUE THREAD

**Issue by andreimc** [CiscoCloud/microservices-infrastructure#233]
As specified in roles/mesos/defaults/main.yml:

mesos_resources: "ports(*):[4000-5000, 31000-32000]"

In vagrant file only 31 to 32k are bound.

**Comment by keithchambers** [comment]
Thanks for the issue and PR!

Just curious -- what breaks without this?

**Comment by andreimc** [comment]
Basically you can not access any containers that you run and they fall under the 4-5k range which is half your stuff.

**Comment by keithchambers** [comment]
I see -- good catch!  :+1:

I'll merge your PR now !

Thank you @andreimc !
