### ISSUE TITLE
Zookeeper running on 3 ports in datacenter setup

### ISSUE THREAD

**Issue by andreimc** [CiscoCloud/microservices-infrastructure#235]
Hey guys,

I was spinning up on this on aws and zookeeper is running on all 2181, 2888, 3888 even tho I run zookeeper on 3 servers.

Should this be the case or do I need to overwrite the following:
zookeeper_ports: "-p 2181:2181 -p 2888:2888 -p 3888:3888"
with 
zookeeper_ports: "-p 2181:2181"

Regards
Andrei

**Comment by stevendborrelli** [comment]
Ports 2888 and 3888 are used within the Zookeeper for quorum and leader elections. 

See http://docs.hortonworks.com/HDPDocuments/HDP1/HDP-1.3.7/bk_using_Ambari_book/content/reference_chap2_4b_2x.html. 

If you are using more than one ZK node, they are required.

**Comment by andreimc** [comment]
Thanks :)
