### ISSUE TITLE
Add coarse-grained options to security-setup 

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#247]
Add coarse-grained `true|false` options for:

`--disable` which disables security for everything
`--enable` which disables security for everything
`--consul=false` which enables/disabled all Consul security
`--mesos=false` which enables/disabled all Mesos security
`--marathon=false` which enables/disabled all Marathon security
`--iptables=false` which enables/disables iptables for all

See: https://github.com/CiscoCloud/microservices-infrastructure/pull/239

**Comment by BrianHicks** [comment]
I'm going to simplify this down a little bit:

 - [ ] `--disable` disables everything
 - [ ] `--disable-consul` disables all Consul security
 - [ ] `--disable-mesos` disables all Mesos security
 - [ ] `--disable-marathon` disables all Marathon security
 - [ ] `--disable-iptables` disables all iptables rules

These will be high level options whose absence implies that everything should be *enabled*. They will be in a group called something like "coarse-grained options".

Does that work for you, @keithchambers?

**Comment by BrianHicks** [comment]
Here's what I've got:

```
Broad Disable Options:
  disable security for entire components. This overrides any more specific options set from the sections below.

  --disable             disable all security. This overrides everything. (default: False)
  --consul CONSUL       Enable Consul security. This overrides all other Consul options. (default: True)
  --mesos MESOS         Enable Mesos security. This overrides all other Mesos options. (default: True)
  --marathon MARATHON   Enable Marathon security. This overrides all other Marathon options. (default: True)
  --iptables IPTABLES   Use iptables rules. This overrides all other options related to iptables. (default: True)
```
