### ISSUE TITLE
Bootstrap Vagrant box with just 'git clone && vagrant up'

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#254]
I watched a number of people try to get started with microservices-infrastructure who did *not* read the instructions.  They all just wanted to do a `vagrant up` and most gave up when that didn't work.

We need to simplify the process for new developers -- it has to be easy easy easy.  Improvements should include:
* Support VirtualBox and VMware vagrant providers
* Require nothing but `vagrant up` to bring up the system (no `pip install -r requirements.txt`)
* Disable security by default for Vagrant deploys
* Forward fewer IP ports to reduce risk of conflict

**Comment by BrianHicks** [comment]
@ChrisAubuchon and I talked about this, and came up with the following:

 - mount the repository at a known location in the VM
 - install Ansible on the VM in a shell provisioner (`pip install -r requirements.txt`)
 - set up security in a shell provisioner
 - run Ansible in a shell provisioner

So really just all the steps that should be taken anyway, just in the VM. This will mean that if `security-setup` has already been run, the `security.yml` will just be used. If it hasn't, it will be created for future runs.

**Comment by keithchambers** [comment]
Let's bang it out!

**Comment by ChrisAubuchon** [comment]
This breaks with the merge of 'feature/image-build'. The 'CiscoCloud/microservices-infrastructure' Vagrant box needs to be able to mount synced folders for this plan to work.

**Comment by keithchambers** [comment]
You're right. Probably a good time to add vagrant shared directory via SSH/SCP vs. the brittle kmod approach.  This way we can support any Vagrant provider (e.g., VirtualBox, VMware, OpenStack, etc). I won't have time to tackle this. @BrianHicks can you take this on too? Thx!

**Comment by ChrisAubuchon** [comment]
Check out https://github.com/CiscoCloud/microservices-infrastructure/tree/fix/gh-254.

All of the configuration is done inside the VM so there shouldn't be any external requirements besides Vagrant.

I think a lot of what is in `vagrant/provision.sh` can be moved to the CiscoCloud/microservices-infrastructure Vagrant box.

I had to reset the wait handlers to use the absolute path. For some reason it doesn't have /usr/local/bin in the PATH. Will need to look into further.

**Comment by BrianHicks** [comment]
This mostly works, but it's slow because our base image is a little outdated (it needs new container versions so it can come up quickly.) Can we create a new base image on Atlas for this?

**Comment by BrianHicks** [comment]
as of ef02f93 this issue will be closed with #357.
