### ISSUE TITLE
Remove Registrator

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#255]
Chris and Brian -- with the new mesos-consul and marathon-consul bridges can we get rid of Registrator?  I'm thinking we can statically register ZK, HAProxy, etc in to Consul instead.

Make sense?

**Comment by ChrisAubuchon** [comment]
I think ZK is the only thing still using registrator. We will have to rework it a bit but it's certainly doable.

**Comment by keithchambers** [comment]
Cool -- let's rip it out.

**Comment by ChrisAubuchon** [comment]
https://github.com/CiscoCloud/microservices-infrastructure/pull/263
