### ISSUE TITLE
Operationalize Zookeeper

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#259]
There is a lot required to run Zookeeper reliably in production including back/restore, purging transactions logs, rolling upgrades, etc. Tools like Exhibitor help to make it simpler.

We need to weigh our options, create a design, and then implement.

**Comment by stevendborrelli** [comment]
Tasks: 
- [ ] test cluster after deploy (maybe use https://github.com/phunt/zk-smoketest)
- [ ] configure backup of zk transactions from zookeeper-data-volume container
- [ ] log rotation
- [ ] metrics
- [ ] consul agent monitoring

**Comment by cmgc** [comment]
I'm currently working on this issue.

**Comment by corebug** [comment]
Possibly we can collect Zookeper metrics via collectd plugin?

**Comment by cmgc** [comment]
Log rotation already [implemented.] (https://github.com/CiscoCloud/microservices-infrastructure/blob/master/roles/logrotate/files/docker)

**Comment by cmgc** [comment]
Steven, please clarify about Log rotation, as I see we have [some](https://github.com/CiscoCloud/microservices-infrastructure/blob/master/roles/logrotate/files/docker) role. This is what did you mean?

And about second task, for now zookeeper runs in docker with ciscocloud/data-volume as volume where we have in-memory database snapshots (/var/lib/zookeeper), and transaction log (/var/log/zookeeper), so can you please clarify about this task?

**Comment by cmgc** [comment]
For now I manual did some tests (smoketest and latency) with https://github.com/phunt/zk-smoketest.
Smoke test result [here](https://gist.github.com/cmgc/7b3c25b36d59f1bc4ee5) .
Latency test result [here](https://gist.github.com/cmgc/2cede463b6a0f70c9b4e) and [here detailed](https://gist.github.com/cmgc/57eeb6a3f5119092160d).
Will be discussed about integration these tests to after deploy step.

**Comment by ohal** [comment]
if I'm not wrong, such testing can be done only internally, because 2181 port is closed to public
so, if we're going to automate some tests (smoketest and latency) we have to think about the approach, so far I see the next solutions:
1 - deploy code to deployed fresh host in cluster (git, rpm etc), run, get the console output, it can take some time
2 - install/keep in tenant already configured host, something like 'friend' host or 'spy', so it can see all ports
which way will be better?

**Comment by corebug** [comment]
Metrics are gathered by collectd (https://github.com/CiscoCloud/microservices-infrastructure/pull/291).

**Comment by stevendborrelli** [comment]
Port 2181 is open across the cluster. 

One thing we can do is integrate the local tests into consul, so that the local system agent runs it. 

Exit codes are as follows:
0 -> service passing
1 -> service warning
any other exit code -> service critical

The zookeeper role already has a simple script to monitor the service, we can probably add more check scripts.

**Comment by ohal** [comment]
> Port 2181 is open across the cluster. 
so, approach is to use install/keep in tenant already configured host/node.
done with zk tests (smoketest and latency), implemented and integrated as after deployment testing steps.

**Comment by cmgc** [comment]
- [X]  test cluster after deploy (maybe use https://github.com/phunt/zk-smoketest)  - added as additional check in jenkins in afterdeploy step.
- [ ]  configure backup of zk transactions from zookeeper-data-volume container - in progress now, 2-3 days to complete
- [X]  log rotation - already done [here.](https://github.com/CiscoCloud/microservices-infrastructure/blob/master/roles/logrotate/files/docker) 
- [X] metrics - added [#291](https://github.com/CiscoCloud/microservices-infrastructure/pull/291)
- [ ] consul agent monitoring (including latency tests) - in progress now, 1 day to complete

**Comment by sony2** [comment]
[WARN] agent: Check 'service:2181:zkid-1' is now warning

I receive this warning in all controllers.

**Comment by corebug** [comment]
Metrics are gathered by collectd (https://github.com/CiscoCloud/microservices-infrastructure/pull/417) Zookeeper plugin.

**Comment by stevendborrelli** [comment]
Marking closed for the 0.3 release. We'll add more production features in the future (and look at exhibitor).
