### ISSUE TITLE
Implement consul 0.5.1 ACL upsert 

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#266]
This should clean out a lot of our ACL code. 0.5.1 is scheduled for release the week of 5/12/2015.

https://github.com/hashicorp/consul/pull/909

- [x] upgrade packages to consul 0.5.1
- [x] upgrade cluster to consul 0.5.1
- [x] Replace our ACL creation and detection code with UUID generation in security-setup.

**Comment by ChrisAubuchon** [comment]
PR https://github.com/CiscoCloud/microservices-infrastructure/pull/270

**Comment by stevendborrelli** [comment]
#270 has been merged, closing
