### ISSUE TITLE
Using private docker repository for app

### ISSUE THREAD

**Issue by ramukima** [CiscoCloud/microservices-infrastructure#271]
An example in the docs on how to use 'uris' in marathon application deploy configuration file would be helpful.

**Comment by kenjones-cisco** [comment]
@ramukima The title seems to indicate how to deploy a containerized app from a private docker repository. If that is the intent, when defining your json payload to submit to the marathon REST API, the image name would look like the following:

`registry.example.com/sample_ns/sample_repo:tag`

That would result in pulling the image from the private registry located at registry.example.com. 

Your comment references 'uris'. Are you referring to configuration files that the container requires?
If that is the case, I found the following docs on marathon to be very helpful:
https://mesosphere.github.io/marathon/docs/application-basics.html
https://mesosphere.github.io/marathon/docs/native-docker.html

I believe there is another issue currently open about a more complete example application and documentation related to it. But hopefully this will help in the interim.
