### ISSUE TITLE
Explicit versioning of MI developed packages and containers

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#276]
I am a strong believer that you must version control *all* production artifacts. We Need to iterate towards this.

To get there let's divide our artifacts in to 3 categories:

* CentOS repo packages: Here Red Hat Enterprise Linux provides a stable API so in practice pulling the latest is very unlikely to cause breakage. The public (CentOS) Yum repos contain all the versions of the packages ever released.

* EPEL/Mesosphere repo packages: This includes Collectd, Mesos and Marathon. These packages provide "very good" API stability but public Yum repos contain *only* the latest version. Versioning these packages requires us to create a new Yum repo mirror.

* MI developed packages + repos: This includes Consul, Consul Template, Vault, Logstash, ZooKeeper, Mesos-Consul, Marathon-Consul, etc. These packages (a mix of RPMs and Docker containers) or the software itself provide "fair" API stability. Our repos maintain all version of the packages making version control straight forward.

As a first step, we will version control the RPMs and Docker containers developed by the MI team.

**Comment by stevendborrelli** [comment]
Here is a list of containers that need to be migrated to CiscoCloud: 

Role         Docker images used in the role

consul       asteris/nginx-consul

haproxy      asteris/haproxy-consul


mesos        asteris/nginx-consul

marathon     asteris/nginx-consul
                    drifting/mesos-consul
                    brianhicks/marathon-consul

**Comment by ChrisAubuchon** [comment]
```
mesos: asteris/nginx-consul
marathon asteris/nginx-consul 
consul asteris/nginx-consul
```
were converted with commit https://github.com/CiscoCloud/microservices-infrastructure/commit/97f19ef4419aa80cca95ac24bc9b2bef4e1790df

**Comment by stevendborrelli** [comment]
Thanks for the update. I think we can eliminate the other two containers pretty easily.

**Comment by BrianHicks** [comment]
marathon-consul is migrated as well. What do we have remaining?

**Comment by stevendborrelli** [comment]
Almost there:

logstash is not using a ciscocloud container & is using `latest`:

```
logstash/defaults/main.yml:logstash_image: keithchambers/logstash
logstash/defaults/main.yml:logstash_image_tag: latest
```

two containers are still using `latest` instead of an explicit version:

```
marathon/defaults/main.yml:mesos_consul_image_tag: latest
marathon/defaults/main.yml:marathon_consul_image_tag: latest
```

**Comment by BrianHicks** [comment]
marathon-consul is updated to 0.1

**Comment by stevendborrelli** [comment]
Thanks everyone! Closing this issue.
