### ISSUE TITLE
Vendor or Include all external dependencies

### ISSUE THREAD

**Issue by bketelsen** [CiscoCloud/microservices-infrastructure#277]
For example several of the roles include dockerized versions of tools used in this repo.  They pull docker containers from unknown sources and end-users have no idea what is being used.

All external dockerfiles & projects should either be explicitly listed, or vendored/merged into this repository.

**Comment by stevendborrelli** [comment]
This is a good point, and I agree:

Docker images should come from ciscocloud/<image>, with a versioned tag (not latest).
RPM/Deb artifacts should come from ciscocloud bintray

Were there any other artifacts you are thinking about?

**Comment by bketelsen** [comment]
The specific bits that caused me to think of this were docker images and the Consul RPM.  There may be others.   RPM/Deb artifacts should be listed with pointers to whatever tools were used to create them.  Introducing binaries that are untraceable is verboten in many environments.

Keep up the great work - I'm really learning a lot from this project!

**Comment by keithchambers** [comment]
Bro ... are you reading my mind ...? :+1: ;-)

https://github.com/CiscoCloud/microservices-infrastructure/issues/276

**Comment by bketelsen** [comment]
apparently so!  Feel free to close as a dup.

**Comment by stevendborrelli** [comment]
Marking as a dup.
