### ISSUE TITLE
Failure talking to yum: failure: repodata/repomd.xml from base: [Errno 256] No more mirrors to try.

### ISSUE THREAD

**Issue by nmarasoiu** [CiscoCloud/microservices-infrastructure#279]
Hi,

http://repo/centos/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: repo

==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => /home/nicu/tools/microservices-infrastructure
==> default: Running provisioner: ansible...
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --private-key=/home/nicu/tools/microservices-infrastructure/.vagrant/machines/default/virtualbox/private_key --user=vagrant --connection=ssh --limit='default' --inventory-file=/home/nicu/tools/microservices-infrastructure/.vagrant/provisioners/ansible/inventory --extra-vars={"consul_acl_master_token":"6d765095-7cca-46f3-a47e-f0f789911bf6","consul_default_acl_policy":"allow","consul_gossip_key":"zIvQhRIQ2N7fUljEk+3oDw==","marathon_http_credentials":"admin:admin","marathon_principal":"marathon","marathon_secret":"jRF1davsI/h9HnCjB2MC7yf/eg97OG0AL/NfNh5ji2aY","mesos_credentials":[{"principal":"marathon","secret":"jRF1davsI/h9HnCjB2MC7yf/eg97OG0AL/NfNh5ji2aY"}],"mesos_follower_principal":"follower","mesos_follower_secret":"Ac6BGJRJyohFSVBz35ewJBCt29d/9APhkYZhH/JCYt6l","nginx_admin_password":"admin","security_enabled":true,"zk_consul_ssl":"true","zk_consul_ssl_verify":"false","zk_marathon_user":"marathon","zk_marathon_user_secret":"38oc1HL7IPaYhOFk","zk_marathon_user_secret_digest":"YMKomZY5/Fq91dZt9UD9rov6cDE=","zk_mesos_user":"mesos","zk_mesos_user_secret":"TrtEmympd5Uc2apf","zk_mesos_user_secret_digest":"3KXBhDZ0nQFsKCjQnlXOItGdKF4=","zk_super_user":"super","zk_super_user_secret":"eLkJBbOEyKNwouGBicxn4SMv5ETT+SvD7OgjZ8c5a2Hm","consul_servers_group":"consul_servers","consul_dc":"vagrant","consul_acl_datacenter":"vagrant","consul_bootstrap_expect":1,"mesos_cluster":"vagrant","mesos_mode":"mixed"} vagrant.yml

PLAY [all] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [default]

TASK: [common | set timezone to etc/utc] ************************************** 
changed: [default]

TASK: [common | configure hosts file] ***************************************** 
changed: [default] => (item=default)

TASK: [common | install httpd-tools] ****************************************** 
failed: [default] => {"failed": true}
msg: Failure talking to yum: failure: repodata/repomd.xml from base: [Errno 256] No more mirrors to try.
http://repo/centos/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: repo; Unknown error"

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
common | install httpd-tools ------------------------------------------- 43.52s
common | set timezone to etc/utc ---------------------------------------- 0.32s
common | configure hosts file ------------------------------------------- 0.30s
           to retry, use: --limit @/home/nicu/vagrant.retry

default                    : ok=3    changed=2    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by nmarasoiu** [comment]
I am running Ubuntu 14.04

**Comment by nmarasoiu** [comment]
I tried also a few rpm/yum based distros in docker, but the longest i got was to vagrant run, but virtualbox not properly installed, the host has 3.19 kernel, but the fedora image has kernel-devel-3.19, maybe this causes an issue, but it complains libvrt not installed (even though it is) and restarting vbox complains unable to unload vboxpci, even though the module is present in the host and guest (i am after all running vbox ok on host)

**Comment by nmarasoiu** [comment]
I fixed it manually, but it needs a more automatic one presumably.
I edited the yum conf.

**Comment by keithchambers** [comment]
Can you share the manual edit you made to the yum config?

FWIW we are very away of the reliability challenges associated with provisioning 10s of JeOS VMs and then installing / upgrading 100s of RPMs and Docker images. We are moving to immutable images where everything is pre-baked. We're working closely to HashiCorp to develop support for on-the-fly importing of OpenStack and GCE images in Terraform to users won't need to build images themselves. And starting yesterday the Vagrantfile in master points to CiscoCloud/microservices-infrastructure -- a VM will all the RPMs and Docker images preinstalled. Probably doesn't solve your problem today but I wanted to share that we're working very hard to make deploys quicker and more reliable across every major public cloud.

**Comment by nmarasoiu** [comment]
That sounds amazing, I will read that a few times more:) I am familiar with the most of the technology names. We are quite happy with Consul and probably all the HashiCorp stack is just as great.

The change to /etc/yum.repos.d/CentOS-Base.repo was to apply the advice from its header, namely the part: "If the mirrorlist= does not work for you, as a fall back you can try the 
# remarked out baseurl= line instead." 

Indeed, commenting out #baseurl lines and commenting mirrorlist= ones did the trick.
I must say that we did get an IP for the mirror.centos.org, but I found on the net also people stating that the IP was not right and did not download the repomd descriptor(s) with the repos.

I had the virtual "cluster" running today well, with hello-world.
Now I am porting our spring boot app to that.
Since we use consul tags (which are not part of its DNS I think), and as well we publish to consul many health indicators made available by spring actuator using HTTP API, and we have a discovery using HTTP API of Consul to filter by all these statuses,
I will try to desecure consul REST API endpoint, i.e. reachable from docker tasks via http://consul.service.consul:8500/v1/... (at least /v1; /ui can remain https/secure if easy).
From a security perspective I think that DNS and HTTP API offer pretty much the same things (it is true that DNS is read only, but we just want to have something running, for production a security review would kick in if we ever want to go live with the stack).
Do you have an advice on how to do this ?

**Comment by stevendborrelli** [comment]
I've seen this problem with another user. Can you make sure your nodes have access to the internet?

**Comment by nmarasoiu** [comment]
Yes I did have access to the internet. Otherwise, no matter changes to config, it would not have eventually wored (I mentioned a change in the yum.repos.conf and then it worked)

**Comment by nmarasoiu** [comment]
This did reproduce consistently with Vagrant until 1 week ago.
Since then I succesfullly deployed on Amazon without the hack documented here.
The bug may still be up
