### ISSUE TITLE
zookeeper container java eats up all host memory

### ISSUE THREAD

**Issue by tymofii-polekhin** [CiscoCloud/microservices-infrastructure#281]
Load average: 3.29 3.16 3.59 4/634 233
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
   66     1 root     S    2410m  31%   0   0% /usr/lib/jvm/default-jvm/bin/java

i have no access to ciscocloud/zookeeper repo so i cant take a look an the docker image

suggestions i found:

To add JVM parameters to zookeeper, create file named java.env under conf folder in each of zookeeper with below content.

export JVMFLAGS="-Xms512m -Xmx512m"

**Comment by keithchambers** [comment]
@tymofii-polekhin the container source (currently) is here: https://github.com/asteris-llc/docker-zookeeper

@stevendborrelli can you fork your asteris-llc repo in to CiscoCloud and update the Docker Hub build to pull from there?

**Comment by stevendborrelli** [comment]
I've forked it to https://github.com/CiscoCloud/docker-zookeeper, and we'll update the docker hub shortly.

**Comment by tymofii-polekhin** [comment]
I'll try to fix this issue with java memory in this repo https://github.com/CiscoCloud/docker-zookeeper

**Comment by tymofii-polekhin** [comment]
@stevendborrelli please, take a look https://github.com/asteris-llc/docker-zookeeper/pull/4

**Comment by ChrisAubuchon** [comment]
Docker hub has been updated to use https://github.com/CiscoCloud/docker-zookeeper

**Comment by tymofii-polekhin** [comment]
fix for java memory. https://github.com/CiscoCloud/docker-zookeeper/pull/1

**Comment by stevendborrelli** [comment]
Closing this, as we have moved away from zookeeper in docker.
