### ISSUE TITLE
 security-setup: add 'nginx_admin_password_encrypted' value option

### ISSUE THREAD

**Issue by ohal** [CiscoCloud/microservices-infrastructure#288]
While deploying cluster security.yml does not have value 'nginx_admin_password_encrypted' and security-setup does not define one.
After order of deploying was changed here https://github.com/CiscoCloud/microservices-infrastructure/commit/08098b571e06cc90860e77beacc7f595676d3b35 some dependencies cause an error:
TASK: [consul | install nginx admin password] ********************************* 
fatal: [******] => One or more undefined variables: 'nginx_admin_password_encrypted' is undefined
FATAL: all hosts have already failed -- aborting
Reverting mentioned changes fix this issue.

**Comment by keithchambers** [comment]
This was my bad. Do a got pull on master are try again. Should be good now.

**Comment by ohal** [comment]
verified, looks well
