### ISSUE TITLE
Failed consul restart in Vagrant

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#295]
The docker role is calling consul restart (it should be consul reload) after loading the docker.json configuration file. 

```
NOTIFIED: [consul | restart consul] ******************************************* 
failed: [default] => {"cmd": "/usr/local/bin/consul-rolling-restart.sh", "failed": true, "rc": 2}
msg: [Errno 2] No such file or directory

FATAL: all hosts have already failed -- aborting
```

**Comment by loshkovskyi** [comment]
Related to this PR #297

**Comment by loshkovskyi** [comment]
The PR has been merged, I think we can close this issue. I have tested deployment in Vagrant and it looks fine.

**Comment by stevendborrelli** [comment]
@loshkovskyi thanks! closing the issue
