### ISSUE TITLE
Ensure that consul clients are configured correctly

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#30]
The current consul role is trying to configure all consul hosts as servers. We need to make sure that clients are correctly configured. 

changes for agents:
- [x] remove -server from clients
- [x] no bootstrap-expect
- [x] remove data volume
- [x] clean up bootstrap flags. Only one consul server should be in bootstrap mode

**Comment by ChrisAubuchon** [comment]
According to the docs, -bootstrap-expect can be run on multiple hosts. It is the legacy -bootstrap option (which we do not use) that can only be run on one server.
