### ISSUE TITLE
[master] : marathon | start jobs: Failed connect to localhost:18080; 

### ISSUE THREAD

**Issue by nmarasoiu** [CiscoCloud/microservices-infrastructure#303]
TASK: [marathon | start jobs] ************************************************* 
failed: [default] => (item=mesos-consul) => {"changed": false, "cmd": ["curl", "-X", "PUT", "-d@/etc/marathon/mesos-consul.json", "-H", "Content-Type: application/json", "http://localhost:18080/v2/apps/mesos-consul"], "delta": "0:00:00.159099", "end": "2015-05-19 14:41:52.952633", "item": "mesos-consul", "rc": 7, "start": "2015-05-19 14:41:52.793534", "warnings": ["Consider using get_url module rather than running curl"]}
stderr:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to localhost:18080; Connection refused
failed: [default] => (item=marathon-consul) => {"changed": false, "cmd": ["curl", "-X", "PUT", "-d@/etc/marathon/marathon-consul.json", "-H", "Content-Type: application/json", "http://localhost:18080/v2/apps/marathon-consul"], "delta": "0:00:00.156887", "end": "2015-05-19 14:41:53.329582", "item": "marathon-consul", "rc": 7, "start": "2015-05-19 14:41:53.172695", "warnings": ["Consider using get_url module rather than running curl"]}
stderr:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to localhost:18080; Connection refused

FATAL: all hosts have already failed -- aborting

**Comment by nmarasoiu** [comment]
this is the only blocking issue we have on master.
on 0.2.0 we have the zookeeper ConnectionLoss on /mesos on restart

**Comment by ChrisAubuchon** [comment]
This is a race condition in the ansible role. Trying to start a marathon job before ensuring that the marathon process is ready. Working on a fix.

**Comment by ChrisAubuchon** [comment]
PR https://github.com/CiscoCloud/microservices-infrastructure/pull/305
