### ISSUE TITLE
upgradepackages.yml throws exception

### ISSUE THREAD

**Issue by saswatp** [CiscoCloud/microservices-infrastructure#308]
I am getting the following error while running 

ansible-playbook site.yml --extra-vars=@security.yml -vvvv

Error seems to  be coming from the execution of upgradepackages.yml from provision-openstack.yml 

Has anyone encountered this error before ?

Thanks,
Saswat

TASK: [refresh yum cache] ***************************************************** 
<['10.202.57.32']> ESTABLISH CONNECTION FOR USER: centos
<['10.202.57.4']> ESTABLISH CONNECTION FOR USER: centos
<['10.202.57.32']> REMOTE_MODULE command yum makecache
<['10.202.57.4']> REMOTE_MODULE command yum makecache
fatal: [host-01] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 785, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 1032, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/action_plugins/normal.py", line 57, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args, inject=inject, complex_args=complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 470, in _execute_module
    tmp = self._make_tmp_path(conn)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 1288, in _make_tmp_path
    result = self._low_level_exec_command(conn, cmd, None, sudoable=False)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 1169, in _low_level_exec_command
    in_data=in_data)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/connection_plugins/ssh.py", line 295, in exec_command
    vvv("EXEC %s" % ' '.join(ssh_cmd), host=self.host)
TypeError: sequence item 22: expected string, list found

**Comment by ohal** [comment]
see /etc/hosts
probably, it has been wrongly updated/merged so ansible/ssh can not resolve host names.
I saw such an issue, but it was fixed last week

**Comment by ohal** [comment]
this is probably caused by ansible 1.9.1
try the next solution:

1 uninstall all versions of ansible:
pip uninstall ansible
yum erase ansible

2 download and install ansible 1.8.4 using yum, from downloaded rpm
here the link ftp://ftp.sunet.se/pub/Linux/distributions/fedora/epel/7/ppc64/a/ansible-1.8.4-1.el7.noarch.rpm

3 install ansible 1.9.0.1 using pip

>    pip install ansible==1.9.0.1

4 check what you have

>    rpm -qa | grep ansible - should be 1.8.4
>    pip list | grep ansible - should be 1.9.0.1

do not upgrade ansible

try deploying cluster

**Comment by saswatp** [comment]
Kind of found the issue but not sure how to fix it  :

fatal: [host-04] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py",
line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py",
line 785, in _executor_internal
    return self._executor_internal_inner(host, self.module_name,
self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py",
line 1032, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject,
complex_args)
  File
"/usr/local/lib/python2.7/dist-packages/ansible/runner/action_plugins/normal.py",
line 57, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args,
inject=inject, complex_args=complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py",
line 470, in _execute_module
    tmp = self._make_tmp_path(conn)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py",
line 1288, in _make_tmp_path
    result = self._low_level_exec_command(conn, cmd, None, sudoable=False)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py",
line 1169, in _low_level_exec_command
    in_data=in_data)
  File
"/usr/local/lib/python2.7/dist-packages/ansible/runner/connection_plugins/ssh.py",
line 296, in exec_command
    vvv("EXEC %s" % ' '.join(ssh_cmd), host=self.host)
TypeError: sequence item 22: expected string, list found

<['10.202.57.40']> ESTABLISH CONNECTION FOR USER: centos
['ssh', '-C', '-tt', '-v', '-o', 'ControlMaster=auto', '-o',
'ControlPersist=60s', '-o',
'ControlPath="/home/admin/.ansible/cp/ansible-ssh-%h-%p-%r"', '-o',
'StrictHostKeyChecking=no', '-o', 'KbdInteractiveAuthentication=no', '-o',
'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey',
'-o', 'PasswordAuthentication=no', '-o', 'User=centos', '-o',
'ConnectTimeout=10', *['10.202.57.35']*, "/bin/sh -c 'mkdir -p
$HOME/.ansible/tmp/ansible-tmp-1432066269.0-255341724299786 && chmod a+rx
$HOME/.ansible/tmp/ansible-tmp-1432066269.0-255341724299786 && echo
$HOME/.ansible/tmp/ansible-tmp-1432066269.0-255341724299786'"]

In ansible ssh.py  , there is a line that does the following :

vvv("EXEC %s" % ' '.join(ssh_cmd), host=self.host)

ssh_cmd is a list and all elements in the list should be string. I added a
print for ssh_cmd and see that host IP is a list *['10.202.57.35']* and not
a
string as it should have been .

Any idea how it becomes a list and not a string .

I manually put the entries in /etc/hosts after host provisioning is done.

Thanks,
Saswat

**Comment by ohal** [comment]
reinstalling the ansible is the fix, you have the solution above

**Comment by saswatp** [comment]
Thanks Oleh .

I have a ubuntu dev box so can't directly use the fedora epel rpm for
ansible.

BTW, If I install ansible via pip , is it not good enough ?
Do i have to also install via apt-get ?

thanks,
Saswat

**Comment by saswatp** [comment]
Removing and downgrading ansible via pip seems to have fixed the problem.

Thanks,
Saswat

**Comment by ohal** [comment]
it works for me on centos
myabe the next solution can help
1 try  to check which version you have installed using apt-get
> dpkg --list | grep ansible
uninstall all of them
2 uninstall ansible using pip
3 install using pip
> pip install ansible==1.8.4
4 upgrade using pip
> pip install -U ansible==1.9.0.1

**Comment by saswatp** [comment]
Thanks Oleh . That problem is resolved now .

Here is the error message.

I am running into another problem during software installation :

TASK: [common | install httpd-tools]
******************************************
failed: [host-02] => {"failed": true}
msg: Error from repoquery: ['/usr/bin/repoquery', '--show-duplicates',
'--plugins', '--quiet', '-q', '--disablerepo', '', '--enablerepo', '',
'--qf', '%{name}-%{version}-%{release}.%{arch}', 'httpd-tools']: Repository
base is listed more than once in the configuration
Repository updates is listed more than once in the configuration
Repository extras is listed more than once in the configuration
Repository centosplus is listed more than once in the configuration
Repository fasttrack is listed more than once in the configuration
Cannot find a valid baseurl for repo: base/7/x86_64
Repository base is listed more than once in the configuration
Repository updates is listed more than once in the configuration
Repository extras is listed more than once in the configuration
Repository centosplus is listed more than once in the configuration
Repository fasttrack is listed more than once in the configuration
Could not match packages: Cannot find a valid baseurl for repo:
base/7/x86_64

 I am using centos-7_x86_64-2015-01-27-v6 in CCS .


Thanks,
Saswat
