### ISSUE TITLE
The connection was reset (mesos, marathon UIs)

### ISSUE THREAD

**Issue by nmarasoiu** [CiscoCloud/microservices-infrastructure#309]
Hi,

After Merge pull request #305 from CiscoCloud/fix/marathon-race, I keep getting Connection reset from 8080 and 5050, over http

**Comment by Y4Rv1K** [comment]
@nmarasoiu Web UI for marathon and mesos not available too?

**Comment by nmarasoiu** [comment]
Right, both give RST, both from the vagrant host and the vagrant guest

**Comment by nmarasoiu** [comment]
I must say I also got that with earlier commits, when rolling back with reset --hard..

**Comment by nmarasoiu** [comment]
Are you aware of any version (commit; hash; tag) which could be more stable than the current master?
I tried 0.1.0, 0.2.0 and master, and all are failing to me, with the bugs I have put this week here, some were fixed, but currently all 3 are blocked right now for me.

**Comment by Y4Rv1K** [comment]
Can you ssh to host and validate that something running at port 8080 and 5050 `netstat -nlupt | grep 8080` ?

And that is tcp or tcp6? What result of  `nc -v <master_host>  8080` ?

**Comment by nmarasoiu** [comment]
tcp6       0      0 :::8080                 :::*                    LISTEN      10536/docker-proxy  
tcp6       0      0 :::5050                 :::*                    LISTEN      9189/docker-proxy   
nc -v localhost 8080
Ncat: Version 6.40 ( http://nmap.org/ncat )
Ncat: Connected to ::1:8080.
Yes, option to disable all security (or just consul one)

**Comment by stevendborrelli** [comment]
@nmarasoiu would you be open to doing a screen share so that I can walk through one of your deployments? I'd like to get a better feel of what is going on.

**Comment by Y4Rv1K** [comment]
Lets change it a little bit. 
Can you try instead `./security-setup --enable=false`:

1. `./security-setup`
2. `./security-setup --mesos-iptables=false --mesos-framework-auth=false` ?

**Comment by nmarasoiu** [comment]
Yes, right now I am starting a fresh instance (vagrant destry + up) with option 1 above i.e. no option given to the security command

**Comment by nmarasoiu** [comment]
I give to the

**Comment by nmarasoiu** [comment]
I am available for a screen share, what tool do you suggest?

**Comment by nmarasoiu** [comment]
NOTIFIED: [zookeeper | wait for zookeeper to listen] ************************** 
failed: [default] => {"changed": true, "cmd": ["zookeeper-wait-for-listen.sh"], "delta": "0:00:59.980486", "end": "2015-05-20 11:46:35.193057", "rc": 1, "start": "2015-05-20 11:45:35.212571", "warnings": []}

FATAL: all hosts have already failed -- aborting

TASK: [mesos | add mesosphere repository] ************************************* 
FATAL: no hosts matched or all hosts have already failed -- aborting

**Comment by nmarasoiu** [comment]
And running ansible again, it's back to: (an existing open issue made by me):
failed: [default] => {"changed": true, "cmd": ["docker", "run", "--rm", "-e", "ZK_AUTH=super:+Nt5e/wmF5gt4tN04SB/syZnqam10nNjoTHL1m+d4bt5", "-e", "ZNODE=/mesos", "-e", "ZNODE_ACL=world:anyone:r,digest:mesos:J+OaGBhZLLsFv0iG/Dpj4HWXTyI=:cdraw", "-e", "ZK_SERVER=zookeeper.service.consul:2181", "--entrypoint", "/usr/local/bin/setacl.sh", "ciscocloud/zookeeper:0.2"], "delta": "0:00:02.505259", "end": "2015-05-20 12:00:03.651818", "rc": 1, "start": "2015-05-20 12:00:01.146559", "warnings": []}
stderr: Exception in thread "main" org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /mesos
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
