### ISSUE TITLE
Move provisioner to terraform

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#31]
Use terraform for provisioning VMs instead of ansible.
Keep track of https://github.com/hashicorp/terraform/pull/924

**Comment by BrianHicks** [comment]
@keithchambers did we want to revisit extending TF for this capability? We probably should open a new ticket for that. Otherwise, I'll close this ticket when we release 0.3.

**Comment by stevendborrelli** [comment]
Marking as closed.
