### ISSUE TITLE
[master] [consul | wait for leader]: Timeout

### ISSUE THREAD

**Issue by nmarasoiu** [CiscoCloud/microservices-infrastructure#310]
failed: [default] => {"elapsed": 300, "failed": true}
msg: Timeout when waiting for 127.0.0.1:8301

FATAL: all hosts have already failed -- aborting

**Comment by stevendborrelli** [comment]
@nmarasoiu if you are open to it, I'd like to do a screen share where we can walk through a cluster provisioning so that I can help address these issues.
