### ISSUE TITLE
Can't start marathon/mesos UI if ./security-setup --enable=false 

### ISSUE THREAD

**Issue by Y4Rv1K** [CiscoCloud/microservices-infrastructure#312]
We faced with issue that if we build cluster with `./security-setup --enable=false ` on top of OpenStack it finish successfully but:

1. Marathon UI not available but service is running on the host
2. Mesos UI not available but service is running on the host
3. Consul UI works fine

As result I'm not able to deploy app to cluster. In my case my Kafka scheduler ( branch `feature\frameworks`) not able to deploy or start.

**Comment by Y4Rv1K** [comment]
Looks like that my misunderstanding of options: 
 
`./security-setup --mesos-iptables=false --mesos-framework-auth=false` works fine for me 
 `./security-setup --enable=false` dose’t work for me even at master

**Comment by ChrisAubuchon** [comment]
It is an issue with the nginx container. It is trying to connect to consul via SSL with Consul disabled. 

Try the fix/nginx-ssl branch.

**Comment by ChrisAubuchon** [comment]
PR https://github.com/CiscoCloud/microservices-infrastructure/pull/317 is a better option for resolving

**Comment by kenjones-cisco** [comment]
@ChrisAubuchon will that PR also resolve an issue I'm currently seeing where I can't access any of the UIs any longer and get 403 Forbidden from nginx for any of the 3 UIs (consul, mesos, marathon). I assumed it was due to the fact my security.yml was out of date. So I reran the security setup, and then the playbook ran successfully but the UIs are no longer accessible.

**Comment by ChrisAubuchon** [comment]
@kenjones-cisco Separate issue. That is due to improper versioning of the nginx-consul container. That should be resolved now.

**Comment by stevendborrelli** [comment]
I've merged #317. @Y4Rv1K can we test and close this issue?

**Comment by Y4Rv1K** [comment]
@stevendborrelli sure.

**Comment by Y4Rv1K** [comment]
Tested and verified. Looks ok. feature/frameworks will be rebased to latest master. 
Thank you
