### ISSUE TITLE
Kubernetes-Mesos Framework

### ISSUE THREAD

**Issue by altvnk** [CiscoCloud/microservices-infrastructure#315]
We are currently working to add [kubernetes-mesos](https://github.com/mesosphere/kubernetes-mesos) to our Microservices platform. Kubernetes is going to be run as a Mesos framework with etcd (since it's the only available option at least for now). The research will cover how to build networking with Kubernetes, as there are multiple solutions available such as `Weave`, `Flannel`, `OVS` and others.

**Comment by loshkovskyi** [comment]
We are affected by this bug right now: [Bug 1213258](https://bugzilla.redhat.com/show_bug.cgi?id=1213258)
For example, I can't use [coreos/etcd](https://registry.hub.docker.com/u/coreos/etcd/) due to the bug.

**Comment by altvnk** [comment]
Because of specific networking model that used by Kubernetes (subnet per host) we need to build overlay network between hosts. 
CoreOS team introduced [Flannel](https://github.com/coreos/flannel) which is designed to emulate Kubernetes networking model on cloud providers different than GCE.
I think we can try to adopt flannel to run in environment that MI provides.
Also flannel assumes that docker networking will be reconfigured to use flannel, let's see how this affects other services e.g. Marathon and infrastructure services running in docker.

**Comment by altvnk** [comment]
I have spent some time trying to package kubernetes-mesos in Alpine Linux base image and run into issues around musl libc. The point is i cannot place binaries of kubernetes-mesos in container because i build them with gnu libc, alpine uses musl libc. Building kubernetes-mesos with alpine golang port ends with errors... I suggest that [busybox](https://registry.hub.docker.com/_/busybox/) is good alternative because it uses gnu libc and also has small footprint. So i continue to work on container but this time i use busybox as base image.

Also to run all of the kubernetes-mesos services (apiserver, controller-manager, scheduler) in single container we need to use some process supervisor. I suggest that [Skarnet S6](http://skarnet.org/software/s6/) process supervisor is good candidate. I found complete overlay that provides custom init for docker containers and runs as PID 1 - [s6-overlay](https://github.com/just-containers/s6-overlay). This overlay can be easily integrated into busybox image.

**Comment by PeterLamar** [comment]
I have thought about this and I like the idea of instead adding the deployment of stand alone k8's until the mesos-k8's solution matures. 

https://github.com/altvnk/kubernetes-ansible

Advantages:
As @michaeltchapman suggests we can re-use the terraform pieces, the inventory plugin and a couple of the base roles (docker)

Having an etcd cluster and access to the kubernetes ecosystem next to the Mesos big data ecosystem is advantageous. For example, side projects such as calico which depend on etcd can be readily experimented with.

I don't believe k8's and etcd take much cpu and memory if you don't actually use them

Thoughts?

**Comment by stevendborrelli** [comment]
I would like to try running etcd in marathon, using DNS SRV discovery on the nodes. 

We could probably add in K8s...we're going to need a networking solution. Maybe we can use Weave until Calico is ready?

**Comment by altvnk** [comment]
Hi, Steven! There is a bug in current docker that prevents running etcd in container, docker run fails, not sure that it fixed now in main repo, but in virt7-testing repo docker doesn't have such issue. Need to do some tests today.

**Comment by altvnk** [comment]
Well, actually Terraform code and inventory plugin was taken from MI. Regards to Steven's team )

**Comment by michaeltchapman** [comment]
@altvnk I did a quick test this week using the 1.6.2 binary and that was working OK for etcd. I went the lazy route and just overwrote the binary, but there's some packages here: http://cbs.centos.org/kojifiles/packages/docker/1.6.2/4.gitc3ca5bb.el7/x86_64/

**Comment by altvnk** [comment]
@michaeltchapman I was able to install docker 1.6.2 from repo you are suggest in a few simple steps in ansible roles, so we use this as temporary workaround until docker will be updated in main repo.
Here is the steps:
add yum repo
```
- name: bootstrap virt7-testing repo
  copy:
    src: virt7-testing.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644
  tags:
    - common
```
virt7-testing.repo contains following

```
[virt7-testing]
name=virt7-testing
baseurl=http://cbs.centos.org/repos/virt7-testing/x86_64/os/
gpgcheck=0
```
and finally install docker from that repo

```
- name: install docker
  sudo: yes
  yum:
    name: docker
    state: latest
    enablerepo: virt7-testing
  tags:
    - docker
```

**Comment by michaeltchapman** [comment]
@altvnk do you have a branch with the k8s framework working? I'm happy to test.

**Comment by altvnk** [comment]
@michaeltchapman I don't have a working framework but have original kubernetes working. I suppose you already seen it in my personal repo. I also have a working cluster with k8s, PM me and i give you creds so you can take some hands-on on it.
We can easily port it into MI, but first we need to decide how to run `etcd`, @stevendborrelli suggests to run it in Marathon. Is there some progress on it?

**Comment by michaeltchapman** [comment]
@altvnk yep your personal ansible-k8s repo is working fine for me.

I can work on etcd in marathon in a feature branch with the repo changes above merged in, then once a better docker package solution comes about via RedHat updating extras we can cherry pick all the non-repo bits across to master and forget the repo issues ever existed. I'm still learning though, so if this is blocking you then don't wait for me.

**Comment by michaeltchapman** [comment]
@altvnk 1.6.2 is in centos 7 extras now.

**Comment by siddharthist** [comment]
etcd is a part of PR #626
