### ISSUE TITLE
ansible bug impacts openstack environments

### ISSUE THREAD

**Issue by kenjones-cisco** [CiscoCloud/microservices-infrastructure#316]
After trying to use the playbook/reboot-hosts.yml to reboot my servers, I got the following error:

```
fatal: [cchub-dc1-01] => Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 785, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1032, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/action_plugins/normal.py", line 57, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args, inject=inject, complex_args=complex_args)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 470, in _execute_module
    tmp = self._make_tmp_path(conn)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1288, in _make_tmp_path
    result = self._low_level_exec_command(conn, cmd, None, sudoable=False)
  File "/usr/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1169, in _low_level_exec_command
    in_data=in_data)
  File "/usr/lib/python2.7/site-packages/ansible/runner/connection_plugins/ssh.py", line 295, in exec_command
    vvv("EXEC %s" % ' '.join(ssh_cmd), host=self.host)
TypeError: sequence item 20: expected string, list found
```

I went through making sure all modules are upgraded to the latest versions based on requirements.txt and then started debugging why a debug statement would cause a failure.

The `self.host` value which is set using the nova_compute core module to `host.private_ip`.

When a host is created the output from the module works like this:
```
    private = openstack_find_nova_addresses(getattr(server, 'addresses'), 'fixed', 'private')
    public = openstack_find_nova_addresses(getattr(server, 'addresses'), 'floating', 'public')

    module.exit_json(changed = True, id = info['id'], private_ip=''.join(private), public_ip=''.join(public), status = server.status, info = server._info)
```

But after the server has been created and the state is gathered the output from the module works like this:
```
        private = openstack_find_nova_addresses(getattr(server, 'addresses'), 'fixed', 'private')
        public = openstack_find_nova_addresses(getattr(server, 'addresses'), 'floating', 'public')
        module.exit_json(changed = ip_changed, id = server.id, public_ip = public, private_ip = private, info = server._info)
```

As a result the state returns private_ip as a list and not a string such that the debug statement is unable to handle a string join on a list that contains another list.

As such anything depending on openstack hosts that already exist will hit this problem as the issue is triggered within the connection_plugins/ssh.py.

The module nova_compute is being deprecated in ansible v2.0 in favor os a new one `os_server` which leverages shade instead of novaclient directly.

**Comment by stevendborrelli** [comment]
Thanks @kenjones-cisco for a fantastic bug report. Do you have any ideas of how we can address this in our project?

**Comment by kenjones-cisco** [comment]
Basically the reason `openstack/provision-hosts.yml` is included at the beginning of every playbook is to do dynamic inventory discovery, after the initial creation of the hosts. Or when someone needs to update those hosts. But the other 90% of the time you just need to discover the IP addresses of your inventory.

At which point either leverage an inventory plugin to acquire similar information, or statically update the inventory file to provide the IP address of each host.

For my project, I use an inventory plugin. Which is why the PR to include metadata was provided such that tagging a group on the hosts generates the ansible host groups for me.

My experience on the existing openstack inventory plugins.
I've looked at both the two existing inventory plugins for openstack, openstack.py and nova.py.
openstack.py uses shade which seems to be a nice library but talk about dependency nightmare requiring a large number of the clients as it tries to be the swiss-army knife of clients (probably while openstack-sdk is being built). 
nova.py is pretty simple but it makes all kinds of decisions for me like naming every variable from the host with "os_", converting to lower-case, etc.
So I created local plugin that is more like openstack.py but simpler like nova.py.

Dynamic is the way to go ultimately.

**Comment by saswatp** [comment]
I encountered this issue yesterday and had reported this issue.
I was suggested to downgrade ansible to 1.9.0.1 as a work around for this
and downgrading to 1.9.0.1 actually fixed the issue.

Thanks,
Saswat

**Comment by kenjones-cisco** [comment]
@saswatp Thanks for the information! That was very helpful.

**Comment by stevendborrelli** [comment]
Closing this issue due to pull #320 getting merged.
