### ISSUE TITLE
is it possible to run ansible/puppet on the local machine directly?

### ISSUE THREAD

**Issue by nmarasoiu** [CiscoCloud/microservices-infrastructure#319]
I am trying to ramp up cloud instances.
With the current cloud provider, I tried several recent distributions including centos7 and ubuntu 15 and even though installation of VirtualBox looked ok, I get 

The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

**Comment by stevendborrelli** [comment]
Can you provide a little more detail on what you are trying to do? If you paste in your Vagrantfile we can try to duplicate what you are doing.

**Comment by nmarasoiu** [comment]
Hello, yes, I would be happy to screen share with you, let's discuss time and tool to share, I will be here from now until 11:30 NewYork time.

I am just trying to start the stack as it is. The only modification is I give more resources to the vm, about half of the cpu and memory available, but I tried with less and more, and still same results (especially zookeeper timeout).

**Comment by nmarasoiu** [comment]
The first step is to start a single node (which I only succeeded once, on my laptop).
Then go 4 nodes, 3 of them will be zk ensemble, 3 consul servers, so will always be a client side node too (consul client agent).
Will be interesting if docker plays well with consul, because we had issues with Docker's UDP Proxy.
