### ISSUE TITLE
consul_dc_group undefined

### ISSUE THREAD

**Issue by kenjones-cisco** [CiscoCloud/microservices-infrastructure#356]
```
TASK: [dnsmasq | configure dnsmasq for consul] ********************************
fatal: [cchub-stage-01] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'consul_dc_group' is undefined", 'failed': True}
fatal: [cchub-stage-02] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'consul_dc_group' is undefined", 'failed': True}
fatal: [cchub-stage-01] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'consul_dc_group' is undefined", 'failed': True}
fatal: [cchub-stage-02] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'consul_dc_group' is undefined", 'failed': True}
fatal: [cchub-stage-03] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'consul_dc_group' is undefined", 'failed': True}
fatal: [cchub-stage-03] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'consul_dc_group' is undefined", 'failed': True}
fatal: [cchub-stage-06] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'consul_dc_group' is undefined", 'failed': True}
fatal: [cchub-stage-06] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'consul_dc_group' is undefined", 'failed': True}
fatal: [cchub-stage-05] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'consul_dc_group' is undefined", 'failed': True}
fatal: [cchub-stage-05] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'consul_dc_group' is undefined", 'failed': True}
fatal: [cchub-stage-04] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'consul_dc_group' is undefined", 'failed': True}
fatal: [cchub-stage-04] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'consul_dc_group' is undefined", 'failed': True}

FATAL: all hosts have already failed -- aborting
```

I believe the value is set, but it is being referenced as a simple variable instead of a complex variable.

```
consul_dc_group: dc={{ consul_dc }}
consul_servers_group: consul_servers
```

```
consul_retry_join: "{% for host in groups[consul_servers_group] | intersect(groups[consul_dc_group]) %}\"{{ hostvars[host].ansible_default_ipv4.address }}\"{% if not loop.last %}, {% endif %}{% endfor %}"
```

The `consul_servers_group` is a simple variable and when plugged into `groups[]`, it would work. But since `consul_dc_group` is a complex as currently defined. it should probably be used as `consul_dc_group[dc]` instead of `consul_dc_group`, or the `dc=` portion can be removed and then the rest of it should work based on how it is currently being used.

**Comment by BrianHicks** [comment]
That error means that the value is set, but you don't have a group named `dc=yourdcname`. It's a pretty misleading error message. One would think they would raise a `KeyError`, but I guess not. Does it work if you add that group?

**Comment by kenjones-cisco** [comment]
I do have a group named `dc1`

```
/mi # more inventory/1-datacenter
# all
[all]
cchub-stage-[01:06]

# datacenters
[dc1]
cchub-stage-[01:06]

# control
[vault_servers]
cchub-stage-[01:03]

[consul_servers]
cchub-stage-[01:03]

[zookeeper_servers]
cchub-stage-[01:03]

[mesos_leaders]
cchub-stage-[01:03]

[marathon_servers]
cchub-stage-[01:03]

# resource nodes
[consul_clients]
cchub-stage-[04:06]

[mesos_followers]
cchub-stage-[04:06]

[proxy_servers]
cchub-stage-[04:06]
```

**Comment by BrianHicks** [comment]
yes, but you either need a group named `dc=dc1` or to set `consul_dc_groups` in your group/host vars. This change was made to make the group names clearer. I recognize it's a hassle as it stands, but with our change to Terraform it separates a few concerns (EG naming the groups independently of the DC name.)

**Comment by kenjones-cisco** [comment]
So the existing inventory/ files are all incorrect?
What about the `group_vars/dc1` and `group_vars/dc1`? Are we supposed to name a file to be `group_vars/dc=dc1`?

Seems rather counter-intuitive, and w/o those changes it definitely is not backwards compatiable.

**Comment by BrianHicks** [comment]
Yes, they’re incorrect. The group_vars are being replaced by the 
`terraform.py` script in 0.3.

Yes, it’s backwards incompatible, but Terraform creates so much of a 
better experience that it’s worth making a breaking change. Going 
forward, clusters should be provisioned only through Vagrant or 
Terraform. Combined with the CLI the Trifork team is working on, this 
will be a much better user experience.

**Comment by BrianHicks** [comment]
@kenjones-cisco are you able to get it working for now, either under Terraform or by modifying the vars?

**Comment by kenjones-cisco** [comment]
If the group_vars are being replaced as it were, then that makes more sense. 

On the current master then `ansible-playbook site.yml` will fail? 

To use terraform, is that something ansible takes care of or is another executable separate from ansible needed to use terraform? 

So to transition, we don't use inventory/ but now use terraform/? 
Just trying to determine next steps, on what that will be.

**Comment by BrianHicks** [comment]
To provision, you'll now need to:

1. provision your stack through Terraform. The sample files in `terraform/` should help with this, then `terraform get && terraform apply` should do the trick to get your servers up and running.
2. fill in your ACL datacenter from the template provided by `terraform.yml.sample` in the root (I'm assuming you'll name this `terraform.yml`)
3. run Ansible with `ansible-playbook -i plugins/inventory/terraform.py -e @security.yml terraform.yml`

All this will be automated by Trifork's new CLI, so we were waiting on documenting this. Seems like you got bitten by the lack of documentation, though. I'm going to close for now, but would you mind treating the instructions above as a draft of said docs, and opening tickets against them? We'll add something into the docs about manual configuration just to cover all the bases and I'd love to know your experience as you get that configured.
