### ISSUE TITLE
./security-setup --enable=false cause SSL error at Marathon REST API

### ISSUE THREAD

**Issue by Y4Rv1K** [CiscoCloud/microservices-infrastructure#359]
If cluster was built wit ` ./security-setup --enable=false` I got issue with Marathon REST API:

           0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0curl: (35) SSL received a record that exceeded the maximum permissible length.

Command to reproduce: 

             http --verify=no -a admin:admin POST https://host-02:8080/v2/apps < kafka.json

Can be reproduced at branch `qa/features-master-integration`

In the same time if cluster built with option `security-setup --mesos-iptables=false --mesos-framework-auth=false` I haven't such problem.

**Comment by ChrisAubuchon** [comment]
`--enable=false` turns off SSL for Marathon. Authentication too. Can you try it using?
```
http://host-02:8080/v2/apps
```

**Comment by Y4Rv1K** [comment]
Good point. I see the problem. Thank you. I will check and let you know.

**Comment by stevendborrelli** [comment]
@Y4Rv1K can you test this on monday so we can either address the bug or close the issue?

**Comment by Y4Rv1K** [comment]
No needs. I'm closing.
