### ISSUE TITLE
deploy on existing computers

### ISSUE THREAD

**Issue by nmarasoiu** [CiscoCloud/microservices-infrastructure#362]
Hi,

I got my local vagrant running, just by retrying the same sequence after few days.

Now I want to test with rackspace machines.
I got ssh ping working: ansible all -i inventory/1-datacenter -m ping
I use /etc/hosts to spoof and map host-01 through host-05 to same ip in the cloud.

And I run security setup both locally and remote (where do I need to run?).
I run it with --consul false.

Now trying to execute:
```
nicu@nmarasoiu:~/tools/microservices-infrastructure$ ansible-playbook -i inventory/1-datacenter site.yml -e @./security.yml

PLAY [localhost] ************************************************************** 

TASK: [check for security] **************************************************** 
skipping: [localhost]

PLAY [localhost] ************************************************************** 

TASK: [verify openstack environment] ****************************************** 
skipping: [localhost] => (item=OS_USERNAME)
failed: [localhost] => (item=OS_PASSWORD) => {"failed": true, "item": "OS_PASSWORD"}
msg: openstack environment variable OS_PASSWORD is not set

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
verify openstack environment -------------------------------------------- 0.01s
check for security ------------------------------------------------------ 0.01s
           to retry, use: --limit @/home/nicu/site.retry

localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```

**Comment by nmarasoiu** [comment]
I do not necessarily want openstack, not do I understand its role at the moment.
My machines will be already defined (I provide them with docker-machine for now).

**Comment by nmarasoiu** [comment]
also want to mention that i prefer other authentication methods such as the key pair, not the password. maybe would be better to clarify context on the os_password above and alternatives if any

**Comment by nmarasoiu** [comment]
Setting a password, retry, now gives:
nicu@nmarasoiu:~/tools/microservices-infrastructure$ ansible-playbook -i inventory/1-datacenter site.yml -e @./security.yml

PLAY [localhost] ************************************************************** 

TASK: [check for security] **************************************************** 
skipping: [localhost]

PLAY [localhost] ************************************************************** 

TASK: [verify openstack environment] ****************************************** 
skipping: [localhost] => (item=OS_USERNAME)
skipping: [localhost] => (item=OS_PASSWORD)

PLAY [all] ******************************************************************** 

TASK: [add ssh key to openstack tenant] *************************************** 
failed: [host-01 -> 127.0.0.1] => {"failed": true}
msg: Unable to authorize user: Authentication requires 'auth_url', which should be specified in 'HTTPClient'
failed: [host-04 -> 127.0.0.1] => {"failed": true}
msg: Unable to authorize user: Authentication requires 'auth_url', which should be specified in 'HTTPClient'
failed: [host-03 -> 127.0.0.1] => {"failed": true}
msg: Unable to authorize user: Authentication requires 'auth_url', which should be specified in 'HTTPClient'
failed: [host-02 -> 127.0.0.1] => {"failed": true}
msg: Unable to authorize user: Authentication requires 'auth_url', which should be specified in 'HTTPClient'
failed: [host-05 -> 127.0.0.1] => {"failed": true}
msg: Unable to authorize user: Authentication requires 'auth_url', which should be specified in 'HTTPClient'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
add ssh key to openstack tenant ----------------------------------------- 0.52s
verify openstack environment -------------------------------------------- 0.01s
check for security ------------------------------------------------------ 0.01s
           to retry, use: --limit @/home/nicu/site.retry

host-01                    : ok=0    changed=0    unreachable=0    failed=1   
host-02                    : ok=0    changed=0    unreachable=0    failed=1   
host-03                    : ok=0    changed=0    unreachable=0    failed=1   
host-04                    : ok=0    changed=0    unreachable=0    failed=1   
host-05                    : ok=0    changed=0    unreachable=0    failed=1   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

Would you be kind to explain what is being attempted? Is openstack the only flow to deploy multiple nodes? How is localhost affected (it is my dev computer)?

**Comment by stevendborrelli** [comment]
Are you running off of master? We've just implemented terraform (terraform.io) provisioning to clusters, which allows us to deploy to Google Cloud, OpenStack, and AWS (coming this week). 

We've found a huge amount of incompatibilities between Ansible 1.9.X and the python-novaclient modules, which is causing many users to fail with errors. This is why we are shifting to terraform.

For the error you are getting, can you confirm that your `inventory/group_vars/dc1` file is populated with the correct values for your openstack environment?

**Comment by nmarasoiu** [comment]
Hi,

I am not sure if I have an openstack env. I just have a rackspace account, and have 1 running machine, which I wanted to provision with all roles (for now; after this works i will go 4 nodes).

I am in the process of studying how to use rackspace public cloud as an openstack provider, I am now anticipating it would offer a public api endpoint and a way to authenticate to it, and likely i will kill my machine to be automatically created from the specs i give ansible through site.yml and/or other configs (i need to determine those as well).

**Comment by nmarasoiu** [comment]
Is there a clear way to deploy to a number of existing IPs with ssh keys installed?
Can I find a documentation on this?
We must evaluate rackspace, but they offer openstack only in private cloud with $25K monthly fee.
Apparently they also offer some way to automate creating vms because docker-machine has a working rackspace driver (not the openstack driver) which worked for me. But that needs to be hooked to ciscocloud, which is not my target at the moment.
