### ISSUE TITLE
rackspace supported?

### ISSUE THREAD

**Issue by nmarasoiu** [CiscoCloud/microservices-infrastructure#376]
Hi,

Running terraform gives me 401, bad credentials.
I can login with nova client however.
Is there a specific configuration that I need to add / modify?
(I noticed rackspace uses a non standard authentication mechanism somewhat plugged into the standard openstack auth flow. Is this correct?)

**Comment by stevendborrelli** [comment]
I haven't tested rackspace, but for openstack, you need to copy the `terraform/openstack.sample` file to  the main directory and modify it for tenant_name, etc.

**Comment by nmarasoiu** [comment]
ok, i will check. I am afraid rackspace != openstack, because:
1. they have their custom authentication 
2. they have non-cloudstack api too (e.g. docker-machine uses a rackspace driver, but it has an openstack one too)
3. a lady from their sales told me they only support openstack integrations at their higher pay subscription

**Comment by nmarasoiu** [comment]
So yes, Rackspace does not support standard Openstack.
For that reason Terraform is introducing a Rackspace provider.
That is in work for a month but suspended at the moment.
It might already work and maybe Tuesday I will give it a try.
