### ISSUE TITLE
plugins/inventory/terraform.py (openstack region)

### ISSUE THREAD

**Issue by kenjones-cisco** [CiscoCloud/microservices-infrastructure#383]
I had to remove region from the terraform files from the openstack samples in order to get terraform to provision keypair and hosts without errors. But the plugin requires region even though openstack doesn't require it (atleast not the version of openstack I'm leveraging).

Maybe change the plugin to use a .get('region') instead of doing ['region']

**Comment by ChrisAubuchon** [comment]
Were you able to provision via Terraform without the region? It looks like the region is required by Terraform: https://github.com/hashicorp/terraform/blob/master/builtin/providers/openstack/resource_openstack_compute_instance_v2.go#L35-L39

**Comment by kenjones-cisco** [comment]
Yes, the provision works great if I remove region from the terraform templates. And I just downloaded and installed terraform this morning so it is the latest version.

If I include region, then I get errors.

**Comment by stevendborrelli** [comment]
@kenjones-cisco I've been able to use regions in two separate data centers. What values are you using?

**Comment by kenjones-cisco** [comment]
the one time I actually tried with region, I just typed in "stage" as region has not been part of any provisioning previously.

**Comment by stevendborrelli** [comment]
@kenjones-cisco can you try using something like us-texas-1 or eu-amsterdam-1?

**Comment by kenjones-cisco** [comment]
With region (including trying with us-texas-1), I get the following error:

```
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * 1 error(s) occurred:

* module.dc2-hosts: missing dependency: module.dc2-keypair.output.region
```

which I figure is related to the following:

```
module "dc2-hosts" {
        source = "./terraform/openstack/hosts"
        region = "${ module.dc2-keypair.region }"
```

Then after doing `get`, `plan`, and then `apply`, I get the following:

```
module.dc2-keypair.openstack_compute_keypair_v2.keypair: Creating...
  name:       "" => "cchub_key"
  public_key: "" => "<VALUE REDACTED>"
  region:     "" => "us-texas-1"
module.dc2-keypair.openstack_compute_keypair_v2.keypair: Error: 1 error(s) occurred:

* Error creating OpenStack compute client: No suitable endpoint could be found in the service catalog.
```

**Comment by kenjones-cisco** [comment]
If I remove region all together from each of the 3 files, then it works with no issues. From the terraform `get`, `plan`, and `apply` portion. 

As soon as I try:

```
ansible all -i plugins/inventory/terraform.py -m ping
```

The plugin throws a KeyError because there is no region to pull in.

**Comment by kenjones-cisco** [comment]
Just tried to use the name of the openstack instance as the region value, and it started working. So basically it is just a bad error message from terraform since the value must be specific. But interesting that it is not required either. Since apply will run successfully even if region is not provided or set as an environment variable.

**Comment by kenjones-cisco** [comment]
FYI, probably should make note in the documents regarding openstack, that the variables set as part of the opernrc.sh have to be removed in order to make use of the environment variables. Otherwise terraform complains the variables are not set.

**Comment by BrianHicks** [comment]
I think we've updated what was causing the problem, since we haven't seen this since you reported it. I'm just going to close the ticket. If it's still a problem for you, please reopen.

**Comment by kenjones-cisco** [comment]
Sounds good!
