### ISSUE TITLE
marathon | wait for marathon to listen fails on atleast 1 node every time

### ISSUE THREAD

**Issue by kenjones-cisco** [CiscoCloud/microservices-infrastructure#385]
Since before the merging of the terraform changes, the `wait for marathon` task will fail on atleast one of the nodes. It will only succeed on a single node or no nodes.

```
NOTIFIED: [zookeeper | wait for zookeeper to listen] **************************
changed: [cchub-control-01]
failed: [cchub-control-02] => {"changed": true, "cmd": ["zookeeper-wait-for-listen.sh"], "delta": "0:00:59.948252", "end": "2015-05-28 19:44:03.900092", "rc": 1, "start": "2015-05-28 19:43:03.951840", "warnings": []}
```

Seems to be a timeout issue, so not sure what the root cause is here.

**Comment by ChrisAubuchon** [comment]
Can you log in to the server and run `/usr/local/bin/zookeeper-wait-for-listen.sh` and check the return value?

**Comment by kenjones-cisco** [comment]
On the server after everything completes, I'm not getting an error when running the script.
But when I run the tasks through ansible, it will error out.

**Comment by ChrisAubuchon** [comment]
Can you run `systemctl restart zookeeper` on the node and see how long it takes? I'm wondering if the restart of zookeeper is taking too long.

**Comment by ChrisAubuchon** [comment]
Can you run `echo $HOSTNAME` and see if it is `cchub-control-02.novalocal`? That's what I'm seeing when reproducing the issue.

**Comment by kenjones-cisco** [comment]
it takes maybe 3-5 secs to restart zookeeper, and yes that is the address `cchub-control-02.novalocal` that I'm seeing.

Is the novalocal the issue?

**Comment by ChrisAubuchon** [comment]
Yes. We had a hack in to add the .novalocal addresses to /etc/hosts. It was removed by default but is restored with https://github.com/CiscoCloud/microservices-infrastructure/commit/72808e960c359bfd4327578cd40aced85ca7eebe

**Comment by kenjones-cisco** [comment]
That did resolve the issue I was seeing.

**Comment by stevendborrelli** [comment]
@kenjones-cisco Are we ok to close this issue?

**Comment by kenjones-cisco** [comment]
Yes, the fix that @ChrisAubuchon applied did the trick and the issue has been resolved.
Thanks

**Comment by stevendborrelli** [comment]
Thanks!
