### ISSUE TITLE
Get rid of ansible openstack playbooks

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#402]
Are these needed anymore? Between terraform and updated roles, I don't see the need for any of them.

```
destroy-hosts.yml
provision-consul-gossip-key.yml
provision-hosts.yml
provision-nova-key.yml
reboot-hosts.yml
show-containers.yml
show-package-drift.yml
show-uptime.yml
trace-consul-wan-traffic.yml
upgrade-packages.yml
verify-env.yml
```

There are duplicate playbooks for some of these in the `playbooks/` directory.

Any objections to me removing them?

**Comment by cdmitri** [comment]
Let's drop those, agreed - we can support the hackathon with prior commits
and features-master branch. Perhaps wait for Monday for changes in master
for team to sign off?
