### ISSUE TITLE
User provisioning broken with terraform

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#420]
Looks like the users are not getting provisioned using terraform dynamic inventory. 

Right now a fix is to pass in the user file to ansible via `-e @users.yml`

**Comment by BrianHicks** [comment]
for 0.4 maybe we should make a little daemon to populate users from Consul?

**Comment by ChrisAubuchon** [comment]
I was thinking a Consul+Vault combination.

**Comment by BrianHicks** [comment]
exactly!

**Comment by BrianHicks** [comment]
I'm closing this for 0.3, but I've opened #442 to track the ongoing work of moving it out of Ansible.
