### ISSUE TITLE
multiple frameworks loaded in mesos, limiting memory

### ISSUE THREAD

**Issue by nmarasoiu** [CiscoCloud/microservices-infrastructure#425]
Hi,

I had this situation today, with my master at eca1776df6e4a55128c6cc0c5bfb7368b54c3cdf
Mesos worked, but memory was too limited compared to cluster.
Investigated and found 2 frameworks running, both Marathon instances, and filled with my tasks both of them. Only one was visible on 8080 (the older one I remember).
What could cause this, do you know?

**Comment by stevendborrelli** [comment]
Can you check to see if those are mesos-consul and marathon-consul? Those are components that we use for service discovery. They both are configured to use 0.1 CPU and 128MB of RAM.

**Comment by nmarasoiu** [comment]
Hi,

There were more, in both frameworks. It should have been just 1 marathon
with 700m occupied but it was another with 1G that consisted of these and
my tasks. i wonder how a second marathon was started..i only run ansible
once afaik

În data de marți, 2 iunie 2015, Steven Borrelli <notifications@github.com>
a scris:

**Comment by stevendborrelli** [comment]
Could you post a screenshot of your marathon state or mesos tasks? That would help us understand what is going on in your environment.
