### ISSUE TITLE
Chronos role

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#43]
Deploy https://github.com/mesos/chronos via marathon for High Availability.

**Comment by tymofii-polekhin** [comment]
I'm working on this right now, and by far i got this output:
1. Downloaded source code from https://github.com/mesos/chronos
2. Installed maven and nodejs to build
3. Successfully launched chronos as mesos framework (with authentication disabled)

Working on ansible role for this

**Comment by tymofii-polekhin** [comment]
Found a workaround to launch mesosphere/chronos package
Working on this right now

**Comment by tymofii-polekhin** [comment]
https://github.com/CiscoCloud/microservices-infrastructure/tree/feature/chronos

**Comment by tymofii-polekhin** [comment]
Chronos ansible role
https://github.com/CiscoCloud/microservices-infrastructure/commit/f4cd4d4066bdbaf3bd4177262cc628718410c798

**Comment by tymofii-polekhin** [comment]
https://github.com/CiscoCloud/microservices-infrastructure/pull/437
