### ISSUE TITLE
rsyslog not forwarding on systems when selinux is enforcing

### ISSUE THREAD

**Issue by ryane** [CiscoCloud/microservices-infrastructure#452]
I noticed that logstash was not receiving syslogs on an AWS cluster but was working fine on a Vagrant install. On the AWS image, selinux is in enforcing mode; on the Vagrant image it is in permissive mode. Setting selinux to permissive on the AWS cluster allows forwarding again. Probably just need to configure selinux with a syslog port of 1514.

**Comment by stevendborrelli** [comment]
@ryane good find. Should we target this fix for 0.3.0 or 0.3.1?

**Comment by ryane** [comment]
this is ready to test, I think
