### ISSUE TITLE
Terraform inventory plugin doesn't work when region is blank.

### ISSUE THREAD

**Issue by matjohn2** [CiscoCloud/microservices-infrastructure#462]
When using terraform automation and then the inventory plugin; terraform.py fails when the region in the terraform manifest is set to ``` region = "" ```.

This is necessary for openstack environments which do not have region support enabled.

**Comment by BrianHicks** [comment]
@matjohn2 I'll fix that - could you send me your .tfstate or a stacktrace so I can reproduce?

**Comment by matjohn2** [comment]
Got everything you needed from our chat or want me to paste still?
