### ISSUE TITLE
Update Dockerfile for terraform

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#464]
- [ ] Add terraform install to Dockerfile
- [ ] change CMD to be a script that provisions via terraform and ansible

**Comment by stevendborrelli** [comment]
@kenjones-cisco we've moved to using terraform for cloud deployments, this still reflects the old deployment method. 

One issue I've found is that the terraform binary available from hashicorp doesn't seem to run in Alpine linux.

**Comment by kenjones-cisco** [comment]
@stevendborrelli is there a prefered base? centos, debian, ubuntu. I had considered updating but with the changes over the past week or so I thought it would be a good idea to wait for 0.3 to settle.
