### ISSUE TITLE
Update OpenStack docs for Terraform

### ISSUE THREAD

**Issue by loshkovskyi** [CiscoCloud/microservices-infrastructure#468]
Terraform looks great, thank you for adding it.

I've tested deployment in CiscoCloud and thought that we could extend our [docs](https://github.com/CiscoCloud/microservices-infrastructure/blob/master/docs/getting_started/openstack.rst) a little bit to make the deployments clearer for end users.

1. In particular `You can find them in openstack/ in the main project directory` looks to be outdated. Is it supposed to be in `playbooks/`?
2. From the user point of view, should we add a [link](http://www.terraform.io/downloads.html) to our docs of how to install Terraform? It's not provided from basic repositories yet.
3. To perform the `terraform get` or `terraform plan` commands, we need to:
```
cp terraform/openstack.sample.tf openstack.tf
```
and fill in all the variables.

Maybe it's a good idea to post some hints where to look for those variables. For example:

`glance image-list` for `image_name`
`keystone tenant-list` for `tenant_id` and `tenant_name`
`nova flavor-list` for `control_flavor_name` and `resource_flavor_name`
or the appropriate `openstack` commands such as `openstack project list`

`security_groups` probably should not be `default` to not mess up things.
The last one is that `public_key` should not be an ssh key itself but rather a path to the file.

Thank you.

**Comment by altvnk** [comment]
I support, I had to make some effort to understand all the things. We must highlight more details in the documentation.

**Comment by stevendborrelli** [comment]
@loshkovskyi @altvnk thanks for the raising the issue. We're working on it now.

**Comment by BrianHicks** [comment]
@loshkovskyi @altvnk I've pushed the docs at f07556c, would you review? I'm not sure what you mean by your public key comment, it uses a path now.

**Comment by altvnk** [comment]
Thanks guys, now it looks more obvious how to start using terraform.
