### ISSUE TITLE
terraform: wrong region configuration

### ISSUE THREAD

**Issue by ohal** [CiscoCloud/microservices-infrastructure#469]
after commit https://github.com/CiscoCloud/microservices-infrastructure/commit/d5001a16574832065e4fbcba0216b01380cf9dee

terraform is failing to deploy with issue below:
>There are warnings and/or errors related to your configuration. Please
fix these before continuing.

>Errors:

>  * module root: module dc2-keypair: required variable region not set

do we need to remove also related to 'region' configuration code below?

https://github.com/CiscoCloud/microservices-infrastructure/blob/master/terraform/openstack/keypair/main.tf

>diff --git a/terraform/openstack/keypair/main.tf b/terraform/openstack/keypair/main.tf
index 56c1e61..c3ac626 100644
--- a/terraform/openstack/keypair/main.tf
+++ b/terraform/openstack/keypair/main.tf
@@ -1,7 +1,6 @@
 variable auth_url {}
 variable tenant_id {}
 variable tenant_name {}
-variable region {}
 variable keypair_name {}
 variable public_key {}

>@@ -12,7 +11,6 @@ provider "openstack" {
 }

 >resource "openstack_compute_keypair_v2" "keypair" {
-  region        = "${ var.region }"
   name          = "${ var.keypair_name }"
   public_key    = "${ file(var.public_key) }"
 }

**Comment by BrianHicks** [comment]
@ohal could you try setting `variables region { default = "" }`  in your configuration and see if that fixes the issue?

**Comment by ChrisAubuchon** [comment]
Commit https://github.com/CiscoCloud/microservices-infrastructure/commit/f8da7e5

**Comment by BrianHicks** [comment]
@ohal if f8da7e5 doesn't fix this issue for you, feel free to reopen.

**Comment by ohal** [comment]
looks well, fixed by changes http://10.203.29.112:8080/view/CCS-MI-US-INTERNAL-1-QA-1/job/COMMIT-to-master-CCS-MI-US-INTERNAL-1-QA-1/57/
