### ISSUE TITLE
Add demo apps for common M-I usecases

### ISSUE THREAD

**Issue by matjohn2** [CiscoCloud/microservices-infrastructure#475]
As an engineer, I want to see and easily demo common solution-driven demo's ontop of MI to demonstrate the value/ease of the platform.

**Comment by PeterLamar** [comment]
2 tier app example as well

**Comment by BrianHicks** [comment]
Could we get a real crunchy specific list of demo apps that y'all would like to see? Unfortunately, I can't do a lot with "common solution-driven demos" or "2 tier app example". The more specific you can get about the examples, the better.

**Comment by siddharthist** [comment]
@matjohn2 @PeterLamar Do you guys have any specifics in mind? I can try to get to work on this, but I'd love some input on what would be most helpful. I saw in #83 that you had done some work on this, did you get anything solid @PeterLamar?

**Comment by PeterLamar** [comment]
A month later I discovered all the k8s and Marathon examples in their respective repos and used those. Thoughts?

**Comment by siddharthist** [comment]
As we haven't been able to decide on any concrete terms, let's close this. If somebody wants to see a specific app example running on Mantl, please open a ticket like #484.
