### ISSUE TITLE
Failed to issue method call: Unit collectd.service not loaded.

### ISSUE THREAD

**Issue by nmarasoiu** [CiscoCloud/microservices-infrastructure#478]
Hi,

With 0.3 I get:

NOTIFIED: [mesos | restart collectd] ****************************************** 
failed: [mi-worker-01] => {"failed": true}
msg: Failed to issue method call: Unit collectd.service not loaded.
Failed to issue method call: Unit collectd.service failed to load: No such file or directory.

failed: [mi-worker-03] => {"failed": true}
msg: Failed to issue method call: Unit collectd.service not loaded.
Failed to issue method call: Unit collectd.service failed to load: No such file or directory.

failed: [mi-worker-02] => {"failed": true}
msg: Failed to issue method call: Unit collectd.service not loaded.
Failed to issue method call: Unit collectd.service failed to load: No such file or directory.

FATAL: all hosts have already failed -- aborting

**Comment by corebug** [comment]
@nmarasoiu  It looks like collectd wasn't installed on a system before the mesos deployment.
What is your roles order.

**Comment by nmarasoiu** [comment]
it was right after common, like on master/0.3.
I commented out all references to starting or restarting the collectd service which may be optional for what i need now

**Comment by nmarasoiu** [comment]
also, interesting is that in terraform.sample.yml, the collectd role was duplicated, i now removed the one below (i saw a commit fixing a duplication, it may be the same thing, but i think i updated 2 hours ago)

**Comment by corebug** [comment]
@nmarasoiu the point is that to collect metrics from MI core software (Mesos, Marathon etc) we use collectd's plugins that are installed as parts of corresponding roles. It's pretty obvious that plugin install step can fail without the collectd core and its directories, configs and systemd service. I guess, to get rid of such problem in future we should just move collectd to common role (https://github.com/CiscoCloud/microservices-infrastructure/issues/480).

**Comment by corebug** [comment]
I think we can close the issue by now.
