### ISSUE TITLE
Move collectd to common role

### ISSUE THREAD

**Issue by corebug** [CiscoCloud/microservices-infrastructure#480]
At the moment it is required that collectd role is provisioned before any roles that include collectd plugins 
(https://github.com/CiscoCloud/microservices-infrastructure/issues/478 and several similar problems were noticed). 
As it's been already said, we must not rely on roles order for everything to work properly, so i propose to move all collectd installation related code to common role since collectd is part of core functionality and must exist on all nodes anyway.

**Comment by corebug** [comment]
@stevendborrelli what do you think about this issue?

**Comment by siddharthist** [comment]
@corebug We are currently relying extensively on role order. We are working on further modularization/optionality of roles, but for now, this issue is nil.
