### ISSUE TITLE
Add KONG as an example app

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#484]
Create an example configuration for http://getkong.org showing:

1. Running Cassandra Mesos framework
2. Running the KONG docker container

**Comment by sinzone** [comment]
+1

**Comment by ahmadnassri** [comment]
great idea, Kong definitely fits right at home here!

**Comment by pikeas** [comment]
+1, this would be a great example app!

**Comment by sinzone** [comment]
Github repo: https://github.com/mashape/kong

**Comment by Nijikokun** [comment]
:+1:

**Comment by stevendborrelli** [comment]
With today's mantl release of 0.5, we now can launch a cassandra cluster with a single curl command. We have also added a nice load balancer with Traefik. Anyone want to take a stab at launching the Kong API fronted?

**Comment by siddharthist** [comment]
I have actually started working on this!

**Comment by ahmadnassri** [comment]
@stevendborrelli @siddharthist happy to assist with kong related questions/setup if needed :)

**Comment by feliperfmarques** [comment]
Hello @siddharthist. I am trying to deploy a example using your branch (feature/kong), but I am having trouble, the cassandra cluster deployed by mantle-api get random port and not 9042 default port which is setted in kong config, furthermore the cassandra service is restarted and getting a new random port each time. Do you have the same trouble? 

So I get this error when in start up of my Kong container:

```
[0m[34m[INFO] [0m[0mUsing configuration: /etc/kong/kong.yml
[0m[34m[INFO] [0m[0mKong version.......0.5.4
       Proxy HTTP port....8000
       Proxy HTTPS port...8443
       Admin API port.....8001
       dnsmasq port.......8053
       Database...........cassandra keepalive=60000 timeout=1000 contact_points=mantl-cassandra.service.consul:9042 keyspace=kong
[0m[34m[INFO] [0m[0mConnecting to the database...
[0m[31m[ERR] [0m[0mCassandra error: connection refused
```

**Comment by siddharthist** [comment]
@feliperfmarques I don't think I've seen that one before, usually port 9042 worked for me and I ran into a different error. That branch is still WIP, but I'd love help getting it working.

**Comment by feliperfmarques** [comment]
Hello @siddharthist, thanks for your help. I'll debug more calmly and I report back here, ok? One question: In your deploy the health state of cassandra on marathon did stay green or gray? 

I understand that branch is still WIP, so I'd love to can help you in this working.

**Comment by siddharthist** [comment]
I'm asking around in the Kong community if anybody can help me with my issue. My problem is that the container appears to start sucessfully, and then exits. Mesos shows the task as "Finished", rather than "Failed". [Here are the logs](http://pastebin.com/raw/fGXS9XLv). Did you get any further @feliperfmarques?

**Comment by feliperfmarques** [comment]
@siddharthist Sorry for my delay, I was working in other codes last week, for this reason I didn't get any further.  I don't tried to deploy more times since the last time but I will to try these days and report back if I have any news. Furthermore, I also will following your issue in Kong community. Let's do This :smile:

**Comment by siddharthist** [comment]
Pull request is in! We'd love help with testing/review @feliperfmarques, @ all.  Please let me know if anything is unclear in the documentation, etc.
