### ISSUE TITLE
Mesos role priorities

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#486]
In mesos-user (http://www.mail-archive.com/user@mesos.apache.org/msg03574.html), there was a great post by Alex Gaudio on setting weights and roles to give priorities to different frameworks.

We should investigate setting these as part of the build. 

```
To let a particular mesos framework receive more offers than other
frameworks, we assign our frameworks weights.  The higher the weight, the
more frequently the framework will receive an offer.  See the '--weights'
and '--roles' options in the config:
http://mesos.apache.org/documentation/latest/configuration/.  Basically, a
higher weight > 1 means more offers get sent to your framework.  The mesos
source code for how weighting works is shown here:
https://github.com/apache/mesos/blob/9e7b890a917fcf0ac4cd1738f060ba97af847b65/src/master/allocator/sorter/drf/sorter.cpp#L306
and
https://github.com/apache/mesos/blob/9e7b890a917fcf0ac4cd1738f060ba97af847b65/src/master/allocator/sorter/drf/sorter.cpp#L41
.

What you may want to do is create a "role" called "development_mode" and
then assign the role a high weight (like 40).  You would then assign your
framework to the "development_mode" role.  What we've actually done is
created roles named the numbers 1,2,3,4,5,10,20,30,40, where each role maps
to a weight of that number ... and we then we allow frameworks to choose
which role they start up as.  At Mesoscon, I will be speaking about why we
do this and how we are solving some general issues with the DRF algorithm,
if you're interested!

Alex
```

**Comment by BrianHicks** [comment]
I imagine that this would need to be specified on an individual deployment basis, is it really something we should prescribe overall?

(for example, I would think that in some environments Spark jobs should be the highest priority, and in some the lowest, just depending on what the framework is being used for.)

**Comment by eirslett** [comment]
I don't think it's viable to specify this in general in mantl... the setup with roles, allocations, priorities etc. are too deployment-specific.
Even things like "database role", with specialised machines provisioned for database operations, is difficult to achieve with Mantl, and I'm not sure how it should be solved.

**Comment by siddharthist** [comment]
I'm going to close this, since there doesn't seem to be much interest. Please reopen if anybody thinks this should be implemented!
