### ISSUE TITLE
Mesos fails to bind when using floating IPs

### ISSUE THREAD

**Issue by michaeltchapman** [CiscoCloud/microservices-infrastructure#487]
When using floating IPs within OpenStack, the Mesos master is attempting to bind to the floating IP instead of its internal IP.

    mesos-master[10943]: F0615 06:16:25.256098 10943 process.cpp:868] Failed to initialize: Failed to bind on 173.37.43.141:15050: Cannot assign requested address: Cannot assign requested address [99]

**Comment by michaeltchapman** [comment]
Addressed by #483

**Comment by loshkovskyi** [comment]
@michaeltchapman can you please confirm this can be closed now? Thank you.
