### ISSUE TITLE
100% self maintaining system

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#49]
Control and Compute nodes need to be 100% self maintaining.  If an administrator needs to login it's a bug.

Some areas that will need attention:
    - OS log rotation
    - Purge old containers
    - Healing after a fault

**Comment by stevendborrelli** [comment]
Now that we are moving consul out of docker, we can put system-level checks into the consul agent. http://www.consul.io/docs/agent/checks.html

This way we can monitor nodes for disk, memory, etc.

**Comment by keithchambers** [comment]
Log rotation discussion in the Mesos community: 
http://www.mail-archive.com/user@mesos.apache.org/msg02667.html

**Comment by pikeas** [comment]
Not directly related to this issue, but why did this project decide to move Consul out of docker?

**Comment by stevendborrelli** [comment]
@pikeas running consul in a docker container made a lot of other things more complicated. 

Networking made contacting 127.0.0.1 more complicated. It was hard to configure things like SSL or more dynamic checks without doing host mounts. 

As our docker command line got longer and longer to connect the consul daemon into the host, we decided that systemd + static binary made our lives easier.

**Comment by stevendborrelli** [comment]
Moving this to a future feature. 

We'll have a docker cleanup package in 0.5. We'll address Mesos packaging in 0.6.

**Comment by siddharthist** [comment]
Docker cleanup: #861
Disk monitoring: #959 
Logrotate is implemented.

Can we consider this ticket done when those three tasks are done? Or at least break it up into well-defined parts?

**Comment by siddharthist** [comment]
Closing as this is pretty nebulous and lots of the requested features have been implemented. Please feel free to open more specific tickets!
