### ISSUE TITLE
0.3.1 release testing

### ISSUE THREAD

**Issue by BrianHicks** [CiscoCloud/microservices-infrastructure#498]
Testing 0.3.2-RC2 tag.

- [x] DigitalOcean (@chrisaubuchon)
- [x] Vagrant (@chrisaubuchon)
- [x] AWS (@ryane)
- [x] OpenStack (@brianhicks)
- [x] GCE (@brianhicks)

**Comment by siddharthist** [comment]
I can cover DigitalOcean

**Comment by BrianHicks** [comment]
@ChrisAubuchon is already testing it. Can you get OpenStack?

**Comment by BrianHicks** [comment]
Vagrant's busted! Moving to 0.3.1-RC3
