### ISSUE TITLE
Kafka message bus

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#50]
Implement Kafka message bus

Should this run on the controller on compute nodes?  It's sort of oxygen for our stack ...

Needs to be self maintaining

We need to consider security aspects

Let's use the bits from Confluent: http://confluent.io/downloads/

**Comment by keithchambers** [comment]
Our plan is to use https://github.com/mesos/kafka

**Comment by stevendborrelli** [comment]
Fixed via #41.
