### ISSUE TITLE
Port conflicts in 4000-5000 range

### ISSUE THREAD

**Issue by bajohns** [CiscoCloud/microservices-infrastructure#503]
Greetings,

Looks like there is an issue created by #233.  

First, I assume the Vagrant file exists for users to try the setup.  It is fairly likely that a port between 4000 and 5000 will already be bound on a personal machine.  Examples: Spotify takes 4370 and Drobo NAS Admin takes 4502.

Can a much higher range be used to avoid these conflicts?

**Comment by michaeltchapman** [comment]
Alternatively give the VM an IP on a private vbox network instead of using forwarded ports. This might be needed for simulating clusters in the future anyway.

**Comment by BrianHicks** [comment]
we're going to have to reconsider a lot of things about Vagrant for future releases. This is one of them–I run into that Spotify conflict all the time, too.

**Comment by gesrat-cisco** [comment]
If I recollect, the Vagrantfile for the Mesosphere tutorial uses vbox private network configuration
