### ISSUE TITLE
Random failure after random kernel upgrade

### ISSUE THREAD

**Issue by eirslett** [CiscoCloud/microservices-infrastructure#504]
I started a 8-node cluster on DigitalOcean with the default settings. One of the nodes failed with a kernel panic, it seems like the kernel was upgraded at some point during the Terraform build. It's strange that it only happened to one node, though...
Is kernel upgrading a part of the Terraform run? Or could it be something that happened on the DigitalOcean side?

**Comment by loshkovskyi** [comment]
Hello @eirslett ,

Most likely, it happened on the DigitalOcean side.

I have checked the Terraform sources and I see they import https://github.com/pearkes/digitalocean to create instances with [CreateDroplet()](https://github.com/pearkes/digitalocean/blob/master/droplet.go). The last one doesn't have any kernel upgrade functionality.

I have tested creation of 10 droplets several times and couldn't reproduce the issue. I would recommend contacting DigitalOcean support in case you encounter such problems again.
