### ISSUE TITLE
How to inject properties from consul into docker containers

### ISSUE THREAD

**Issue by audunstrand** [CiscoCloud/microservices-infrastructure#507]
How do I get properties, eg. database urls, from consul, injected into my docker container at startup?

**Comment by stevendborrelli** [comment]
There are a few ways to do it: 

1) create environment variables when you launch your container. Your marathon json file will include something like the following: 
```
    "env": {
      "MYSQL_USER": "user",
      "MYSQL_PASSWORD": "pwd",
      "MYSQL_ROOT_PASSWORD": "secret"
    }
```

2) You can use consul-template in your container to query values in Consul K/V or consul service discovery. We have an example container that includes a consul-template binary at https://github.com/CiscoCloud/haproxy-consul, and an example configuring zookeeper is at: https://github.com/CiscoCloud/docker-zookeeper

3) There is also a project called envconsul that can set environment variables via Consul: https://github.com/hashicorp/envconsul
