### ISSUE TITLE
documentation fixes

### ISSUE THREAD

**Issue by BrianHicks** [CiscoCloud/microservices-infrastructure#509]
After talking with @Raffo on Gitter, I think we need some updates to the docs:

- [ ] make it clear that Python 2 is the version one should use for this project
- [ ] make it clearer that `vagrant up` is the only command one needs to get started

**Comment by gesrat-cisco** [comment]
specific instructions for deploying MI on OSX+Vagrant+VBox

**Comment by ObjectiveJoe** [comment]
Is the first of these two points for internal developers, and the second for external developers using Shipped? If so, perhaps we should split these into two separate issues.

**Comment by BrianHicks** [comment]
@ObjectiveJoe they're both for both, really. If someone wants to use MI for *anything* they'll need to get past the bootstrap step, and that's not currently well documented.

**Comment by Raffo** [comment]
Adding something more: as suggested, installing the requirements with python2 make everything work quite fine. I would also add that there are some other minor problems: running step 2 in the example here  https://github.com/CiscoCloud/microservices-infrastructure/tree/master/examples/hello-world is impossible as marathon doesn't seem to be running as HTTPS in my case. HTTP makes it work. I'm writing this just to understand if it is a documentation problem, if there's something not right we can discuss it somewhere else.

**Comment by ObjectiveJoe** [comment]
Is it fine to say we require Python 2.7 or later, or just say Python 2?

**Comment by ObjectiveJoe** [comment]
Also, is this still true or shorten it up and really just say 'vagrant up'? 
           "ensure that you set your provider to Virtualbox when running `vagrant up`: `vagrant up --provider=virtualbox`."

**Comment by mcelligott** [comment]
The provider part should be handled via the generated Vagrantfile. It is ABSOLUTELY NECESSARY to include `--no-parallel` in the `vagrant up` command

**Comment by BrianHicks** [comment]
@ObjectiveJoe 2.6 and 2.7 are [supported by Ansible](http://docs.ansible.com/intro_installation.html#control-machine-requirements). Our scripts are written and tested on 2.7, we haven't had anybody using 2.6 yet but I suppose it's just a matter of time… are you working on this?

The Virtualbox provider is enabled by default, people who use alternate implementations would know when they need to use that flag, since they have to set up a different integration.

@mcelligott why is that necessary? I've never used that, and my machines come up just fine. Are you using an altered Vagrantfile?

**Comment by BrianHicks** [comment]
@Raffo it sounds like you've disabled HTTPS for Marathon. If that's not it, please open up a ticket.

**Comment by mcelligott** [comment]
@BrianHicks sorry, I'm probably off-base. I assumed this issue applied to running a shipped project, but I just saw that this is an M-I ticket. In shipped, we need `--no-parallel` because some VMs are dependent on others and `vagrant up` will fail if the dependencies are not up before the dependent VMs boot up. But that probably doesn't apply here. Apologies for the confusion

**Comment by BrianHicks** [comment]
@mcelligott no problem, thanks for clarifying.

**Comment by ObjectiveJoe** [comment]
@BrianHicks, I have read access but no write access. Please update my permission and I will create branch for document_updates, submit changes, and create pull request.

**Comment by BrianHicks** [comment]
@ObjectiveJoe can you just fork the repo and do it that way? I'm going to take that to mean that you're working on this issue, though. I'll assign you here. Thanks!

**Comment by stevendborrelli** [comment]
Python 2.7 came out in 2010, I think it's ok that we make it the base 2.x version

**Comment by Raffo** [comment]
@BrianHicks I cannot reproduce the issue I was having right now, I'll open an issue if I find something more specific.
