### ISSUE TITLE
dnsimple

### ISSUE THREAD

**Issue by eirslett** [CiscoCloud/microservices-infrastructure#516]
It would be nice to be able to access the control and worker nodes like this:

control-01.mydatacenter.example.com
control-02.mydatacenter.example.com
control-03.mydatacenter.example.com
worker-001.mydatacenter.example.com
worker-002.mydatacenter.example.com
worker-003.mydatacenter.example.com

Is it possible to set up dnsimple with microservices-infrastructure, to work that way?

**Comment by stevendborrelli** [comment]
@eirslett You should be able to do it via terraform. It will require a little bit of modification on your behalf, but there is a dnsimple provider in terraform that should do the trick. (You'll have to use vars in the provider definition to match each IP to a hostname). 

Please let me know if this works for you. It would be awesome if you could document an example. 

https://www.terraform.io/docs/providers/dnsimple/index.html

**Comment by eirslett** [comment]
I tried, and hit this bug: https://github.com/hashicorp/terraform/issues/2441

What worked in the end, was to put dnsimple inside terraform/digitalocean/hosts/main.tf, but that is a very tight coupling between digitalocean and dnsimple that we want to avoid. I hope we'll hear from the Terraform team soon, about the issue/bug.

**Comment by pikeas** [comment]
hashicorp/terraform#2441 was closed as a dup, the live issue can be found at https://github.com/hashicorp/terraform/issues/2301.

**Comment by stevendborrelli** [comment]
I believe we have addressed this via #653.
