### ISSUE TITLE
logrotate is messy

### ISSUE THREAD

**Issue by BrianHicks** [CiscoCloud/microservices-infrastructure#519]
Logrotate currently rotates and creates archives for Mesos, Docker, and ZooKeeper. Each one has a slightly different configuration, but there's a lot of repetition going on. There should be a generic role built in and used through Ansible's metadata dependencies in order to DRY this up.

**Comment by stevendborrelli** [comment]
I'm wondering if  the docker log rotate even works, we just get a file with 0 bytes that never gets updated for the containers.
