### ISSUE TITLE
Push container logs to Kafka

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#52]
This this tread for implementations:  https://github.com/gliderlabs/logspout/pull/35

We should add "Shipped Deployment Tag ID", Container ID, Hostname to each log/event.

**Comment by stevendborrelli** [comment]
0.5 supports this functionality. Closing this ticket. 

https://github.com/CiscoCloud/microservices-infrastructure/blob/master/roles/logstash/defaults/main.yml
