### ISSUE TITLE
Possible bug in terraform.py inventory script

### ISSUE THREAD

**Issue by linuxbsdfreak** [CiscoCloud/microservices-infrastructure#529]
Hi,

I was not able to ping the launched instances via terraform tool with the terraform.py inventory script.

I tested on centos6.5 and centos7. I also added the nodes in a static inventory file and ansible was able to ping the nodes.

I keep getting the following error:

ansible -i plugins/inventory/terraform.py all -m ping -u ec2-user 
Traceback (most recent call last):
  File "/usr/bin/ansible", line 66, in <module>
  File "/usr/lib/python2.7/site-packages/ansible/cli/adhoc.py", line 140, in run
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 88, in __init__
  File "/usr/lib64/python2.7/multiprocessing/__init__.py", line 218, in Queue
  File "/usr/lib64/python2.7/multiprocessing/queues.py", line 63, in __init__
  File "/usr/lib64/python2.7/multiprocessing/synchronize.py", line 147, in __init__
  File "/usr/lib64/python2.7/multiprocessing/synchronize.py", line 75, in __init__
OSError: [Errno 24] Too many open files

Could someone try to launch and check if this is an issue.

Regards,
Kevin

**Comment by stevendborrelli** [comment]
Thanks for filing this issue. 

Is there any way we can duplicate your environment? (For example, letting us use your terraform config file with tokens redacted). 

Also what OS, Python and Ansible versions are you using?

cc @BrianHicks @ryane

**Comment by linuxbsdfreak** [comment]
terraform version
Terraform v0.5.3

OS: Fedora21 (Control node)
Python: 2.7.8
ansible 2.0.0

aws.tf

provider "aws" {
  access_key = "xxx"
  secret_key = "xxx"
  region = "eu-west-1"
}

module "aws-dc" {
  source = "./terraform/aws"
  availability_zone = "eu-west-1a"
  control_type = "m3.medium"
  worker_type = "m3.medium"
  ssh_username = "ec2-user"
  source_ami = "ami-8b22effc"
  ssh_key   = "~/.ssh/id_rsa.pub"
  control_count = 1
  worker_count = 1
}

**Comment by BrianHicks** [comment]
@linuxbsdfreak I'll just ask again in here what I asked in Gitter, answer either place and I'll keep this updated:

> did adjusting ulimits not help? Are you still running within the Docker container?

**Comment by ryane** [comment]
@linuxbsdfreak also, are you able to test with ansible 1.9? I don't think we've done any testing with 2.0 which hasn't had an official release yet afaik.

**Comment by stevendborrelli** [comment]
I'm also worried about Centos 6.5, as we've never tested deploying to that version, so I'm certain it worn work. Ryan has suggested using ami-e4ff5c93 instead.

**Comment by linuxbsdfreak** [comment]
Ok it works with that image which is centos 7 and  ansible 1.9.2 (stable-1.9 db5ea10ed2) last updated 2015/06/29 14:30:11 (GMT +200)

**Comment by stevendborrelli** [comment]
Awesome! Let us know how the rest of the install goes.

**Comment by stevendborrelli** [comment]
@linuxbsdfreak I'm going to close this issue. We've created an issue in the terraform.py project to track Ansible 2.0 support. 

We don't plan on adding Centos/Redhat 6.x support.
