### ISSUE TITLE
Performance + usage metrics Linux + Mesos + Marathon + Containers

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#53]
High level story is that we want the entire system to be well instrumented right out of the box.  This will include:
* Linux host metrics
  * CPU states
    * Per core
    * Average for all cores
  * Memory
  * Disk
    * IO count
    * IO size
    * IO service time (histogram):
      * I'd like the leverage [Brandon Gregs](http://www.brendangregg.com)'s [great work](https://github.com/brendangregg/perf-tools/blob/master/iolatency) in this space.
        * Example collectd metric:
          * disk.sda.block_size_kb.1 18
          * disk.sda.block_size_kb.2 2
          * disk.sda.block_size_kb.4 2
          * disk.sda.block_size_kb.8 2
          * disk.sda.block_size_kb.16 10
          * disk.sda.block_size_kb.32 2
          * disk.sda.block_size_kb.64 17
          * disk.sda.block_size_kb.128 0
          * disk.sda.block_size_kb.256 0
          * disk.sda.block_size_kb.512 0
          * disk.sda.block_size_kb.1024 0
          * disk.sda.read_time_ms.1 10
          * disk.sda.read_time_ms.2 2
          * disk.sda.read_time_ms.4 100
          * disk.sda.read_time_ms.8 12
          * disk.sda.read_time_ms.16 12
          * disk.sda.read_time_ms.32 12
          * disk.sda.read_time_ms.64 100
          * disk.sda.read_time_ms.128 0
          * disk.sda.read_time_ms.256 0
          * disk.sda.read_time_ms.512 12
          * disk.sda.read_time_ms.1024 0
          * disk.sda.read_time_ms.2048 0
          * disk.sda.read_time_ms.4096 12
          * disk.sda.read_time_ms.8192 0
          * disk.sda.read_time_ms.16384 0
    * Queue depth
  * Network
    * IO count
    * IO size
  * Users
    * Count
    * Logged in
  * Uptime

* Mesos metrics
  * https://github.com/rayrod2030/collectd-mesos

* Marathon metrics
  * https://github.com/klynch/collectd-marathon

* ZooKeeper
  * https://github.com/signalfuse/collectd-zookeeper
  * Collectd has a native ZooKeeper plugin now but it requires the c bindings and Alpine Linux does not package this collectd plugin

* Consul metrics
* Container metrics
  * Size
  * Uptime
  * CPU
  * RAM
  * Network IO
  * Disk IO
  * Disk space

This needs to be broken in to a number of smaller issues.

**Comment by keithchambers** [comment]
I just had a hallway conversion with @matjohn2 about this.  We are thinking:
* Use collectd
* Run plugins in Docker containers
* Use [gliderlabs/alpine](https://registry.hub.docker.com/u/gliderlabs/alpine/) as the base image
* Favor histograms over 1 dimensional metrics

**Comment by brucemartins** [comment]
Have you thought of using hekad over collectd? Does both metrics and log streaming and written in GO

**Comment by keithchambers** [comment]
I have not!  I'll look now.  Are you running hekad in production?

**Comment by brucemartins** [comment]
We are using it, technically the service isn't live yet, but just thought I would share some of the things we use or have looked at.. look for an invite soon

**Comment by keithchambers** [comment]
Cool. Let's chat soon Bruce!  :-)

**Comment by keithchambers** [comment]
Logstash filters from the Mesos community: http://www.mail-archive.com/user@mesos.apache.org/msg02731.html

**Comment by keithchambers** [comment]
Collectd plugin discussion from the Mesos community: http://www.mail-archive.com/user@mesos.apache.org/msg02773.html

We definitely want to give back any improvements we make to the community.

**Comment by corebug** [comment]
I'm currently working on this issue.

**Comment by maier** [comment]
i am as well. [collectd-cadvisor](https://github.com/maier/cadvisor-collectd/) is a work in progress. will be starting on ansible orchestration this week, got side-tracked by another issue late last week.

**Comment by corebug** [comment]
Closed by https://github.com/CiscoCloud/microservices-infrastructure/pull/417.
