### ISSUE TITLE
ElasticSearch

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#54]
Perhaps via Mesos framework

**Comment by corebug** [comment]
What about https://github.com/mesosphere/elasticsearch-mesos ?

**Comment by corebug** [comment]
I'm currently working on this issue.

**Comment by keithchambers** [comment]
We are developing an Elasticsearch framework over here: https://github.com/mesos/elasticsearch

**Comment by mwl** [comment]
Am I right in assuming that what's left here is just importing whatever work we did in the _Alpha_ repository?

**Comment by corebug** [comment]
@mwl yes, right after we finish the proxy stuff :-)

**Comment by ryane** [comment]
we have an elasticsearch framework package available to install in mantl-api now (0.5.2). I think we can move to 0.6.x after we upgrade mesos. I will close this and open another issue for the proxying support
