### ISSUE TITLE
security doc can not contain spaces nor quotes

### ISSUE THREAD

**Issue by vallard** [CiscoCloud/microservices-infrastructure#543]
Ansible scripts fail if the password entered has a space or a quote '.

**Comment by siddharthist** [comment]
@vallard Can you post the output you're seeing when the Ansible run fails?

**Comment by vallard** [comment]
I'll run again and capture output.

**Comment by vallard** [comment]
The password I entered was: ci$34'sco.
``` ______________________________________ 
< TASK: nginx | encrypt admin password >
 -------------------------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


fatal: [mi-worker-03] => error parsing argument string 'htpasswd -Bnb admin ci$34'sco. | cut -f 2 -d ':'', try quoting the entire line.
fatal: [mi-worker-02] => error parsing argument string 'htpasswd -Bnb admin ci$34'sco. | cut -f 2 -d ':'', try quoting the entire line.
fatal: [mi-worker-01] => error parsing argument string 'htpasswd -Bnb admin ci$34'sco. | cut -f 2 -d ':'', try quoting the entire line.
fatal: [mi-control-02] => error parsing argument string 'htpasswd -Bnb admin ci$34'sco. | cut -f 2 -d ':'', try quoting the entire line.
```
Changing the line by adding quotes around the password gets through that:
roles/nginx/tasks/main.yml: 
from: 
```
 shell: htpasswd -Bnb admin {{ nginx_admin_password }} | cut -f 2 -d ':'
```
to 
```
 shell: htpasswd -Bnb admin "{{ nginx_admin_password }}" | cut -f 2 -d ':'
```

**Comment by vallard** [comment]
but I can see how this might fail if the password has " in it.  Maybe we just call out what is an acceptable password in the documentation ?

**Comment by siddharthist** [comment]
@vallard Thanks for capturing that! I think we should attempt to have as few disallowed characters as possible, so I like the idea of changing that line to include single quotes and documenting their disallowal. Single quotes should cause the fewest other issues, since the shell won't try and interpret $ variables inside them.

**Comment by siddharthist** [comment]
@vallard If you want to submit a PR, that'd be great (documentation is in ./docs), but if not, I'll get around to it as soon as I have the time.

**Comment by ryane** [comment]
There are actually still some issues with this. The escaped password is incorrectly written into some configuration files. For example `/etc/consul/marathon.json` which prevents consul from restarting:

```
consul[31838]: ==> Error decoding '/etc/consul/marathon.json': invalid character '$' in string escape code
```

**Comment by BrianHicks** [comment]
Great. I guess we’ll have to add an “escape” filter and just 
escape where necessary, then.

**Comment by BrianHicks** [comment]
@ryane does [`feature/spaces-in-password-2`](https://github.com/CiscoCloud/microservices-infrastructure/tree/feature/spaces-in-password-2) fix this for you?

**Comment by ryane** [comment]
I'll give it a shot

Ryan Eschinger | http://ryaneschinger.com
Phone: 347-394-2990
Skype: ryanesch

**Comment by BrianHicks** [comment]
🙌
