### ISSUE TITLE
Automate Calico networking into M-I default install

### ISSUE THREAD

**Issue by matjohn2** [CiscoCloud/microservices-infrastructure#548]
Calico networking has already been proved compatible and steps to reproduce documented.
This needs automating into the default M-I automation to allow marathon workloads to haver the ability to use full IP addresses out of the box

**Comment by loshkovskyi** [comment]
Calico is using etcd for elections and endpoints registration. As far as I understand, we need to register container IP (from the Calico network) into Consul. Do we need to build a bridge like etcd-consul as we did with  mesos-consul? Right now we can query etcd for an IP address this way:
```
curl -L http://127.0.0.1:4001/v2/keys/calico/v1/host/mi-worker-01/workload/docker/a7727a7/endpoint

{
    "action": "get",
    "node": {
        "createdIndex": 53,
        "dir": true,
        "key": "/calico/v1/host/mi-worker-01/workload/docker/a7727a7/endpoint",
        "modifiedIndex": 53,
        "nodes": [
            {
                "createdIndex": 53,
                "key": "/calico/v1/host/mi-worker-01/workload/docker/a7727a7/endpoint/5d22bfe8255d11e5a808fa163ebcde60",
                "modifiedIndex": 53,
                "value": "{\"ipv6_gateway\": null, \"state\": \"active\", \"name\": \"cali5d22bfe8255\", \"ipv6_nets\": [], \"ipv4_gateway\": \"10.10.10.5\", \"ipv4_nets\": [\"192.168.0.2/32\"], \"profile_ids\": [\"mi\"], \"mac\": \"de:68:53:f3:2b:c8\", \"container:if_name\": \"eth1\"}"
            }
        ]
    }
}
```
Where 192.168.0.2 is the IP address we are looking for.
`a7727a7` is a Docker container that is running on top of Marathon.

Just trying to figure out some use cases of such deployments.

**Comment by PeterLamar** [comment]
I absence of an answer to your question, lets go with your best guess and a PR. We can deploy it to tenants and get feedback pretty quickly and iterate from there. Thoughts?

**Comment by loshkovskyi** [comment]
PR https://github.com/CiscoCloud/microservices-infrastructure/pull/598

**Comment by loshkovskyi** [comment]
Merged with PR https://github.com/CiscoCloud/microservices-infrastructure/pull/658
