### ISSUE TITLE
mesos services not properly enabled/disabled

### ISSUE THREAD

**Issue by ryane** [CiscoCloud/microservices-infrastructure#549]
On multi-node clusters, the `mesos-master` service should be enabled and running on control nodes but disabled on worker nodes. On worker nodes, the `mesos-slave` service should be enabled and running but disabled on control nodes. The ansible roles are correctly configured for this.

However, there is a bug in the ansible service module that does not properly set the enabled state of a service:

https://github.com/ansible/ansible-modules-core/issues/1136

The result is that both `mesos-master` and `mesos-slave` are always enabled on both control and worker nodes. This causes problems when nodes are rebooted.

The bug is fixed in Ansible 1.9.1. Currently, requirements.txt pegs the Ansible version at 1.9.0.x.

**Comment by kenjones-cisco** [comment]
FYI, The cap was added in #320 due to an issue with one of the former openstack playbooks, with the introduction of terraform the cap is not required.
