### ISSUE TITLE
Kibana 4

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#55]
Kibana 4 for viewing logs and metrics.

Needs to support authentication.
Multi-tenancy needs to be considered for hosted use-cases.

- This is a FRAMEWORK (tied to the roadmapped Elasticsearch / Logstash frameworks) however may not be configured out of the box to receive logs from the M-I platform.

**Comment by loshkovskyi** [comment]
@keithchambers is this issue still relevant? For example, we don't have any central storage such as Elasticsearch cluster from where we could load and parse entries with Kibana.

**Comment by siddharthist** [comment]
Closing in favor of https://github.com/CiscoCloud/mantl-universe/issues/9
