### ISSUE TITLE
Environment variable "NGINX_PUBLIC_IP" rendered incorrectly

### ISSUE THREAD

**Issue by loshkovskyi** [CiscoCloud/microservices-infrastructure#553]
The following expression is rendered incorrectly:
```
{% raw %}{{ env "NGINX_PUBLIC_IP" }}{% endraw %}
```
This line is pasted 'as is' in `/etc/consul/consul.nginx`, `/etc/marathon/marathon`, etc.
For example:
```
listen {% raw %}{{ env "NGINX_PUBLIC_IP" }}{% endraw %}:8500
```
Expected behaviour - the line is rendered to something like:
```
listen 10.10.10.10:8500
```

**Comment by loshkovskyi** [comment]
PR https://github.com/CiscoCloud/microservices-infrastructure/pull/554

**Comment by ChrisAubuchon** [comment]
This is incorrect. It is expected to render as
```listen {{ env "NGINX_PUBLIC_IP" }}```
The `.nginx` templates are put into Consul for each node to pull down via the `nginx-consul` container. The NGINX_PUBLIC_IP environment variable is passed into the container at startup. Check out https://github.com/CiscoCloud/microservices-infrastructure/blob/master/roles/consul/templates/nginx-consul.env.j2 for an example of the environment variables passed to the container.

**Comment by loshkovskyi** [comment]
Yes, looks like I got it wrong. Thank you for explanation.
