### ISSUE TITLE
docker_launch.sh checking /ssh fails

### ISSUE THREAD

**Issue by kenjones-cisco** [CiscoCloud/microservices-infrastructure#555]
```
find: '/ssh/*': No such file or directory
cp: missing file operand
Try 'cp --help' for more information.
```

I build the image for MI, and use as a base image. Then I handle decrypting my keys from source control and placing within `~/.ssh/` (`/root/.ssh/`). Because it seems fixed to requiring the directory `/ssh/` the script fails. Even if creating the `/ssh/` directory within my dockerfile and copying my keys there after decrypting fails as the volume points a non-existent directory. 

Requiring a volume be mounted for ssh keys seems overly restrictive. Maybe just adding a check if `SSH_KEY` already exists then skip trying to create `/root/.ssh` and copying files from `/ssh/` ?

**Comment by kenjones-cisco** [comment]
```
if [ ! -f "$SSH_KEY" ]; then
    mkdir -p /root/.ssh/
    find /ssh/* ! -type l -print0 | xargs -0 cp -t /root/.ssh/
fi
```

That does work and provides the ability to use mi as a base image. I can submit a PR to apply that change.

**Comment by ryane** [comment]
sounds good to me. I wasn't thrilled with the existing way of managing ssh keys but hadn't really come up with a better one

**Comment by stevendborrelli** [comment]
Closing with the merge of #556
