### ISSUE TITLE
Kafka to ElasticSearch consumer

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#56]
To get the logs out of Kafka and in the ElasticSearch

**Comment by siddharthist** [comment]
We now have support for both ElasticSearch and Kafka via mantl-api. Is this issue still relevant?

**Comment by ryane** [comment]
Yes, we should have all the pieces in place for this. It should be possible to launch ElasticSearch with a Kafka input plugin configured to read from a topic.

Please re-open if there is a specific use case we are missing
