### ISSUE TITLE
HAPROXY_MODE option to be added

### ISSUE THREAD

**Issue by kenjones-cisco** [CiscoCloud/microservices-infrastructure#560]
Based on the video demo for minecraft, as of 0.3.2, HAPROXY_MODE was going to be included in the configurations for haproxy. I noticed it was still not there.

Has the plan changed or is it no longer necessary?

**Comment by BrianHicks** [comment]
After discussion, we didn't want to introduce a breaking change like that in a patch release. We should probably change it for 0.4.

**Comment by ryane** [comment]
closing this one since we are moving to traefik instead of haproxy-consul
