### ISSUE TITLE
Bake VM image in Atlas (Packer)

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#57]
Bake VM image in Atlas (Packer)
    - Controller
    - Compute

**Comment by keithchambers** [comment]
[This](https://github.com/riywo/mesos-ceph) repo could be a good resource when the time comes.

**Comment by matjohn2** [comment]
I'm currently looking at creating a build pipeline with packer/atlas from our current master branch. The idea is to produce output images based on whatever is currently in ansible for a given build.

There will be two output images: microservices_master and microservices_compute.

Future dependancies on ansible are not explicit, it just allows me to try this out without the added work of re-factoring without ansible.

Some of the Init and configuration/templating will need to change to support packer/atlas configuration variables and consul service lookups for all services on start.

Currently working of a local feature branch, will push when i've got something concrete, at the moment it's a bit messy with my IaaS credentials in packer scripts etc.

**Comment by stevendborrelli** [comment]
Closing for vagrant as a dup of #815. We'll add other cloud providers individually to our sprint backlog.
