### ISSUE TITLE
Enabling SELinux 

### ISSUE THREAD

**Issue by saswatp** [CiscoCloud/microservices-infrastructure#571]
It is very important to enhance security of host vms running on micro services infrastructure. For many it is a requirement to go production. Therefore it is desirable to have SELinux turned on for the VMs orchestrated by microservices-infrastructure. It can be started with SELinux as permissive , so that at least auditing can be done on security violations. Later SELinux can be enforced. Has anyone investigated the impact of enabling SELinux and what it would take to enable it ?

**Comment by Lennie** [comment]
Currently as I understand it (this may be outdated):
1. SELinux only protects the host for the guests, not so much the guests from each other. Because I believe they are use the same SELinux context (if that is the right terminology).
2. When using volumes, you might need to prepare the volumes before use so they have the right SELinux properties or the volumes will be unusable.

**Comment by stevendborrelli** [comment]
SELinux is currently not on our roadmap, but it would be interesting to see the impact. https://www.digitalocean.com/community/tutorials/an-introduction-to-selinux-on-centos-7-part-1-basic-concepts

@saswatp do you want to try enabling it and see what comes up?

**Comment by saswatp** [comment]
@stevendborrelli - Yes that is in my plan. Will be able to work on that next week.

**Comment by stevendborrelli** [comment]
@saswatp from what I understand from @ryane, the AWS image already has SELinux running in enforcing mode.

**Comment by saswatp** [comment]
@stevendborrelli : That's great to know , hopefully there won't issues in openstack. I will update you with my findings with the CentOS cloud image used OpenStack.

**Comment by saswatp** [comment]
I did a test with SELinux enforced on Openstack. All services came up fine and their status could be seen through Consul UI. Do you have a set of automated test cases that I could run to see everything is working fine ?

**Comment by stevendborrelli** [comment]
@siddharthist, can you reach out to @saswatp about automated testing?

**Comment by siddharthist** [comment]
@saswatp We are currently working on integrating our automated tests, hopefully we will be releasing later this week. They will be accessable through the Consul UI. 

Related: PR #564 

If you're itching to get started, you could install them yourself, or just look through the checklists and manually validate that they would all pass. 

Checklists: https://github.com/CiscoCloud/distributive-rpm/tree/master/SOURCES
Distributive: https://github.com/CiscoCloud/distributive

**Comment by saswatp** [comment]
@siddharthist - Hey, quick question on distributive. Services add their health check scripts during deployment and the health of the the service is tracked by consul and shown on Consul UI ? Is distributive trying to organize all health check scripts under one umbrella ? Could you please explain how is it enhancing 

what consul already offers

**Comment by siddharthist** [comment]
@saswatp Absolutely. Distributive essentially packages a whole bunch of health checks into one binary file, and then enables them to be configured simply via JSON. It also makes it easier to package different checks for the same component together. It attempts to remove duplicated effort on defining ~100+ different health checks, like a project such as MI requires. 

So the overarching goals are:
 * Organization of checks into checklists (one per component) 
 * Ease of configuration (unified JSON configuration)
 * Ease of distribution (a single ~5MB binary)
 * Less duplication of effort (defining 10 similar bash commands to see if a port is open)

**Comment by saswatp** [comment]
I did some testing on a single node (on openstack) control VM with SELinux enabled. There were some major issues.

Steps : 

- Orchestrate and Configure a Control VM in Openstack.
- Manually ssh into the box and enable SELinux. 
- Reboot the box - Marathon , ZK and Chronos are not running .  Marathon is not able to port 18080; With a Connection refused error message.

Here is an image snapshot : 

<img width="787" alt="screen shot 2015-07-22 at 1 17 35 pm" src="https://cloud.githubusercontent.com/assets/5034927/8836195/1d336762-3074-11e5-97f9-008433733943.png">

**Comment by abn** [comment]
@saswatp FWIW, I do not think this is an SELinux issue. I can confirm the deployment works without issues on CentOS 7 boxes wit SELinux in enforcing mode.

**Comment by siddharthist** [comment]
@saswatp What platform are you deploying on?

**Comment by ryane** [comment]
@saswatp can you take a look at the zookeeper, marathon and chronos logs to see if there are any clues as to why they aren't starting?

**Comment by saswatp** [comment]
@abn - You may be right. I didn't see anything in SELinux log in /var/log/messages . This could be a separate issue. 

I am going to close this issue. If at all there is anything in zookeper etc. that's a new issue.

**Comment by abn** [comment]
@siddharthist my VMs are running on oVirt.
