### ISSUE TITLE
Info regarding accessing the hello-world App after install 

### ISSUE THREAD

**Issue by linuxbsdfreak** [CiscoCloud/microservices-infrastructure#588]
Hi,

I was able to provision the cluster via terraform on AWS successfully. Also i launched an app by running the below command 

examples/hello-world/launch.sh -c examples/hello-world/hello-world.json -m PubicIPofMarathonInstance -u <user> -p <pass>`

However i have the following question:

1. As per https://microservices-infrastructure.readthedocs.org/en/latest/components/haproxy.html I tried to access example.com by setting that in the /etc/hosts file to one of the worker nodes. But it doesnt work. I checked the worked nodes and saw that the following
docker ps

CONTAINER ID        IMAGE                                     COMMAND                CREATED             STATUS              PORTS                                                                      NAMES
ed1fea80ec08        keithchambers/docker-hello-world:latest   "/run.sh"              11 minutes ago      Up 11 minutes       0.0.0.0:31819->80/tcp                                                      mesos-8d65e4de-cb50-4824-afbc-f7171f7e265a   
9b7dd63907ec        keithchambers/docker-hello-world:latest   "/run.sh"              11 minutes ago      Up 11 minutes       0.0.0.0:31413->80/tcp                                                      mesos-8496d95d-3d26-4e5f-b85c-70f182924eef   
7f1460d9c437        ciscocloud/logstash:0.2                   "/usr/local/bin/star   29 minutes ago      Up 29 minutes       0.0.0.0:8125->8125/udp, 0.0.0.0:1514->1514/tcp, 0.0.0.0:25826->25826/udp   logstash                                     
8cf969117fb2        ciscocloud/haproxy-consul:0.2             "/launch.sh -ssl -ss   29 minutes ago      Up 29 minutes                                                                                  haproxy                                      
2ad7ad58d502        ciscocloud/nginx-consul:1.1               "/scripts/launch.sh"   29 minutes ago      Up 29 minutes           
                 
How do i access is via happroxy? Is there support for nginx as a LB in the pipeline.

2. Is there any plans to use a CI tool like jenkins etc launching a new app ?. Typically documented by the steps given below.

http://container-solutions.com/2015/03/continuous-delivery-with-docker-on-mesos-in-less-than-a-minute 
http://container-solutions.com/continuous-delivery-with-docker-on-mesos-in-less-than-a-minute-part-2/

Regards,
Kevin

**Comment by ryane** [comment]
Hi @linuxbsdfreak. RE: haproxy. We're testing a couple of haproxy fixes in https://github.com/CiscoCloud/microservices-infrastructure/pull/592. Since you are on AWS, you may just need to manually update your worker security group to allow HTTP/S traffic.

**Comment by linuxbsdfreak** [comment]
@Ryane. Thanks for the info.

**Comment by siddharthist** [comment]
@linuxbsdfreak Are you still experiencing this issue?
