### ISSUE TITLE
selinux preventing access to mesos sandbox in dockerized tasks

### ISSUE THREAD

**Issue by ryane** [CiscoCloud/microservices-infrastructure#613]
selinux is preventing access to the $MESOS_SANDBOX directory within dockerized mesos tasks. The docker containerizer maps the host's sandbox directory to $MESOS_SANDBOX (/mnt/mesos/sandbox) in the docker container. However, this directory is inaccessible within the container. This is preventing us from being able to run the the dcos spark package. This can be demonstrated with the following marathon app:

```json
{
  "container": {
    "type": "DOCKER",
    "docker": {
      "network": "BRIDGE",
      "image": "busybox"
    }
  },
  "id": "selinux-test",
  "instances": 1,
  "cpus": 0.1,
  "mem": 128,
  "cmd": "ls -al $MESOS_SANDBOX && while [ true ] ; do echo 'Hello selinux' ; sleep 5 ; done"
}
```

This app will always fail to start with the following error:

`ls: can't open '/mnt/mesos/sandbox': Permission denied`

If you turn off selinux enforcement (`setenforce 0`) the app will start and run successfully.

**Comment by nickvth** [comment]
Hello Ryan,

Maybe you can do semanage on host os, instead of disable selinux.

- name: Selinux managed mesos sandbox 
 command: /usr/sbin/semanage fcontext -a -t svirt_sandbox_file_t "/mnt/mesos/sandbox(/.*)?"

With Kind Regards,

Nick van ’t Hart

**Comment by ryane** [comment]
@nickvth right, the intent is not to disable selinux - I just included that to demonstrate the selinux is causing the issue. Thanks for the semanage command - I'll look into that

**Comment by ryane** [comment]
it turns out the docker upgrade in #597 appears to have fixed this

**Comment by ryane** [comment]
This problem is back. I'm not positive but I'm guessing it started after switching back to the centos docker package in #803.

**Comment by ryane** [comment]
selinux is also preventing some mesos frameworks (elasticsearch and arangodb, for example) from running. Mounting host volumes in marathon tasks are also being blocked.

**Comment by ryane** [comment]
It looks like this problem was introduced in #794 with this commit: https://github.com/CiscoCloud/microservices-infrastructure/commit/9bb17ad7968042abbe7736fa0bcd415f543bcdc9

@zogg was there a reason we re-enabled selinux in the docker daemon here?

afaict, it has not been enabled since 442198bac7bbee79452fff76df413a896a341915 in February from @stevendborrelli. `selinux-enabled` with the current docker version and selinux policy breaks some of our primary use cases: running containers, mesos frameworks, etc.

I think we should revert back to `--selinux-enabled=false` and open a new issue for proper docker selinux support - by either creating a custom policy or waiting for an updated docker-selinux package that works with Mantl.

Regardless, we need to make sure the [security docs](https://github.com/CiscoCloud/microservices-infrastructure/blob/master/docs/security/security.rst) reflect the current setting.

thoughts?

**Comment by stevendborrelli** [comment]
selinux causes too many problems right now. I think we need to disable it and review again once we test against Centos 7.2.
