### ISSUE TITLE
Mesos version is hardcoded in configuration

### ISSUE THREAD

**Issue by OleksandrBerchenko** [CiscoCloud/microservices-infrastructure#614]
In both `roles/mesos/templates/mesos-master.conf.j2` and `roles/mesos/templates/mesos-slave.conf.j2` we have a hardcoded version of Mesos:

Version "0.21.0"

At the same time we actually install the latest version of Mesos from the Mesosphere repository and it's already 0.23.0.

It's not a big deal to update our hardcoded version, but one day a new Mesos version can unexpectedly break the clusters.  It may be an issue for other external packages too (not only Mesos).

Probably it makes sense to specify exact versions for all the packages (or even to move them to our own repository).

Thanks.

**Comment by loshkovskyi** [comment]
+1

Same for Marathon. Right now with the `latest` tag we install `Mesos 0.23.0-1.0` and `Marathon 0.9.1-1`, but:

https://github.com/mesosphere/marathon/releases/tag/v0.9.1
```
Recommended Mesos version is 0.22.1

We tested this release against Mesos version 0.22.1.
Thus, this is the recommended Mesos version for this release.
```
There are [263 changes](https://github.com/apache/mesos/blob/0.23.0/CHANGELOG) in the latest Mesos, so better to avoid any problems.

**Comment by loshkovskyi** [comment]
@OleksandrBerchenko the configs, you are referring to, are related to the Mesos collectd plugin. So, the plugin should be updated as well. I'll update it and see how it works.

**Comment by loshkovskyi** [comment]
PR https://github.com/CiscoCloud/microservices-infrastructure/pull/618

**Comment by loshkovskyi** [comment]
@OleksandrBerchenko , the patch has been merged, please review when you are back to work and reopen this issue if necessary. Thank you.

**Comment by OleksandrBerchenko** [comment]
Looks good to me, thank you!
