### ISSUE TITLE
Support cluster auto healing from Atlas (TF)

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#62]

**Comment by keithchambers** [comment]
Auto Scaling discussion in the Mesos community:

http://www.mail-archive.com/user@mesos.apache.org/msg02684.html

http://www.slideshare.net/spodila/aws-reinvent-2014-talk-scheduling-using-apache-mesos-in-the-cloud

**Comment by stevendborrelli** [comment]
Atlas support is currently not on our roadmap.
