### ISSUE TITLE
Enhanced docker logs

### ISSUE THREAD

**Issue by tgermain** [CiscoCloud/microservices-infrastructure#621]
When a container is launch by Marathon, the logs it output are associated with the name of the container, something like `mesos-23d9e0ac-332c-42e8-b62b-3f9d488d3eb4`.

It would be useful to add information to those logs like which image/task it is. This will help to consolidate the logs coming from multiple instances of the same app.

I've write a logstash filter to do that : https://github.com/tgermain/logstash-filter-docker_metadata

This could go in the new logstash image, see : https://github.com/CiscoCloud/microservices-infrastructure/issues/596

**Comment by stevendborrelli** [comment]
This is a great idea.

**Comment by siddharthist** [comment]
Can we close this in favor of #646? It seems like whatever we end up doing will (hopefully) make this issue obsolete.
