### ISSUE TITLE
Common health checks

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/microservices-infrastructure#633]
We need health checks for more basic, MI-unrelated things. I'd like to see the following on every node:

 * CPU usage (<100%)
 * Disk usage (<90%)
 * Memory usage (<100%)
 * ~~`centos` user present~~

Does anybody else have any ideas?

**Comment by loshkovskyi** [comment]
Actually, user can be different, for example, in Cisco Cloud Services it can be `cloud-user` instead of `centos`.

**Comment by stevendborrelli** [comment]
We probably don't need to include the centos user check for mem/disk

**Comment by siddharthist** [comment]
@loshkovskyi Thanks for pointing that out, I'll make sure not to include that. @stevendborrelli Did you mean "*or* mem/disk"? Do you just want the CPU check?

**Comment by stevendborrelli** [comment]
I don't think user checks should be mixed with capacity checking. The centos user is an artifact of the OS  & Cloud platform, and memory & disk checks are more generic.

**Comment by jospaeth** [comment]
For capacity checking, I am currently checking the following additional items on all my worker nodes:
- conntrack table utilization
- filehandle utilization

I am also considering haproxy a part of the "platform/capacity checks" so we could consider:
haproxy maxconns vs current conns

**Comment by jospaeth** [comment]
A few more metrics for consideration:
- Number of containers spawned per hour could provide high level health metric of the cluster (i.e. VMs aren't dying, constantly being re-spawned, etc)
- IO throughput saturation (if appropriate ... this one may need to have user-configured thresholds)
- Number of TCP connections in various WAIT states (eg. CLOSE_WAIT, TIME_WAIT)

**Comment by stevendborrelli** [comment]
Moving to 0.6
