### ISSUE TITLE
Add default output for Logstash

### ISSUE THREAD

**Issue by loshkovskyi** [CiscoCloud/microservices-infrastructure#634]
As pointed out by @matjohn2 , we need to provide a reasonable default output for Logstash. Right now it set to be empty, that is we don't send logs and metrics anywhere. There are plenty of use cases for such setup. For example, it can help in troubleshooting of any issue with the M-I components or an application deployed on Marathon.

Some other keypoints:
- We should follow the M-I philosophy and keep it as simple as possible.
- GlusterFS support was recently merged, so we could use a volume to store logs (for example using ElasticSearch).
- Right now we start Logstash on each node. Maybe, it's a good idea to start one Logstash instance on top of Marathon and use shippers such as Logstash forwarder or fluentd to forward logs to that Logstash instance. It could be scaled by Marathon if there is such need. It will significantly speed up deployments, by the way.
- Add several predefined dashboards in Kibana or search for other alternative dashboards (related old issue: https://github.com/CiscoCloud/microservices-infrastructure/issues/55)

**Comment by cdmitri** [comment]
Andrii, please talk to the rest of the team that are working on this on
dcos and follow the same strategy. Destination can change, but should be
same logstash containers and config methods everywhere. If there are
arguments to chandelier and enhance, that's great of course, but need to be
completely in sync and not do it 5 different ways :)

**Comment by stevendborrelli** [comment]
@loshkovskyi I agree. We could use a lightweight agent on each box. We've seen a lot of issues where logstash is filling up the /var/lib/docker filesystem on nodes. 

I'd like to see the logging get more modular, with defaults being we run a useful ELK ( or similar stack) by default tha. 

For example: 
- enable logstash forwarder (https://github.com/elastic/logstash-forwarder)
- configure logstash forwarder: logstash running on marathon or external logstash
- fluentd to logstash
- fluentd to external
- etc.

**Comment by cdmitri** [comment]
@stevenborelli the reason stuff was filling up was just yesterday for
debugging. Well turn it off. There is actually a logstash framework that we
are finalizing that we can run also, will see if that's better. We're doing
kibana and zoomdata dashboards for central shipped analytics, once those
are done, in a couple of days we can leverage. ES also...testing those,
once done will integrate into mantl.
