### ISSUE TITLE
Mesos Framework integration with microservices-infrastructure

### ISSUE THREAD

**Issue by tpowell-rms** [CiscoCloud/microservices-infrastructure#640]
It seems Mesos Frameworks can not be dropped into the microservices-infrastructure unmodified. Is this the case? http://microservices-infrastructure.readthedocs.org/en/latest/roadmap.html#mesos-frameworks
I don't see any documentation on what needs to be done to retrofit a framework on the platform.

Or am I looking in the wrong place?

**Comment by eirslett** [comment]
Marathon is running in microservices-infrastructure:

From https://github.com/mesosphere/marathon:
> Marathon is a meta framework: you can start other Mesos frameworks such as Chronos or Storm with it to ensure they survive machine failures. It can launch anything that can be launched in a standard shell. In fact, you can even start other Marathon instances via Marathon.

So one option is to start your framework as a Marathon task.

**Comment by tpowell-rms** [comment]
@eirslett  Is that suggested method? Frameworks do not need to be modified? Looking at the docs, the impression is they need modification.. or I would assume all the frameworks would be checked off on the page.

**Comment by stevendborrelli** [comment]
@tpowell-rms the goal is to use mesosphere universe packaging with the dcos command line (which might have to be modified). I'm not sure what you mean about retrofitting frameworks.

**Comment by tpowell-rms** [comment]
This page list several frameworks.... http://microservices-infrastructure.readthedocs.org/en/latest/roadmap.html#mesos-frameworks   that are on the RoadMap.  The assumption is , you can not use them today with microservices-infrastructure . Is this correct? 

If that is correct, why is this? Do Frameworks need modification before I run them on microservices-infrastructure with mesos.   As these frameworks already run just fine with mesos alone.

**Comment by stevendborrelli** [comment]
Any framework that runs on Mesos should run fine. One issue you might run into is certain frameworks don't support authentication, so in the security setup script there is an option to disable mesos authentication.

**Comment by cdmitri** [comment]
Trevor - we have several frameworks that were co-written by us and
partners. We'll be testing integration with microservices-infrastructure
right after MesosCon, perhaps you can help - thanks for raising this!

Any framework that runs on Mesos should run fine. One issue you might run
into is certain frameworks don't support authentication, so in the security
setup script there is an option to disable mesos authentication.

—
Reply to this email directly or view it on GitHub
<https://github.com/CiscoCloud/microservices-infrastructure/issues/640#issuecomment-131265621>
.

**Comment by tpowell-rms** [comment]
Ah I see.

Do you have any indication why this page shows other frameworks are unsupported? 
http://microservices-infrastructure.readthedocs.org/en/latest/roadmap.html#mesos-frameworks

It seems to show Spark, Storm, Chronos are not working on the product yet.

**Comment by tpowell-rms** [comment]
I talked to @stevendborrelli   ; That page is for frameworks that will be including in the future as part of the project.
