### ISSUE TITLE
Vagrant environment failing to start due to docker version conflict

### ISSUE THREAD

**Issue by SillyMoo** [CiscoCloud/microservices-infrastructure#641]
Hi, whilst running up the vagrant environment I get the failure shown below. This seems to be a conflict in versions between the pre-installed docker version in the vagrant box and the official 'docker-engine' version being installed.

FYI, I have a fix, pull request incoming.

The error:

==> default: TASK: [docker | install docker packages] **************************************
==> default: failed: [default] => (item=docker-engine-1.7.0,docker-selinux) => {"changed": true, "item": "docker-engine-1.7.0,docker-selinux", "rc": 1, "results": ["docker-selinux-1.6.0-11.0.1.el7.centos.x86_64 providing docker-selinux is already installed", "Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * epel: mirrors.syringanetworks.net\nResolving Dependencies\n--> Running transaction check\n---> Package docker-engine.x86_64 0:1.7.0-1.el7.centos will be installed\n--> Processing Dependency: libpthread.so.0 for package: docker-engine-1.7.0-1.el7.centos.x86_64\n--> Processing Dependency: libsqlite3.so.0 for package: docker-engine-1.7.0-1.el7.centos.x86_64\n--> Running transaction check\n---> Package glibc.i686 0:2.17-78.el7 will be installed\n--> Processing Dependency: libfreebl3.so(NSSRAWHASH_3.12.3) for package: glibc-2.17-78.el7.i686\n--> Processing Dependency: libfreebl3.so for package: glibc-2.17-78.el7.i686\n---> Package sqlite.i686 0:3.7.17-4.el7 will be installed\n--> Processing Dependency: libtinfo.so.5 for package: sqlite-3.7.17-4.el7.i686\n--> Processing Dependency: libreadline.so.6 for package: sqlite-3.7.17-4.el7.i686\n--> Processing Dependency: libncurses.so.5 for package: sqlite-3.7.17-4.el7.i686\n--> Running transaction check\n---> Package ncurses-libs.i686 0:5.9-13.20130511.el7 will be installed\n--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4) for package: ncurses-libs-5.9-13.20130511.el7.i686\n--> Processing Dependency: libstdc++.so.6(CXXABI_1.3) for package: ncurses-libs-5.9-13.20130511.el7.i686\n--> Processing Dependency: libstdc++.so.6 for package: ncurses-libs-5.9-13.20130511.el7.i686\n--> Processing Dependency: libgcc_s.so.1(GCC_3.0) for package: ncurses-libs-5.9-13.20130511.el7.i686\n--> Processing Dependency: libgcc_s.so.1 for package: ncurses-libs-5.9-13.20130511.el7.i686\n---> Package nss-softokn-freebl.x86_64 0:3.16.2.3-9.el7 will be updated\n---> Package nss-softokn-freebl.i686 0:3.16.2.3-12.el7_1 will be installed\n---> Package nss-softokn-freebl.x86_64 0:3.16.2.3-12.el7_1 will be an update\n---> Package readline.i686 0:6.2-9.el7 will be installed\n--> Running transaction check\n---> Package libgcc.i686 0:4.8.3-9.el7 will be installed\n---> Package libstdc++.i686 0:4.8.3-9.el7 will be installed\n--> Processing Conflict: docker-engine-1.7.0-1.el7.centos.x86_64 conflicts docker\n--> Restarting Dependency Resolution with new changes.\n--> Running transaction check\n---> Package docker.x86_64 0:1.6.0-11.0.1.el7.centos will be updated\n---> Package docker.x86_64 0:1.7.1-108.el7.centos will be an update\n--> Processing Dependency: lvm2 >= 2.02.112 for package: docker-1.7.1-108.el7.centos.x86_64\n--> Processing Dependency: docker-selinux >= 1.7.1-108.el7.centos for package: docker-1.7.1-108.el7.centos.x86_64\n--> Running transaction check\n---> Package docker-selinux.x86_64 0:1.6.0-11.0.1.el7.centos will be updated\n---> Package docker-selinux.x86_64 0:1.7.1-108.el7.centos will be an update\n---> Package lvm2.x86_64 7:2.02.115-3.el7_1.1 will be installed\n--> Processing Dependency: lvm2-libs = 7:2.02.115-3.el7_1.1 for package: 7:lvm2-2.02.115-3.el7_1.1.x86_64\n--> Processing Dependency: device-mapper-persistent-data >= 0.3.2-1 for package: 7:lvm2-2.02.115-3.el7_1.1.x86_64\n--> Processing Dependency: liblvm2app.so.2.2(Base)(64bit) for package: 7:lvm2-2.02.115-3.el7_1.1.x86_64\n--> Processing Dependency: libdevmapper-event.so.1.02(Base)(64bit) for package: 7:lvm2-2.02.115-3.el7_1.1.x86_64\n--> Processing Dependency: liblvm2app.so.2.2()(64bit) for package: 7:lvm2-2.02.115-3.el7_1.1.x86_64\n--> Processing Dependency: libdevmapper-event.so.1.02()(64bit) for package: 7:lvm2-2.02.115-3.el7_1.1.x86_64\n--> Running transaction check\n---> Package device-mapper-event-libs.x86_64 7:1.02.93-3.el7_1.1 will be installed\n---> Package device-mapper-persistent-data.x86_64 0:0.4.1-2.el7 will be installed\n--> Processing Dependency: libaio.so.1(LIBAIO_0.4)(64bit) for package: device-mapper-persistent-data-0.4.1-2.el7.x86_64\n--> Processing Dependency: libaio.so.1(LIBAIO_0.1)(64bit) for package: device-mapper-persistent-data-0.4.1-2.el7.x86_64\n--> Processing Dependency: libaio.so.1()(64bit) for package: device-mapper-persistent-data-0.4.1-2.el7.x86_64\n---> Package lvm2-libs.x86_64 7:2.02.115-3.el7_1.1 will be installed\n--> Processing Dependency: device-mapper-event = 7:1.02.93-3.el7_1.1 for package: 7:lvm2-libs-2.02.115-3.el7_1.1.x86_64\n--> Running transaction check\n---> Package device-mapper-event.x86_64 7:1.02.93-3.el7_1.1 will be installed\n---> Package libaio.x86_64 0:0.3.109-12.el7 will be installed\n--> Processing Conflict: docker-engine-1.7.0-1.el7.centos.x86_64 conflicts docker\n--> Processing Conflict: docker-engine-1.7.0-1.el7.centos.x86_64 conflicts docker-io\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\n"]}
==> default: msg: Error: docker-engine conflicts with docker-1.7.1-108.el7.centos.x86_64

**Comment by SillyMoo** [comment]
Pull request: https://github.com/CiscoCloud/microservices-infrastructure/pull/642

**Comment by ryane** [comment]
What version of the CiscoCloud/microservices-infrastructure vagrant image do you currently have installed (run `vagrant box list`)? We recently published a new version that should address this problem without having to uninstall/reinstall docker. The latest image is

`CiscoCloud/microservices-infrastructure (virtualbox, 0.5)`

**Comment by SillyMoo** [comment]
Ahh, I have 04.24.2015. Looks like I need to update. I shall abandon the pull request.

**Comment by SillyMoo** [comment]
Oh, but if I try to update it does not work:

vagrant box update
==> default: Checking for updates to 'CiscoCloud/microservices-infrastructure'
    default: Latest installed version: 04.24.2015
    default: Version constraints:
    default: Provider: virtualbox
==> default: Box 'CiscoCloud/microservices-infrastructure' (v04.24.2015) is running the latest version.

vagrant box outdated
Checking if box 'CiscoCloud/microservices-infrastructure' is up to date...

**Comment by SillyMoo** [comment]
Odd, I removed and re-added the box and now I have version 0.5. But a box update failed to work. Never mind not a microservices bug either way, so issue and pull request can be closed.
