### ISSUE TITLE
Investigate integration of kubernetes-ansible for Container Workloads

### ISSUE THREAD

**Issue by PeterLamar** [CiscoCloud/microservices-infrastructure#643]
Investigate integration of kubernetes-ansible for Container Workloads, deployed not as a framework but integrated with the MI architecture. 

Kubernetes is continuing to gather momentum around container based workloads. It has several unique features that make it attractive in this usecase
1. IP per Container
2. Pod organization of containers
3. 2 dozen+ [examples](https://github.com/kubernetes/kubernetes/tree/master/examples)
4. [Pluggable architecture](https://github.com/kubernetes/kubernetes/blob/fd7a48f379fd4f6b0779bdc6db1efb625b1a24d8/docs/design/architecture.md)
5. Built-in [Monitoring](https://github.com/kubernetes/kubernetes/blob/fd7a48f379fd4f6b0779bdc6db1efb625b1a24d8/docs/user-guide/monitoring.md)
6. Extremely fast velocity with [30+ active contributing developers](https://github.com/kubernetes/kubernetes/graphs/contributors)
7. [Cloud Native Computing Foundation](https://cncf.io/)
8. Version '1.0' status
9. Built in Go, works easier with Go Tooling
10. Support for Identity and access [control](https://github.com/kubernetes/kubernetes/blob/master/docs/design/access.md)
11. Forward looking proposals for [federation](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/federation.md)

**Comment by PeterLamar** [comment]
As a user, I can deploy Kubernetes from an ansible role in Mantl so that Kubernetes is a deployment option

Acceptance Criteria

Kubernetes is successfully deployed

**Comment by ryane** [comment]
a standalone Kubernetes playbook was added with #794. will open new issues to more tightly integrate kubernetes and for any problems or enhancements we identify

**Comment by PeterLamar** [comment]
Thanks Ryan! FYI @loshkovskyi @altvnk
