### ISSUE TITLE
Stopping consul server stops nginx-consul as well

### ISSUE THREAD

**Issue by saswatp** [CiscoCloud/microservices-infrastructure#652]
If I manually stop consul service in a control node , nginx-consul gets into failed state.
After consul starts again , it is not accessible through the UI interface as the proxy is unavailable.

Stopping Consul shouldn't fail nginx-consul. 

Logs
------

Aug 18 21:13:32 pb-control-01.cisco.com docker[29589]: }
Aug 18 21:13:32 pb-control-01.cisco.com docker[29589]: }
Aug 18 21:13:32 pb-control-01.cisco.com docker[29589]: }
Aug 18 21:13:32 pb-control-01.cisco.com docker[29589]: 2015/08/18 21:13:32 [DEBUG] (view) "key(service/nginx/templates/consul)" no new data (index was the same)
Aug 18 21:13:32 pb-control-01.cisco.com docker[29589]: 2015/08/18 21:13:32 [DEBUG] ("key(service/nginx/templates/consul)") querying consul with &{Datacenter: AllowStale:false RequireConsist...1m0s Token:}
Aug 18 21:13:34 pb-control-01.cisco.com docker[29589]: 2015/08/18 21:13:34 [DEBUG] ("storeKeyPrefix(service/nginx/auth/users)") Consul returned 1 key pairs
Aug 18 21:13:34 pb-control-01.cisco.com docker[29589]: 2015/08/18 21:13:34 [DEBUG] (view) "storeKeyPrefix(service/nginx/auth/users)" no new data (index was the same)
Aug 18 21:13:34 pb-control-01.cisco.com docker[29589]: 2015/08/18 21:13:34 [DEBUG] ("storeKeyPrefix(service/nginx/auth/users)") querying Consul with &{Datacenter: AllowStale:false RequireCo...1m0s Token:}
Aug 18 21:14:23 pb-control-01.cisco.com systemd[1]: Stopping nginx-consul...
Aug 18 21:14:23 pb-control-01.cisco.com docker[30259]: nginx-consul
Aug 18 21:14:25 pb-control-01.cisco.com systemd[1]: nginx-consul.service: main process exited, code=exited, status=137/n/a
Aug 18 21:14:25 pb-control-01.cisco.com systemd[1]: Stopped nginx-consul.
Aug 18 21:14:25 pb-control-01.cisco.com systemd[1]: Unit nginx-consul.service entered failed state.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by ChrisAubuchon** [comment]
Check out PR https://github.com/CiscoCloud/microservices-infrastructure/pull/654

**Comment by ryane** [comment]
fixed in #654
