### ISSUE TITLE
site.yml could not be found

### ISSUE THREAD

**Issue by eebjr** [CiscoCloud/microservices-infrastructure#664]
While attempting a deployment using the Docker container I'm getting an error: $ docker run -it -e SSH_KEY=/home/centos/.ssh/mi.key -v ~/.ssh/:/ssh/ -v $PWD:/state mi
ERROR: the playbook: site.yml could not be found
The web site doesn't mention this site.yml file, and there's not an example file.

**Comment by kenjones-cisco** [comment]
Did you remember to copy the `terraform.sample.yml` to `terraform.yml` (that is the playbook/site that is executed by default) before building the docker image?
```
cp terraform.sample.yml terraform.yml
```

**Comment by eebjr** [comment]
I didn't, have the terraform.yml setup. I've moved a little farther down the road now. I was trying the docker method, because I was blocked. I'll try it again later.
