### ISSUE TITLE
Combine "short_name" and "datacenter"

### ISSUE THREAD

**Issue by eirslett** [CiscoCloud/microservices-infrastructure#665]
The "datacenter" variable isn't used for many things as it is now. How about letting short_name = datacenter?
In a default setup, the datacenter would then be called "mi".
With 2 centers, you could have "mi0" and "mi1".
With multiple environments, maybe "prod0" and "prod1" etc.?

**Comment by BrianHicks** [comment]
I like that idea! I wish we could do that in Terraform, but since we can't reference variables in definitions for other variables, we're left having to overspecify. It's worth revisiting if/when Terraform allows this kind of behavior, but I'm going to close this for now.

**Comment by eirslett** [comment]
We should be able to do this with .tfvars (which should be used anyways?)
And we don't really need to say `datacenter = "${var.short_name}"` in the terraform code, we could just use short_name everywhere and get rid of the "datacenter" variable altogether.
