### ISSUE TITLE
Configure stale reads in dns? 

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#667]
If there is a consul leader election dns will be unavailable by default, which could cause outages.

https://www.consul.io/docs/guides/dns-cache.html

Options: 
1) set dns_config.allow_stale in the consul config, plus x number of seconds for stale dns reads
2) set a cache on the dnsmasq 
3) ??

**Comment by eirslett** [comment]
How about allowing stale reads in consul for everything? (Including the k/v store)
It could be allowed by default and disabled by overriding an ansible variable?

**Comment by stevendborrelli** [comment]
@eirslett sounds good, we'll add this to the 0.4 release.

**Comment by stevendborrelli** [comment]
Pushing to 0.5

**Comment by siddharthist** [comment]
Bad news: with the naive solution,
```
$ git diff HEAD
diff --git a/roles/consul/defaults/main.yml b/roles/consul/defaults/main.yml
index 02e1479..df498ca 100644
--- a/roles/consul/defaults/main.yml
+++ b/roles/consul/defaults/main.yml
@@ -17,3 +17,5 @@ consul_acl_down_policy: "allow"
 consul_dns_domain: consul
 consul_verify_incoming: true
 consul_verify_outgoing: true
+consul_allow_stale: true
+consul_max_stale: "5s"
diff --git a/roles/consul/templates/consul.json.j2 b/roles/consul/templates/consul.json.j2
index ded5ad9..ee72793 100644
--- a/roles/consul/templates/consul.json.j2
+++ b/roles/consul/templates/consul.json.j2
@@ -25,5 +25,9 @@
   "disable_remote_exec": {{ consul_disable_remote_exec|to_nice_json }},
   "http_api_response_headers": {
     "Access-Control-Allow-Origin": "*"
+  },
+  "dns_config": {
+    "allow_stale": {{ consul_allow_stale|to_nice_json }},
+    "max_stale": {{ consul_max_stale }}
   }
 }
```
Consul leader election fails on GCE and AWS.

**Comment by eirslett** [comment]
Maybe
```
-    "max_stale": {{ consul_max_stale }}
+    "max_stale": "{{ consul_max_stale }}"
```

helps?

**Comment by siddharthist** [comment]
Turns out, "5s" is not a valid value. Will try an integer next.
```
Nov 11 03:30:08 lb-mi-control-02.c.asteris-mi.internal consul[8538]: ==> Error decoding '/etc/consul/consul.json': invalid character 's' after object key:value pair
```

**Comment by sehqlr** [comment]
'5s' is not an int? The more you know ;p

**Comment by eirslett** [comment]
https://www.consul.io/docs/agent/options.html
> max_stale When allow_stale is specified, this is used to limit how stale results are allowed to be. By default, this is set to "5s": if a Consul server is more than 5 seconds behind the leader, the query will be re-evaluated on the leader to get more up-to-date results.

Might be a bug in the docs?

**Comment by siddharthist** [comment]
@eirslett I think you're probably right in that it's a quoting issue. I'm currently retrying with the fix. That is also more consistent with our other values in Ansible.

**Comment by siddharthist** [comment]
I think that solution is working, but I can't fully test because I'm running into LVM issues. Will update when I can finish testing.
