### ISSUE TITLE
Vagrant up gives box could not be found error

### ISSUE THREAD

**Issue by deepagargit** [CiscoCloud/microservices-infrastructure#672]
Please suggest what is missing

The github has Vagrant file vm box as "CiscoCloud/microservices-infrastructure".
How could I get the "CiscoCloud/microservices-infrastructure" vm box?

config.vm.box = "CiscoCloud/microservices-infrastructure"

sfuser@microservices:~/github/microservices-infrastructure$ sudo pip install -r requirements.txt
 
sfuser@microservices:~/github/microservices-infrastructure$ ./security-setup

sfuser@microservices:~/github/microservices-infrastructure$ pwd
/home/sfuser/github/microservices-infrastructure
sfuser@microservices:~/github/microservices-infrastructure$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The box 'CiscoCloud/microservices-infrastructure' could not be found.

sfuser@microservices:~/github/microservices-infrastructure$ cat /etc/hostname
microservices

sfuser@microservices:~/github/microservices-infrastructure$ vagrant -v
Vagrant 1.4.3

sfuser@microservices:~/github/microservices-infrastructure$ virtualbox --help
Oracle VM VirtualBox Manager 4.3.10_Ubuntu
(C) 2005-2015 Oracle Corporation
All rights reserved.

**Comment by mikejihbe** [comment]
I also noticed that the latest version of virtualbox doesn't work (5.*)

On Mon, Aug 31, 2015 at 2:22 AM, deepagargit <notifications@github.com>
wrote:

> Please suggest what is missing
>
> sfuser@microservices:~/github/microservices-infrastructure$ sudo pip
> install -r requirements.txt
>
> sfuser@microservices:~/github/microservices-infrastructure$
> ./security-setup
>
> sfuser@microservices:~/github/microservices-infrastructure$ pwd
> /home/sfuser/github/microservices-infrastructure
> sfuser@microservices:~/github/microservices-infrastructure$ vagrant up
> Bringing machine 'default' up with 'virtualbox' provider...
> There are errors in the configuration of this machine. Please fix
> the following errors and try again:
>
> vm:
>
>    - The box 'CiscoCloud/microservices-infrastructure' could not be found.
>
> sfuser@microservices:~/github/microservices-infrastructure$ virtualbox
> --help
> Oracle VM VirtualBox Manager 4.3.10_Ubuntu
> (C) 2005-2015 Oracle Corporation
> All rights reserved.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CiscoCloud/microservices-infrastructure/issues/672>.
>



-- 
Mike Ihbe
MustWin - Principal

mike@mustwin.com
mikejihbe@gmail.com
skype: mikeihbe
Cell: 651.283.0815

**Comment by stevendborrelli** [comment]
@deepagargit could you upgrade your vagrant to the newest version? 1.7.4 is the newest version, and versions older than 1.7 might have issues with the networking.

**Comment by stevendborrelli** [comment]
@mikejihbe what issue are you seeing? I'll upgrade my box to 5.x and test.

**Comment by mikejihbe** [comment]
With Vbox 5.0:

```
➜  microservices-infrastructure git:(master) vagrant up --provider=virtualbox                                                                         (master⚡)
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported. Please install one of the supported versions
listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3
```

**Comment by stevendborrelli** [comment]
@mikejihbe what version of vagrant are you using?

**Comment by mikejihbe** [comment]
```
➜  microservices-infrastructure git:(master) vagrant --version                                                                                                                        (master⚡)
Vagrant 1.7.2
```

**Comment by deepagargit** [comment]
I have got this issue fixed by upgrading the valgrant and virtualbox versions.

Thanks for the help.
