### ISSUE TITLE
Why zookeeper when consul is there?

### ISSUE THREAD

**Issue by nmabhinandan** [CiscoCloud/microservices-infrastructure#673]

**Comment by eirslett** [comment]
Because Mesos uses ZooKeeper.

**Comment by nmabhinandan** [comment]
Oh. okay
![okay-face](https://cloud.githubusercontent.com/assets/1548848/9580564/eb7dc942-5017-11e5-80d3-ba92d359bf55.jpg)

**Comment by stevendborrelli** [comment]
Many big data components use Zookeeper for coordination, and it's unlikely they will be ported to other systems in the next year or so. 

We're really looking at 3 consensus systems right now in mantl:
  
Zookeeper: mesos, kafka, etc. 
consul: mantl's main service discovery backend
etcd: kubernetes, weave, calico

Of the 3, the migration between consul <-> etcd is probably easiest, but there are still some issues.

**Comment by nmabhinandan** [comment]
Consul is better for everyone in every angle IMO. Hope they would migrate soon.

**Comment by eirslett** [comment]
I think we're stuck with all 3 systems for the future...

**Comment by fire** [comment]
Are you familiar with https://github.com/glerchundi/parkeeper ? It emulates the zookeeper api.

**Comment by fire** [comment]
https://github.com/kubernetes/kubernetes/pull/26310 is a recent attempt at consul for kubernetes

**Comment by benschumacher** [comment]
> kubernetes/kubernetes#26310 is a recent attempt at consul for kubernetes

That pull request is a side effect of our efforts in Mantl. Not sure how soon we'd be able to schedule an attempt to replace Zookeeper w/Consul in Mesos, but we're working on the community effort to give another option for Kubernetes.

**Comment by stevendborrelli** [comment]
parkeeper hasn't been updated in over a year. 

Another thing to consider is that the zookeeper api is rather complex, and the java/c client libs have been around for a long time (and are still somewhat buggy). Right now we don't have the bandwidth to address corner cases that using a wrapper lib around zk would introduce. 

I'm going to close this issue. As @benschumacher indicated, we will support k8s using consul first in Mantl.
