### ISSUE TITLE
Timeout issue with marathon-wait-for-listen.sh on underpowered control node

### ISSUE THREAD

**Issue by chrholme** [CiscoCloud/microservices-infrastructure#675]
When I spun my test cluster I ran into an issue with marathon-wait-for-listen.sh timing out.  My control node was relatively under powered (t2-small in AWS).  I found that 60s wasn't long enough.  I changed the timeout to 300s and was able to get passed this.  Perhaps a longer timeout would be worth adding to help out all us poor folks playing with small instances.

**Comment by stevendborrelli** [comment]
@chrholme do you think 120 seconds as in pull #659 would be sufficient?

**Comment by chrholme** [comment]
I'd have to check but my guess is that that would be perfectly fine.  :)

**Comment by stevendborrelli** [comment]
Closing with the merge of #659. Reopen if it is too short.
