### ISSUE TITLE
Unable to install on openstack - ansible

### ISSUE THREAD

**Issue by subbu05** [CiscoCloud/microservices-infrastructure#684]
When I run with 
ansible-playbook -i plugins/inventory/terraform.py -e @security.yml terraform.yml
I get following error.

failed: [subbu_mi-worker-01] => {"changed": true, "cmd": ["/usr/local/bin/consul-acl-bootstrap.sh", "fc10cc5a-33b5-42e7-b36d-3f32cea0a45b", "0a230be5-1a22-447f-9b35-f8adf2151e83"], "delta": "0:00:00.010865", "end": "2015-09-03 23:52:37.731259", "rc": 1, "start": "2015-09-03 23:52:37.720394", "warnings": []}
stderr: Unexpected response code: 500 (rpc error: No path to datacenter)

FATAL: all hosts have already failed -- aborting

I used default yml file provided, how to fix datacenter issue in the yml file?

**Comment by subbu05** [comment]
no clear document / help.

**Comment by subbu05** [comment]
Need more documentation / help how to use it.

**Comment by eirslett** [comment]
It's a little invisible gotcha: https://github.com/CiscoCloud/microservices-infrastructure/blob/master/terraform.sample.yml#L26
Comment out the line `consul_acl_datacenter`. Unless you have multiple datacenters that are supposed to communicate, in case you can point that variable to the name of the primary datacenter.
