### ISSUE TITLE
run distributive consul test fails - appears to be distributive version issue

### ISSUE THREAD

**Issue by kbroughton** [CiscoCloud/microservices-infrastructure#686]
TASK: [consul | run distributive consul test] ********************************* 
<127.0.0.1> 
<127.0.0.1> --verbosity=info
<127.0.0.1> IdentityFile=/Users/kestenbroughton/projects/mantl/.vagrant/machines/default/virtualbox/private_key ConnectTimeout=10 PasswordAuthentication=no KbdInteractiveAuthentication=no User=vagrant ControlPath=/Users/kestenbroughton/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey StrictHostKeyChecking=no ControlMaster=auto Port=2222 ControlPersist=60s
<127.0.0.1> 
<127.0.0.1> IdentityFile=/Users/kestenbroughton/projects/mantl/.vagrant/machines/default/virtualbox/private_key ConnectTimeout=10 'sudo -k && sudo -H -S -p "[sudo via ansible, key=shtdsnxxuzshdxjdxtvobilhahdwpota] password: " -u root /bin/sh -c '"'"'echo SUDO-SUCCESS-shtdsnxxuzshdxjdxtvobilhahdwpota; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1441340785.37-275394462027244/command; rm -rf /home/vagrant/.ansible/tmp/ansible-tmp-1441340785.37-275394462027244/ >/dev/null 2>&1'"'"'' PasswordAuthentication=no KbdInteractiveAuthentication=no User=vagrant ControlPath=/Users/kestenbroughton/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey StrictHostKeyChecking=no ControlMaster=auto Port=2222 ControlPersist=60s
failed: [127.0.0.1] => {"changed": true, "cmd": ["/usr/bin/distributive", "-f", "/etc/distributive.d/consul.json", "--verbosity=info"], "delta": "0:00:00.003788", "end": "2015-09-03 22:31:15.695460", "rc": 2, "start": "2015-09-03 22:31:15.691672", "warnings": []}
stderr: flag provided but not defined: -verbosity
Usage of /usr/bin/distributive:
  -a="/etc/distributive.d/": Run all the checks in the specified directory
  -f="": Use the health check located at this path
  -log-level="warn": Output verbosity level (valid values are info | debug | fatal | error | panic | warn
  -u="": Use the health check located at this URL
  -version=false: Get the version of distributive this binary was built from

FATAL: all hosts have already failed -- aborting

It looks to me like this is a version issue, but yum upgrade distributive fails and I can't find any way to find more recent rpms.

**Comment by siddharthist** [comment]
Cisco has a [Bintray page](https://bintray.com/ciscocloud/rpm/Distributive/view) from which we pull the distributive RPMs, as you can see [here](https://github.com/CiscoCloud/microservices-infrastructure/blob/50a5131bf30eb0a79868efa7fb42a800932dc733/roles/common/tasks/main.yml#L78). If you suspect you're downloading an old version, that's a good line to check. 

You can also create your own RPMs with [distributive-rpm](https://github.com/CiscoCloud/distributive-rpm).

**Comment by kbroughton** [comment]
Not sure how, but I had distributive 0.1.1 installed on the vagrant vm after running vagrant up.
Perhaps you can check if you can reproduce with the current master or latest tagged branch

[vagrant@default ~]$ yum info distributive
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: linux.cc.lehigh.edu
 * epel: ftp.cse.buffalo.edu
 * extras: mirror.pac-12.org
 * updates: mirror.millry.co
Installed Packages
Name        : distributive
Arch        : x86_64
Version     : 0.1.2
Release     : 1.el7.centos
Size        : 5.7 M
Repo        : installed
From repo   : /distributive-0.1.2-1.el7.centos.x86_64
Summary     : Distributive was designed with Consul in mind to perform distributed health checks in datacenters
URL         : https://github.com/CiscoCloud/distributive
License     : ASL 2.0:
Description : Distributive is a tool for running distributed health checks in datacenters. It was designed with Consul in mind, but is
            : platform agnostic. It is simple to configure (with JSON checklists) and easy to deploy and run. It has no dependencies, and can
            : be shipped as a speedy 4MB (yes, megabytes!) binary.

I was able to resolve this with

sudo yum -y remove distributive
sudo yum install https://bintray.com/artifact/download/ciscocloud/rpm/distributive-0.2.1-5.el7.centos.x86_64.rpm

Which is exactly what the ansible task is doing, so not sure why it didn't work out of the box.

You may close this ticket.

**Comment by siddharthist** [comment]
I can't reproduce with Vagrant+master. Using `yum info` reports the latest version. Glad it worked out for you!
