### ISSUE TITLE
MI platform-support for Linux Ubuntu\CentOS

### ISSUE THREAD

**Issue by deepagargit** [CiscoCloud/microservices-infrastructure#687]
Hello,

I have below 3 queries. Please add your inputs.

1. Is MI platform supported for Linux Ubuntu\CentOS ?

------------------------------------------------------------------------------------------------------
The Roadmap has this listed. 
 Vagrant (Linux + VirtualBox) http://microservices-infrastructure.readthedocs.org/en/latest/roadmap.html

The Git page doesnot have Linux support listed in "Platform Support" section.
https://github.com/CiscoCloud/microservices-infrastructure

------------------------------------------------------------------------------------------------------

When I executed provision.sh standalone on CentOS VM, It asked for admin password for nginx, 
2. Is this password prompt the reason "vagrant up" is timeout as it might be waiting for admin-password for nginx,?

------------------------------------------------------------------------------------------------------

I am getting below error on CentOS VM, and error continues after increasing timeout also.
3. Is there any known workaround for this error?
---------------------------------------------------------------------------------------------

[@default microservices-infrastructure]$ sudo vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'CiscoCloud/microservices-infrastructure'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'CiscoCloud/microservices-infrastructure' is up to date...
==> default: Setting the name of the VM: microservices-infrastructure_default_1441528211044_51091
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

**Comment by eirslett** [comment]
1) Mi runs on Linux/CentOS. It doesn't run on Ubuntu (which is a different Linux distro than CentOS) because of differences in the ecosystem, like for example the `yum` package manager, which is used by MI.

2) The nginx password prompt is run as part of the security-setup script, which generates various secrets, public/private keys and certificates for MI. You can run that on beforehand (`./security-setup`) and it will generate a file `security.yml` for you. I haven't used the Vagrant stuff yet, but I believe it will then use the existing `security.yml` and not create a new one.

**Comment by deepagargit** [comment]
Thanks!

I am getting below error over centos-se linux.
Please suggest what is missing?

[@default microservices-infrastructure]$ cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)


#Vagrantfile
  # Prefer VirtualBox before VMware Fusion
  config.vm.provider "virtualbox"
#  config.vm.provider "vmware_fusion" 

---------------------------------------------------------------------------------------------------------------------

[@default microservices-infrastructure]$ ls
ansible.cfg    docker_launch.sh  LICENSE              packer     README.md         security-setup     ssl                   vagrant
CHANGELOG.rst  docs              mantl-logo-1.png     playbooks  requirements.txt  security.yml       terraform             Vagrantfile
Dockerfile     examples          mantl-rename-faq.md  plugins    roles             security.yml.orig  terraform.sample.yml  vagrant.yml

-----------------------------------------------------------------------------------------------------------------

[@default microservices-infrastructure]$ sudo vagrant up


Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'CiscoCloud/microservices-infrastructure'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'CiscoCloud/microservices-infrastructure' is up to date...
==> default: Setting the name of the VM: microservices-infrastructure_default_1441528211044_51091
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.



--------------------------------------------------------------------------------------------------------------

[cisco@default microservices-infrastructure]$ cat Vagrantfile
# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'yaml'

def load_security
  fname = File.join(File.dirname(__FILE__), "security.yml")
  if !File.exist? fname
    $stderr.puts "security.yml not found - please run `./security-setup` and try again."
    exit 1
  end

  YAML.load_file(fname)
end

VAGRANT_PRIVATE_IP = "192.168.242.55"

Vagrant.configure(2) do |config|

  # Prefer VirtualBox before VMware Fusion
  config.vm.provider "virtualbox"
#  config.vm.provider "vmware_fusion"

  config.vm.box = "CiscoCloud/microservices-infrastructure"

  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.network "private_network", :ip => VAGRANT_PRIVATE_IP

  config.vm.provision "shell" do |s|
    s.path = "vagrant/provision.sh"
    s.args = VAGRANT_PRIVATE_IP
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--cpus', 1]
    vb.customize ['modifyvm', :id, '--memory', 1536]
  end
end

**Comment by ryane** [comment]
The Vagrant build should pick up the `security.yml` file. I haven't see that timeout before. Can you verify the version of Vagrant and VirtualBox you are running? You need Vagrant 1.7.3+ and probably virtualbox 4.3+.

**Comment by deepagargit** [comment]
I have below versions. 
I understand I need Vagrant updated 1.7.3. Do I need to update virtualbox also to 5.0?

Vagrant 1.7.2
Virtualbox 4.3.30

**Comment by deepagargit** [comment]
Vagrant 1.7.4
Virtualbox 4.3.30

Same timeout error.

**Comment by deepagargit** [comment]
Vagrant 1.7.4
Virtualbox 5.0

All latest versions. Same timeout error.
Could someone suggest the fix?

**Comment by eirslett** [comment]
What is your host OS? Windows? OS X? I'm not sure whether that could impact the result of the build (though it's not supposed to)

**Comment by deepagargit** [comment]
OS is CentOS-7 with SE enabled.

**Comment by deepagargit** [comment]
Any thoughts to fix the vagrant issue on CentOS-7 with SE enabled ?

Vagrant 1.7.4
Virtualbox 5.0

All latest versions. Same timeout error.
Could someone suggest the fix?

**Comment by deepagargit** [comment]
I have tried with lower Virtualbox version as well.

Any thoughts to fix the vagrant issue on CentOS-7?

Vagrant 1.7.2
Virtualbox 4.3

**Comment by ryane** [comment]
Are you running vagrant 1.7.2? You definitely need Vagrant 1.7.3+

**Comment by deepagargit** [comment]
I tried with 1.7.4 vagrant , same error!  Any more thoughts for the fix?

============================================================
Vagrant 1.7.4
Virtualbox 4.3
MI 0.3.2
CentOS7

============================================================

[@CentOS7 ~]$ vboxmanage --version
4.3.30r101610
[@CentOS7 ~]$ vagrant --version
Vagrant 1.7.4
[@CentOS7 ~]$ systemctl status firewalld
firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled)
   Active: inactive (dead)

[@CentOS7 ~]$ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      28

============================================================


[cisco@CentOS7 microservices-infrastructure]$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'CiscoCloud/microservices-infrastructure'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'CiscoCloud/microservices-infrastructure' is up to date...
==> default: Setting the name of the VM: microservices-infrastructure_default_1442676583790_85866
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

=================================================================

**Comment by deepagargit** [comment]
With Vagrant ip --debug ... I see following logs ... "Command not in installer"

Is it something to do with vagrant or virtualbox issue ?

Vagrant 1.7.4
Virtualbox 4.3
MI 0.3.2
CentOS7

====================================================================


DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
DEBUG virtualbox_4_3:   - [1, "ssh", 2222, 22]
DEBUG ssh: Checking key permissions: /home/cisco/.vagrant.d/insecure_private_key
 INFO ssh: Attempting SSH connection...
 INFO ssh: Attempting to connect to SSH...
 INFO ssh:   - Host: 127.0.0.1
 INFO ssh:   - Port: 2222
 INFO ssh:   - Username: vagrant
 INFO ssh:   - Password? false
 INFO ssh:   - Key Path: ["/home/cisco/.vagrant.d/insecure_private_key"]
 INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "dadac1d1-01b0-4f88-abe5-5668d0706755", "--machinereadable"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: name="microservices-infrastructure_default_1442677009730_22726"
groups="/"

**Comment by deepagargit** [comment]
Any inputs??

**Comment by deepagargit** [comment]
[Solved]
Added Hardware Virtualization on vSphere VM.

It would be good to add advisory to MI outpur when failure happens, since 32-bit vbox doesn't give failure and User assumes failure is only with MI vbox.
=====================================================================

Vagrant Failing with 64 bit vbox:
The vagrant instantiation using vbox 64-bit on GCP-Pod has been failing (e.g. hashicorp/precise64 or CiscoCloud/microservices-infrastructure).

Vagrant Passing with 32 bit vbox: 
The vagrant instantiation using vbox 32-bit on GCP-Pod has been passing (e.g hashicorp/precise32).

The issue might puzzle since 32-bit vbox works while 64-bit vbox fails with vagrant and this kills many cycles by the time 32-bit Vs 64-bit difference is detected!

======================================================================

Enable Hardware Virtualization over vSphere VM, on which vagrant is creating the instance.

The instruction are shared below.

1.	From vSphere Client. 
a.	Power off VM
b.	Right click on the VM, and click the *Upgrade Virtual Hardware*

2.	Next, login to WebSphere client
a.	click on the VM, check the Settings option. 
b.	To verify if it changed in to VM version 10, and click edit.

3.	From WebSphere client 
a.	Check the option and click CPU, check the option *Hardware virtualization*, click OK. you are done.

**Comment by eirslett** [comment]
I guess the Vagrant stuff should have more documentation in general...?

**Comment by chrislovecnm** [comment]
@deepagargit I am wondering if the vSphere api will allow us to do that automatically.  Does your vm ovf have these settings already?  This might be a vm ovf setting where you can upgrade then save the ovf for later use.
