### ISSUE TITLE
Can't access slave's sandbox

### ISSUE THREAD

**Issue by TeaBough** [CiscoCloud/microservices-infrastructure#692]
When I'm on the mesos master UI and I try to access the Sandbox of a task I get :
```
Failed to connect to slave '20150909-142320-857843904-15050-14868-S0' on 'worker1:5051'.
Potential reasons:
The slave's hostname, 'worker1', is not accessible from your network
The slave's port, '5051', is not accessible from your network
The slave timed out or went offline
```

I run 3 mesos masters and 1 slave all of them using `CiscoCloud/microservices-infrastructure` box in Vagrant. All `/etc/hosts` are correctly set. When I ssh my master node I can see using `nmap` that I can access the port 5051 of worker1 (which is my slave hostname). I really don't know why it is not working.

**Comment by stefanbacon** [comment]
It's because it's trying to access slave on https but it's running on http.
there was a patch to fix the urls so it uses http but then javascript complains about loading unsecured resources inside https page.
We need to wait for mesos 0.23 with native ssl support.

In the mean time you can create an SSH tunnel:

ssh -L 5050:localhost:15050 MASTER-IP-ADRESS

and access mesos on http://localhost:5050 , the slave sandbox will work here

**Comment by TeaBough** [comment]
It doesn't work in my case. When I tunnel ssh using the 15050 port I get : 
```
channel 4: open failed: connect failed: Connection refused
channel 5: open failed: connect failed: Connection refused
channel 6: open failed: connect failed: Connection refused
channel 7: open failed: connect failed: Connection refused
```

I when I tunnel ssh using 5050 port I get the same problem as in my first comment.

**Comment by TeaBough** [comment]
Ok my mistake, I did : `ssh -L 5050:localhost:15050 MASTER-IP-ADRESS` instead of `ssh -L 5050:MASTER-IP-ADRESS:15050 MASTER-IP-ADRESS`. It's working now. Thank you very much,

**Comment by stefanbacon** [comment]
yeah I edited my comment had written it by memory but remembered it was wrong was hoping I had fixed it before you tired it! sorry

**Comment by TeaBough** [comment]
Don't worry it has helped me to have a deeper understanding of ssh tunnels ;-)

**Comment by eirslett** [comment]
I've disabled the iptables rule for mesos and then access the dashboard at http://mi-control-01.example.com:15050/, that works but it's an ugly hack.

**Comment by stevendborrelli** [comment]
@TeaBough we've added a new UI in master that wraps all of the endpoints. 

For example https://control/mesos, https://control/marathon. Would you like to test?

**Comment by TeaBough** [comment]
@stevendborrelli  yeah I've seen that thx, I've been using it since it's out, even if it's broken when using mesos 0.24.1, but with 0.23.0 it's working great !

**Comment by ryane** [comment]
@TeaBough if you feel like testing it, the changes in #745 might help with mesos 0.24.1

**Comment by TeaBough** [comment]
@ryane yep
