### ISSUE TITLE
Docker on CentOS 7.1 fails to start "ServeAPI error: No sockets found"

### ISSUE THREAD

**Issue by abn** [CiscoCloud/microservices-infrastructure#695]
The root cause of the issue is the `-H fd://` in https://github.com/CiscoCloud/microservices-infrastructure/blob/master/roles/docker/tasks/main.yml#L83-L86.

This expects socket activation, this is no longer the case for CentOS and Fedora. See upstream issue at https://github.com/docker/docker/issues/11135.

**Comment by eirslett** [comment]
I'm not sure `$other_arg` is needed at all... I guess it should be possible to inject the other options via files, the systemd way? It would be nice to leave the main service configuration alone.

**Comment by abn** [comment]
`other_arg` is required to facilitate configuration of dns for the docker daemon see https://github.com/CiscoCloud/microservices-infrastructure/blob/master/roles/docker/tasks/main.yml#L57-L68

As clarified by Brian at https://github.com/CiscoCloud/microservices-infrastructure/issues/688#issuecomment-138907383, the drop-in file was used due upstream docker packaging issues.

**Comment by stevendborrelli** [comment]
@abn: I'm going to close this, please reopen if you still have this issue.
