### ISSUE TITLE
Can't find a way to change ServicePort in a *-direct service

### ISSUE THREAD

**Issue by TeaBough** [CiscoCloud/microservices-infrastructure#696]
Every time a start a service using marathon an similar `service-direct` is registered in Consul with a `ServicePort` set to 0. I would like to be able to change this port when launching the app. I can't find a way to do that. Moreover I can't find the place responsible for registering those `*-direct` services in consul.

**Comment by eirslett** [comment]
It's happening somewhere in calico or mesos-consul (the docker container) I think...

**Comment by TeaBough** [comment]
In the doc it says something about Powerstrip but I don't see where it's set. For instance, what if I want to change from `*-direct` to `*-toto` ?

**Comment by TeaBough** [comment]
So to answer a part of my question, I pretty sure that the logic of registering `*-direct` services is done in the `ciscocloud/calico` image. Unfortunaty it's not possible to get access to the Dockerfile : https://hub.docker.com/r/ciscocloud/calico-node/ to see how it's done.

**Comment by loshkovskyi** [comment]
@TeaBough regarding those `*-direct` services, please take a look on this branch https://github.com/CiscoCloud/calico-docker/blob/add-consul-support/calico_containers/adapter/powerstrip_calico.py#L38
The `-direct` suffix is set with the variable `CONSUL_CALICO_DNS`.

**Comment by TeaBough** [comment]
@loshkovskyi  Thank you very much, I didn't see this branch !

**Comment by loshkovskyi** [comment]
Please confirm this is the issue you are having:
```
[cloud-user@mi-control-01 ~]$ dig @localhost -p 8600 testapp.service.consul SRV +short
1 1 4409 mi-worker-003.node.dc1.consul.
1 1 31375 mi-worker-001.node.dc1.consul.
1 1 31000 mi-worker-002.node.dc1.consul.

[cloud-user@mi-control-01 ~]$ dig @localhost -p 8600 testapp-direct.service.consul SRV +short
1 1 0 mi-worker-002.node.dc1.consul.
1 1 0 mi-worker-003.node.dc1.consul.
1 1 0 mi-worker-001.node.dc1.consul.
```

**Comment by TeaBough** [comment]
Exactly, I've added a PR in https://github.com/CiscoCloud/calico-docker to set the port of the service in Consul for the direct-* services.

**Comment by loshkovskyi** [comment]
@TeaBough, I've pushed new Calico image with the tag `v0.4.9-mi-test` which you can set in https://github.com/CiscoCloud/microservices-infrastructure/blob/master/roles/calico/defaults/main.yml#L3 to verify the changes.

It should be working like so:
```
[cloud-user@mi-worker-002 ~]$ dig @localhost -p 8600 testapp7.service.consul SRV +short
1 1 4803 mi-worker-002.node.dc1.consul.
1 1 31545 mi-worker-001.node.dc1.consul.
1 1 31422 mi-worker-003.node.dc1.consul.

[cloud-user@mi-worker-002 ~]$ dig @localhost -p 8600 testapp7-direct.service.consul SRV +short
1 1 7000 mi-worker-003.node.dc1.consul.
1 1 7000 mi-worker-001.node.dc1.consul.
1 1 7000 mi-worker-002.node.dc1.consul.
```

Let me know if you need any help on this.

**Comment by loshkovskyi** [comment]
@TeaBough, the PR https://github.com/CiscoCloud/microservices-infrastructure/pull/728 has been merged, let me know if I can close this issue.
