### ISSUE TITLE
RPM packages for mesos and collectd

### ISSUE THREAD

**Issue by SupriyaPrasad** [CiscoCloud/microservices-infrastructure#699]
Hi Team,

Could you please provide the rpm packages (centos 7) for mesos and collectd?

mesos version: 0.23.0 
collectd version: 5.5.0

also you please let me knw the cisco cloud location?

**Comment by eirslett** [comment]
If you install Microservices-infrastructure (which is a software project, it has now been renamed to Mantl) it will install all of the packages for you. Most of them are simply from the official repositories.
This is a project page for the software, not a cloud provider that gives you servers.

**Comment by SupriyaPrasad** [comment]
Thank you for the reply, but we are building another environment similar to microservices infrastructure. most of the rpm i have got but just these two are left over. in the mesos and collectd playbook i dont see a specific rpm link so could you please provide them?

**Comment by eirslett** [comment]
Look at the common role, I think it adds an rpm repository. The mesos role also adds a repository. They get their rpms from there.

**Comment by stevendborrelli** [comment]
Mesos is pulled from the Meosphere yum repo, collectd is installed via Centos package. 

We are also re-packaging many of the ansible roles, you can track progress at https://bintray.com/asteris/mantl-rpm

**Comment by SupriyaPrasad** [comment]
Thank you Steven, could you please provide me the link of the collectd rpm package for centos7? i search for it but couldnt find it. Collectd version 5.5.0

**Comment by siddharthist** [comment]
From [collectd's webpage](https://collectd.org/download.shtml), "For Red Hat, CentOS and fedora, there are collectd RPM packages in Dag Wieers' repository." which is [here](http://pkgs.repoforge.org/collectd/).

**Comment by stevendborrelli** [comment]
Closing this issue.
