### ISSUE TITLE
"centos" user name is hard coded.

### ISSUE THREAD

**Issue by saswatp** [CiscoCloud/microservices-infrastructure#701]
Newer CentOS releases have cloud-user as default user . Since centos user name is hardcoded for logging into nodes , login fails.

**Comment by siddharthist** [comment]
@saswatp As far as I am aware, the login name is different on the different cloud providers, e.g. "root" on DigitalOcean, and centos on GCE. Maybe we could document this, rather than change how it works?

**Comment by siddharthist** [comment]
Closing in favor of #947
