### ISSUE TITLE
Create distributable binary for mi-deploy

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#702]
Users shouldn't need to build their own binaries of mi-deploy. Please make mi-deploy binaries avalilble for our common platforms. 

See the Makefile at https://github.com/CiscoCloud/consul-cli/blob/master/Makefile for a build pattern. 

@siddharthist

**Comment by saswatp** [comment]
+1 - We certainly need this. 

One more feedback : 

mi_deploy is part of MI . When user downloads MI code with mi_deploy in it , (s)he most of the time wishes to deploy that version/branch of MI. Right now mi_deploy by default downloads a master branch in "deployments" and every time it creates a new deployment snapshot with current timestamp. User should just be allowed to deploy the MI (s)he has downloaded.

**Comment by siddharthist** [comment]
These aer live [here](https://bintray.com/siddharthist/mi-deploy/mi-deploy/0.0.1/view?sort=&order=). I'm working on getting them in our organization.

**Comment by eirslett** [comment]
> When user downloads MI code with mi_deploy in it , (s)he most of the time wishes to deploy that version/branch of MI.

I guess I'm derailing this issue - but actually, one of the strongest wins we got from using mi-deploy was separating code and configuration. (Have them in different repositories) So we can deploy our cluster using MI code from the upstream repository, but with custom tweaks/configuration for us that is kept in a separate in-house repository. In that regard, mi-deploy works more like a package manager, like npm or r10k.

This is our setup:
We have an internal git repository for custom configuration, with cluster1/tf-files/..., cluster2/tf-files/... etc. Then we have another repository github.com/finn-no/microservices-infrastructure, which is a fork of MI with some of our changes, but eventually we want to deploy directly from upstream. We then use mi-deploy to combine configuration and code as the cluster is deployed.

**Comment by siddharthist** [comment]
@saswatp @eirslett If either of you have any feedback unrelated to creating binaries, we'd love to hear it! Please go ahead and create a separate issue and we can discuss there.

**Comment by siddharthist** [comment]
These are live! https://bintray.com/asteris/mantl-deploy/mantl-deploy/v0.1.0/view?sort=&order=#files

**Comment by npateriya** [comment]
Can we Cisco official bintray account?
