### ISSUE TITLE
How to access *-direct service through ha-proxy 

### ISSUE THREAD

**Issue by TeaBough** [CiscoCloud/microservices-infrastructure#704]
I have a service email running in a container on port 8080. This service has been registered in haproxy conf this way : 
```
frontend www
    bind *:80
    acl host_rights-direct hdr(host) -i rights-direct.192.168.31.51.xip.io
    use_backend rights-direct_backend if host_rights-direct
backend rights-direct_backend
   server worker3 192.168.0.10:0
```

How am suppose to access this service through haproxy ? I tried : 

```
curl -L  --header "Host: rights-direct.192.168.31.51.xip.io" 192.168.31.51/check
```

But it won't work since haproxy is redirecting this request to the port `0` of `192.168.0.10`.

The only thing working is : 
```
curl 192.168.0.10:8080/check
```
But I really want to use haproxy !

**Comment by eirslett** [comment]
What I have suggested (but it's not implemented yet) is to add "workerhost" as a record in dnsmasq (referring to the worker node's public IP), so that you can access haproxy on "myapp.workerhost" - would that work for you?

**Comment by TeaBough** [comment]
I don't think so because in my case it's a port problem. I need a way to change : 

```
backend rights-direct_backend
   server worker3 192.168.0.10:0
```
to : 

```
backend rights-direct_backend
   server worker3 192.168.0.10:8080
```

**Comment by TeaBough** [comment]
I've added a PR in https://github.com/CiscoCloud/calico-docker to set the port of the service in Consul.

**Comment by loshkovskyi** [comment]
@TeaBough, the PR https://github.com/CiscoCloud/microservices-infrastructure/pull/728 has been merged, let me know if I can close this issue.

**Comment by TeaBough** [comment]
Yes thx !
