### ISSUE TITLE
zookeeper service fails to start

### ISSUE THREAD

**Issue by ipolyzos** [CiscoCloud/microservices-infrastructure#705]
Zookeeper service start is failing due to an error risen from "zookeeper-wait-to-listen.sh"script execution. Further diving into this turns out that "zookeeper-service.j2" template is not publishing the port.

**Comment by ipolyzos** [comment]
the problem still exists and is due to the zookeeper docker container. I can access it in port 2181 with nc when i refer to as localhost but not when using the internal/external IP or hostname.  The systemd unit file seems to be generated correctly.

**Comment by ipolyzos** [comment]
trying to access the curl consul.service.consul:8500 using "curl http://consul.service.consul:8500/v1/health/service/zookeeper?wait=60000ms" results to "302 Not Found " however sshing into the machine and attempt curl "http://localhost:8500/v1/health/service/zookeeper?wait=60000ms" works fine.

**Comment by ChrisAubuchon** [comment]
The `consul.service.consul` address uses HTTPs. You can either use `https://consul.service.consul` or use `curl -L`.

**Comment by ipolyzos** [comment]
I can see that the generated */etc/defaults/zookeeper* contain the following information *CONSUL_CONNECT=consul.service.consul:8500* and *CONSUL_SSL=true* also this file is passed in the container from the parameter  *--env-file={{ zookeeper_env }} \* . However the call to the service happen in *http* and not *https*.

**Comment by ipolyzos** [comment]
what i can see from when attach in the zookeeper image is the following ERR log   : 

> 2015/09/22 16:05:34 [ERR] (runner) watcher reported error: health services: error fetching: Get http://consul.service.consul:8500/v1/health/service/zookeeper?wait=60000ms: dial tcp: lookup consul.service.consul on 10.10.10.2:53: server misbehaving

How could we change this behavior? is there any properties that could enforce *https* ?

**Comment by ChrisAubuchon** [comment]
The `10.10.10.2:52: server misbehaving` is indicating a DNS issue from inside the Zk container. Is 10.10.10.2 reachable from inside the container? `docker exec -it zookeeper /bin/bash` to get a shell in the container.

**Comment by ipolyzos** [comment]
*10.10.10.2:52* is reachable from the container along with all the other hosts, the dns servers are correctly set, though the error log continue to be generated

**Comment by ipolyzos** [comment]
as a quick & dirty solution have disabled consul ssl (i.e. do_consul_ssl: false) and the installation seems to proceed normally

**Comment by ipolyzos** [comment]
Still resulted in the same issue. Got in the container and i can access 10.10.10.2, ping it etc I can also access all the other machines. It has been set as name server at resolve.conf but can not translate the *consul.service.consul* name in an ip address and therefor can not access it.

**Comment by heww** [comment]
The problem happened when consul cluster is down, zookeeper image use consul-template for zookeeper config but failed for consul is down, so zookeeper failed. There are some issues about that https://github.com/CiscoCloud/microservices-infrastructure/issues/566   https://github.com/hashicorp/consul/issues/993

**Comment by ipolyzos** [comment]
what confuses me with this issue is that consul server were online at all time and failure occured

**Comment by heww** [comment]
@ipolyzos I'm sorry, this problem was happened  for me and consul is online.

**Comment by ipolyzos** [comment]
@heww attaching in the ZooKeeper container I can see that tries to connect I'm consul.service.consul at http instead of https. Issuing the same request in https works fine. I believe change Nginx conf to redirect all traffic to https might be a good candidate solution.

**Comment by ipolyzos** [comment]
is there any updates with this issue?

**Comment by ipolyzos** [comment]
issue resolved, fixed when pass the docker host as a DNS server to the container (i.e.add --dns={{ private_ipv4 }}) in zookeeper systemd unit

**Comment by stevendborrelli** [comment]
@ipolyzos could you check your /etc/sysconfig/docker file? You should have these dns options set for the docker daemon, so all containers use consul for resolution.
