### ISSUE TITLE
Thoughts on mantl-cli/mi-deploy

### ISSUE THREAD

**Issue by eirslett** [CiscoCloud/microservices-infrastructure#706]
Here's some feedback:

We're running a slightly modified version of mi-deploy now, with this project layout in our internal "configuration" git repository:

```
bin/mi-deploy
cluster1/...
cluster2/...
cluster3/...
```

...where we have different configurations per cluster in their own folder.

One thing we found was that mi-deploy is built around the idea that you're supposed to deploy the same cluster configuration, but to different cloud providers. (--provider aws, --provider openstack etc). That makes a lot of sense for integration tests (:+1:), because you want to test changes in the master branch (or the PR) for whether it works or not.

:-1: In an actual mesos deployment however, you probably want to have different configurations for every cluster, and you probably only want to deploy the cluster to one cloud provider. Sending the `-platform` flag into mi-deploy didn't make a lot of sense for us, since which provider you use is determined by which terraform file you include in tf-files. (But it's a mandatory argument to mi-deploy, so you have to use it anyways)

:-1: Having multiple deployments in the ./deployments/ folder didn't make sense, because we only have one mantl deployment per folder (cluster1, cluster2, cluster3).

:+1: The tf-files/ stuff worked pretty well, since we're able to do all the tweaks we need in either the terraform .tf file or the ansible .yml file, different for every cluster.

We added a modification so that we can add things like security.yml and certificates in ~/.ssh on our "bootstrap" server - we have a dedicated meta-server which job it is to deploy our mantl clusters. It's valuable to be able to commit configuration into a repository, but not commit the secrets; that's something that one should maybe look into.

Compiling it from source is a hassle, so it's a good thing that binaries are published now (:+1:). But since mi-deploy is so simple, it could have been written in pure bash.

We run mi-deploy from jenkins/bamboo, so we needed a way to turn off the interactive mode.

:-1: We don't really want a higher-level tool that abstracts away the underlying tools. Other open-source projects have done similar things before: [Yeoman](http://yeoman.io/) is a popular open-source project that went down the path of wrapping underlying tools, and then [decided not to](http://stephenplusplus.github.io/yeoman.io/migrate.html). (I'm sure @addyosmani knows that story better than me.) In our experience, it's easier to simply use Terraform and Ansible directly - they are both well-documented and widely used. Besides, using the underlying tools directly gives us more control and lets us fine-tune mantl more - any high-level tool that's built to abstract away other tools will necessarily be less flexible than using these tools directly.

:+1: :+1: Being able to specify which git repository and branch of mantl to deploy is the best feature of mi-deploy, since it allows us to separate code and configuration. In principle, that lets us run Mantl straight off of the official master branch/release, without having to maintain a fork only for configuration.

So that's our comments, thanks for the efforts on making mi-deploy! It really improved our workflow when we were able to separate code and configuration! Cheers! :beers:

**Comment by siddharthist** [comment]
@eirslett We created mi-deploy mostly to simplify our own testing process. I think it really reflects this use case, especially in its inability to support multiple configurations, and a mandatory platform argument. Our use case is mostly having .tf files for ALL our supported platforms in `tf-files/`, which then get selected via the arg. The interactivity could be disabled, but then you get exactly what you would if you just run the Ansible and Terraform commands in our documentation.

**Comment by stevendborrelli** [comment]
I think many of @eirslett's comments are really good. In particular:

1) the use of a deployments/ directory is required less when building via an automated system like Jenkins. 

2) The idea that someone wants to deploy multiple clusters to a single cloud is something we need to thing about. 

3) We are building out some tools that wrap terraform, we need to keep in mind that for many of these use cases. The mantl command line would be for end-users and mi-deploy for our internal testing.

**Comment by eirslett** [comment]
Ah I see, of course given that mi-deploy is scoped to integration tests only, the design makes a lot more sense.
Though if the mantl command is used both for end users and integration tests, the tests will be more reliable, since they are run in the same way as users would run the commands in production?

**Comment by saswatp** [comment]
Since mi-deploy is part of microservices-infra it would make sense to allow users to deploy the micro-services infra they have downloaded instead of always downloading the latest (or specified branch). Current design is fine, but there is a need for deploying the already downloaded microservices-infra. 

Other option is to put mi-deploy in a separate repo. Then it can download a new version of MI and deploy it. That would make more sense IMO.

**Comment by eirslett** [comment]
I think mi-deploy also lets you specify a commit hash tag instead of a HEAD. So you are able to deploy whatever version if mantl you wish.
It certainly has another "release cycle" than the main mantl project - I guess it's in the same repository just because that's simple to begin with.

**Comment by saswatp** [comment]
@eirslett  - Do you mean I could test my local changes with commit hash tag without pushing it to the repo ? 
If I make a one line change, I would like mi-deploy to deploy the changed code , so that it could be tested.

**Comment by eirslett** [comment]
Aah I see, yes in that use-case there's missing something. It should be possible to run mi-deploy on a dirty working tree as well as on a commit hash! (What I have done in these cases is to not use mi-deploy at all, but just use mantl/terraform/ansible directly. It's not very pretty)

**Comment by siddharthist** [comment]
Closed because `mi-deploy` has been removed in favor of `testing/build-cluster.py`.
