### ISSUE TITLE
Add roadmap to README

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#71]

**Comment by BrianHicks** [comment]
We might want to add a ROADMAP.rst in the top level so it can be included
to in the docs.

**Comment by keithchambers** [comment]
I just committed a first cut to the main README to get something out there.  I need to understand a bit more about how we update readthedocs.org.

**Comment by BrianHicks** [comment]
This repo has a webhook to RTD - any time there's a push to master it rebuilds the docs. Basically, we'd just add `ROADMAP.rst` in the root, and then include it in the `toctree` directive in `docs/index.rst`.

**Comment by keithchambers** [comment]
Hey Brian, can you help me to create a list with market items in Sphinx?

- [x] Foo
- [ ] Bar
- [ ] Baz

I've been Googling around for 20 minutes and can't find a solution.

**Comment by benschumacher** [comment]
Keith-

I'm not sure rST natively supports a checklist, but you could do something like this:

'''
* [x] Foo
* [ ] Bar
* [ ] Baz
'''

I think it would transform fairly cleanly.

**Comment by BrianHicks** [comment]
@keithchambers try substitutions:

```
- |checked| foo
- |unchecked| bar
- |unchecked| baz

.. |checked| unicode:: U+2610
.. |unchecked| unicode:: U+2611
```

Here are the docs for: [replacments](http://docutils.sourceforge.net/docs/ref/rst/directives.html#replacement-text), [the unicode directive](http://docutils.sourceforge.net/docs/ref/rst/directives.html#unicode), and [the code points I'm using in that example](https://en.wikipedia.org/wiki/Checkbox#Unicode)

**Comment by BrianHicks** [comment]
I think you could even make your substitution `| |` and `|x|` if you want to mirror the GFM syntax.

**Comment by keithchambers** [comment]
Thx! I'll give it a go this afternoon!

**Comment by keithchambers** [comment]
[Committed](https://github.com/CiscoCloud/microservices-infrastructure/commit/ea24915986a2857f5eee944e1d25c0c5cccc35d9) and [verified](http://microservices-infrastructure.readthedocs.org/en/latest/roadmap.html)!  Closing.
