### ISSUE TITLE
Add HelloWorld example

### ISSUE THREAD

**Issue by masonse** [CiscoCloud/microservices-infrastructure#72]
Can you provide a simple HelloWorld type example for someone to use/follow?  A simple MySQL or webserver would suffice.

**Comment by stevendborrelli** [comment]
Thanks for your ticket, that's a great idea. We'll add marathon example files to the repo in a future release.

For now, you can use some of the examples from the marathon project: https://github.com/mesosphere/marathon/tree/master/examples

**Comment by keithchambers** [comment]
Perhaps we create a single shell script that queries consul for the marathon endpoints in each datacenter and post a marathon config!

**Comment by keithchambers** [comment]
Something like this ...

$ cat hello-world.json
{
  "container": {
    "type": "DOCKER",
    "docker": {
      "network": "BRIDGE",
      "image": "keithchambers/docker-hello-world",
      "portMappings": [ { "containerPort": 80,"protocol": "tcp"} ]
    }
  },
  "id": "hello-world",
  "instances": 2,
  "cpus": 0.1,
  "mem": 128
}

curl -X POST -H "Content-Type: application/json" http://10.1.2.3:8080/v2/apps -d@Docker.json

**Comment by masonse** [comment]
Add some comments to the beginning and it looks good.

**Comment by PeterLamar** [comment]
Close? We have a hello world example now
