### ISSUE TITLE
Default volume is too small on AWS

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#723]
Spun up a cluster on AWS, and the root volumes were only 8GB. Can we make the root volume larger on these nodes? 

- [x] configure control node size
- [x] configure worker node size

**Comment by ryane** [comment]
aws is addressed in #724. will work on making volume sizes configurable on other providers

**Comment by ryane** [comment]
* digitalocean disk size is not configurable (controlled by instance size)
* not sure how to specify disk size on vsphere or softlayer (ping @eirslett)
* it looks like we could specify a volume size for openstack by using the `block_device` option but not setup to test openstack right now

**Comment by eirslett** [comment]
I think SoftLayer uses the default disk size on SoftLayer, newer versions of the terraform provider have support for setting the disk size. I'll have a look at it!

**Comment by ryane** [comment]
this was fixed in #724. added issues to the backlog for openstack, vsphere, and softlayer
