### ISSUE TITLE
Missing Logstash image on docker.io

### ISSUE THREAD

**Issue by jtfogarty** [CiscoCloud/microservices-infrastructure#732]
I’m seeing an error when a Logstash image is getting pulled
looking at this site
https://index.docker.io/v1/repositories/ciscocloud/logstash/images

Get https://index.docker.io/v1/repositories/ciscocloud/logstash/images: dial tcp 54.210.246.75:443: connection timed out

There are no images when I browse to this location

**Comment by siddharthist** [comment]
It looks to me like `sudo docker pull ciscocloud/logstash:0.2` works. Have you run into this multiple times?

**Comment by jtfogarty** [comment]
Yes, several times.  The proxy log shows 404 error

**Comment by stevendborrelli** [comment]
@jtfogarty was this related to your proxy issues? Can we close this one out?

**Comment by jtfogarty** [comment]
Yes, it can be closed!
