### ISSUE TITLE
Glusterfs link not reachable

### ISSUE THREAD

**Issue by AndriiOmelianenko** [CiscoCloud/microservices-infrastructure#746]
Hi,

I'm trying to install cluster on OpenStack and stuck here:

```
TASK: [glusterfs | enable community repo] *************************************
failed: [control-02] => {"failed": true}
msg: Failed to connect to download.gluster.org:443.
failed: [control-03] => {"failed": true}
msg: Failed to connect to download.gluster.org:443.
failed: [control-01] => {"failed": true}
msg: Failed to connect to download.gluster.org:443.
```
```
$ curl download.gluster.org:443
curl: (7) Failed to connect to 2001:4801:7824:104:be76:4eff:fe10:23d8: Network is unreachable

$ sudo telnet download.gluster.org 443
Trying 23.253.208.221...
telnet: connect to address 23.253.208.221: Connection refused
Trying 2001:4801:7824:104:be76:4eff:fe10:23d8...
telnet: connect to address 2001:4801:7824:104:be76:4eff:fe10:23d8: Network is unreachable
```

I've take link from here: https://github.com/CiscoCloud/microservices-infrastructure/blob/master/roles/glusterfs/tasks/main.yml#L5
but seems it's not accessible.
```
$ wget https://download.gluster.org/pub/gluster/glusterfs/3.7/3.7.3/CentOS/glusterfs-epel.repo
--2015-10-21 15:35:06--  https://download.gluster.org/pub/gluster/glusterfs/3.7/3.7.3/CentOS/glusterfs-epel.repo
Resolving download.gluster.org (download.gluster.org)... 23.253.208.221, 2001:4801:7824:104:be76:4eff:fe10:23d8
Connecting to download.gluster.org (download.gluster.org)|23.253.208.221|:443... failed: Connection refused.
Connecting to download.gluster.org (download.gluster.org)|2001:4801:7824:104:be76:4eff:fe10:23d8|:443... failed: Network is unreachable.
```
Is link / version correct?

**Comment by AndriiOmelianenko** [comment]
it's http/https issue:
works: **http**://download.gluster.org/pub/gluster/glusterfs/3.7/3.7.3/CentOS/glusterfs-epel.repo
doesn't work: **https**://download.gluster.org/pub/gluster/glusterfs/3.7/3.7.3/CentOS/glusterfs-epel.repo

**Comment by stevendborrelli** [comment]
@AndriiOmelianenko can you submit a pull request?

**Comment by AndriiOmelianenko** [comment]
@stevendborrelli yes, definitely:
https://github.com/CiscoCloud/microservices-infrastructure/pull/747

**Comment by ryane** [comment]
@AndriiOmelianenko are you still having issues with the https link? it is valid and has been used for a while. I am wondering if it was a transient issue.

**Comment by corebug** [comment]
@ryane @AndriiOmelianenko well, by now it's working again. I've also noticed a period of 1-2 weeks in which host download.gluster.org didn't respond to TCP/443. I guess by now the issue can be closed.

**Comment by ryane** [comment]
ok, thanks, if this pops up again we'll revisit
