### ISSUE TITLE
Docker packages overwrite /etc/sysconfig/docker

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#750]
If we are using the official docker rpms, any upgrade will overwrite `/etc/sysconfig/docker` and remove our custom DNS settings. This causes anything that uses consul for DNS resolution to fail

Options:

- create a `/etc/sysconfig/docker-local`
- write to `/etc/systemd/system/docker.service.d/local.conf` directly with the dns settings

**Comment by BrianHicks** [comment]
Personally, I prefer `/etc/sysconfig/docker-local` because it's most expected on CentOS, but either of these seems fine.

**Comment by stevendborrelli** [comment]
I am also leaning towards an Environment file.
