### ISSUE TITLE
Support physical block devices for device-mapper

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#751]
See:  http://www.projectatomic.io/docs/docker-storage-recommendation/

**Comment by avnik** [comment]
Looks like we need physical block device, not loopback

**Comment by stevendborrelli** [comment]
Updated the ticket title

**Comment by avnik** [comment]
Roadmap for discussion:

* Single volume group (VG) with all available extra block devices
* two logical volumes for  docker (data+metadata)
* volume for glusterfs (replace direct usage of block device in current setup)
* other LV (for future usage)

Questions:
* assertion in TF if we have docker + gluster LVs requested with size bigger than all PVs.

**Comment by stevendborrelli** [comment]
Closing, as this was implemented with #797.
