### ISSUE TITLE
Kubernetes deployment testing

### ISSUE THREAD

**Issue by PeterLamar** [CiscoCloud/microservices-infrastructure#752]

**Comment by PeterLamar** [comment]
As a developer, I can run the tests that validate the deployment of Kubernetes is valid

Acceptance Criteria:

Every Ansible task should be tested

Additional Info:
https://github.com/CiscoCloud/distributive

**Comment by siddharthist** [comment]
Duplicate of #753. We now have a tech preview of Kubernetes available, and are working on further integration.
