### ISSUE TITLE
Automated Testing for Kubernetes Deployment

### ISSUE THREAD

**Issue by PeterLamar** [CiscoCloud/microservices-infrastructure#753]
As a developer, I see that the automation that deploys K8s is tested on a regular schedule so that build status is quickly and easily evaluated

Acceptance Criteria:
A button is available on the page to observe if the build is passing
K8s clusters are regularly spun up and tested to conform to configuration
A sample k8s application "Hello world" is spun up on a pod and tested

Additional Info:
Jenkins or another similar tool can be utilized for this purpose

**Comment by siddharthist** [comment]
Travis testing for `kubernetes.yml` is available in our current configuration, just commented out due to the prohibitive use of resources to test two playbooks on three clouds each.
