### ISSUE TITLE
Automatic Mesos Cluster Testing

### ISSUE THREAD

**Issue by PeterLamar** [CiscoCloud/microservices-infrastructure#754]
As a developer, I can deploy a mesos cluster and verify that the components are running and available on a scheduled basis

Acceptance Criteria:
A button is available on the page to observe if the build is passing
Components Zookeeper is up
Mesos is up
Marathon is up
Consul is up
A 'hello world' application can be triggered on Marathon

Additional Info:
Jenkins or another similar tool can be utilized for this purpose

**Comment by eirslett** [comment]
We do this on our CI - we deploy the cluster (mi-deploy), then run curl against the consul API in a loop, until it tells us all the nodes are healthy. (Meaning that distributive has run all the health checks and they succeeded)

**Comment by frankscholten** [comment]
Checkout minimesos.org

**Comment by siddharthist** [comment]
Duplicate of #163, #547
