### ISSUE TITLE
MantlUI - Mesos - 404

### ISSUE THREAD

**Issue by AndriiOmelianenko** [CiscoCloud/microservices-infrastructure#756]
Hi, I've installed Mantl in OpenStack.

I opened http://master/ in my browser and got mantl-ui opened with 4 links: mesos, marathon, chronos, consul.
All of them are working **except** Mesos - it getting `404 Not Found`

Mesos on 5050 master's port opens good, so it seems like nginx issue.

**Comment by TeaBough** [comment]
Which version of mesos are you running ?

**Comment by ryane** [comment]
Are the mesos services healthy in Consul?

**Comment by AndriiOmelianenko** [comment]
Mesos 0.24.1
It seems MantlUI supports only 0.23 for now, correct?

**Comment by TeaBough** [comment]
Yep I have the same problem with 0.24.1. But it's working with 0.23. I think that there is an issue somewhere reporting this problem,

**Comment by AndriiOmelianenko** [comment]
Yes, found it: https://github.com/CiscoCloud/microservices-infrastructure/issues/739
I'll close the issue and will follow top one then.

Thanks!

**Comment by ryane** [comment]
If you want to test it, #745 might work better with Mesos 0.24.1
