### ISSUE TITLE
Investigate other storage backends for docker

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#76]
DeviceMapper is slow on container builds. Investigate alternatives.

**Comment by stevendborrelli** [comment]
References: http://developerblog.redhat.com/2014/09/30/overview-storage-scalability-docker/

**Comment by keithchambers** [comment]
Atomic uses direct-lvm by default.  Atomic is RHEL based so we should be able to leverage their investment:

* [Here](http://www.projectatomic.io/docs/docker-storage-recommendation/) is the Atomic documentation for managing storage.
* [Here](https://github.com/projectatomic/docker-storage-setup) is their helper script that manages setup/configuration.

**Comment by stevendborrelli** [comment]
Looks like Centos 7.1 has overlayfs as a tech preview. https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.1_Release_Notes/chap-Red_Hat_Enterprise_Linux-7.1_Release_Notes-File_Systems.html

I think we need to test this ASAP to improve performance of container loads.

**Comment by keithchambers** [comment]
Closing this issue as the investigation portion is now complete.

The conclusion is to move to overlayfs.  See PR https://github.com/CiscoCloud/microservices-infrastructure/pull/180 for implementation status.

Thanks @stevendborrelli for your work on this!
