### ISSUE TITLE
Mesos web UI is not displaying correctly

### ISSUE THREAD

**Issue by jtfogarty** [CiscoCloud/microservices-infrastructure#760]
After installing Mantl to a cluster behind a proxy, the Mesos administration site at port 5050 appears as below;

![screen shot 2015-10-26 at 8 43 19 am](https://cloud.githubusercontent.com/assets/6708730/10730389/ad264846-7bbd-11e5-989b-4dd5baf1aad7.png)

**Comment by ryane** [comment]
do you get the same behavior if you access the Mesos UI at http(s)://control-node/mesos/ ?

**Comment by jtfogarty** [comment]
http(s)://control-node/mesos/ returns 404

**Comment by siddharthist** [comment]
@jtfogarty Can you retry on master please?

**Comment by stevendborrelli** [comment]
I'm trying to get access to @jtfogarty's cluster so that I can help diagnose the issue.

**Comment by siddharthist** [comment]
@jtfogarty I'm going to close this now because we've had a lot of updates to our UIs since this was opened. Please let us know if you're still having this issue!
