### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by PeterLamar** [CiscoCloud/microservices-infrastructure#77]
I completed the getting started, and filled out dc1 for my openstack project. My ansible commands return the below error with users.yml. Did I miss a step? 

user@user-VirtualBox:~/Documents/microservices-infrastructure$ ansible all -i inventory/1-datacenter -m ping
host-01 | FAILED => /home/user/Documents/microservices-infrastructure/inventory/group_vars/all/users.yml must be stored as a dictionary/hash
host-03 | FAILED => /home/user/Documents/microservices-infrastructure/inventory/group_vars/all/users.yml must be stored as a dictionary/hash
host-04 | FAILED => /home/user/Documents/microservices-infrastructure/inventory/group_vars/all/users.yml must be stored as a dictionary/hash
host-05 | FAILED => /home/user/Documents/microservices-infrastructure/inventory/group_vars/all/users.yml must be stored as a dictionary/hash
host-02 | FAILED => /home/user/Documents/microservices-infrastructure/inventory/group_vars/all/users.yml must be stored as a dictionary/hash
user@user-VirtualBox:~/Documents/microservices-infrastructure$ ansible openstack/destroy-hosts.yml 
No hosts matched

Thanks in advance,

Peter

**Comment by stevendborrelli** [comment]
Thanks for opening the issue. I don't think you did anything wrong. This looks like a bug in the users.yml role. 

If you want to proceed until we fix it, please comment out the following line in `roles//common/tasks/main.yml `: 

`- include: users.yml`

So that is looks like
`#- include: users.yml`

Please let me know if that helps.

**Comment by PeterLamar** [comment]
Indeed, that does it. It seems to affect older versions of ansible (1.6.6). I downloaded and started working with dev ansible (1.9) and I don't see it.

**Comment by keithchambers** [comment]
OK -- yea I was pretty sure I'd tested the users code thourghly prior to release and didn't see this issue.  Do you think it's worth adding a check to make sure the version of Ansible is 1.8 or greater?

**Comment by keithchambers** [comment]
We could add something like this to the ```users.yml``` playbook:
```
    - fail:
        msg: "Ansible version 1.8 or greater is required"
      when: ansible_version | version_compare('1.8', '=<')
```

**Comment by BrianHicks** [comment]
You might add a bit to that message about the version being in
`requirements.txt`. I'm not sure if that's documented yet.
