### ISSUE TITLE
The ext3 filesystem leads to issues with Docker containers filling up the disks

### ISSUE THREAD

**Issue by eirslett** [CiscoCloud/microservices-infrastructure#772]
After running a worker for some days, this is the state of the disks:
```
[root@dev1-worker-003 ~]# df -hT
Filesystem     Type      Size  Used Avail Use% Mounted on
/dev/xvda2     ext3       25G   24G     0 100% /
devtmpfs       devtmpfs  3.9G     0  3.9G   0% /dev
tmpfs          tmpfs     3.7G     0  3.7G   0% /dev/shm
tmpfs          tmpfs     3.7G  940M  2.8G  25% /run
tmpfs          tmpfs     3.7G     0  3.7G   0% /sys/fs/cgroup
/dev/xvda1     ext3      240M  109M  119M  48% /boot
```

Running out of disk means the Mesos agent stops, Marathon gets confused and lots of weird stuff happens.

We try to [delete the leftover docker containers manually](http://stackoverflow.com/questions/17236796/how-to-remove-old-docker-containers) but the disk space isn't freed.

I think we're hitting on https://github.com/docker/docker/issues/3182 because of ext3. People say it should be fixed in ext4. Any change we can upgrade?

**Comment by stevendborrelli** [comment]
Thanks for opening this, it has been a problem in some of our clusters. Adding @altvnk and @sehqlr to this issue. 

Here are our plans, please let me know what you think:

1. Deploy a docker cleanup package
   - install in /etc/cron.hourly
   - `docker rm && docker rmi` 
   - docker cleanup volumes

2. Move from loopback to LVM storage for device mapper until overlayfs is in better shape
3. Move /var/lib/docker to an external block device so that it doesn't affect root.

**Comment by eirslett** [comment]
Sounds good to me!

**Comment by emdem** [comment]
@stevendborrelli What we've done in our own cluster and may be a good idea is to set up a chronos task to do this. There's a few ways to cleverly use regular expressions/sorting to only remove unused images.

**Comment by altvnk** [comment]
@loshkovskyi Have ansible playbooks to setup docker storage on separate volume with LVM. We decided that loopbacks if not safe and brings a lot of issues.

Regarding image cleanup: no matter what docker storage type is used, cleanup is still an issue. Here is example Chronos job i've used:

```JSON
{
  "schedule": "R/2015-10-19T20:00:00Z/PT1H",
  "name": "delete_old_containers",
  "ownerName": "Alexander Litvinenko",
  "description": "Deletes exited containers on slaves",
  "owner": "altvnk@me.com",
  "container": {
    "type": "DOCKER",
    "image": "spotify/docker-gc",
    "network": "BRIDGE",
    "volumes": [
      {
        "containerPath": "/var/run/docker.sock",
        "hostPath": "/var/run/docker.sock",
        "mode": "RW"
      },
      {
        "containerPath": "/etc",
        "hostPath": "/etc",
        "mode": "RW"
      }
    ]
  },
  "cpus": "0.1",
  "mem": "64",
  "disk": "",
  "uris": [],
  "command": ""
}
```
The only thing is Chronos don't have appropriate constrains (like Marathon's) to let it run on EVERY slave. So in my case it runs every hour on RANDOM slaves and it's enough for me, but YMMV.

**Comment by emdem** [comment]
@altvnk you can use the mesos rest api to retrieve all workers at:
master-url/master/slaves

it returns json with everything you need

**Comment by altvnk** [comment]
Sure, but if you will try to make all these jobs with the same schedule in Chronos you will face with issue that actually runs only one of them, and it's annoying. Anyway, there is might be another way to do that, i'm finished with this config and pretty happy now.

**Comment by stevendborrelli** [comment]
I'd just like to have the cleanup run on the nodes locally via cron.hourly. That we we only have to drop a few scripts in a directory.

**Comment by altvnk** [comment]
So then it can be simple docker run, check source repo for instructions. That image is pretty smart in removing containers.

**Comment by stevendborrelli** [comment]
We can run a couple of docker images to clean the volumes, so the /etc/cron.hourly scripts can just be a couple of `docker run` commands. 

- spotify/docker-gc
- https://github.com/chadoe/docker-cleanup-volumes (https://hub.docker.com/r/martin/docker-cleanup-volumes/builds/). I've been running this one for a while on two of our clusters.

**Comment by sehqlr** [comment]
Hey all, I've tested out a solution to this issue, following @stevendborrelli's idea with the local cron job. I added it to https://github.com/asteris-llc/mantl-packaging as the `docker-cleanup` package. It uses the `spotify/docker-gc` image, and it removes containers that have exited for more than an hour. This container supports adding text files to `/etc` to build a whitelist of images/containers. 

What do you think?

**Comment by eirslett** [comment]
The error I'm hitting on means you can delete docker containers, but the disk space isn't actually freed. So that has to be solved too.

**Comment by stevendborrelli** [comment]
@eirslett is the space being used in volumes?

**Comment by stevendborrelli** [comment]
@sehqlr 
1. Can we make the volume mount a little more fine-grained? -v/etc/:etc basically gives the container full access to the host configuration. 
2. We'll need to add volume cleanup in addition. Docker 1.9 includes some volume options but until it gets into Centos (might be a few months), we'll need to use a script.

**Comment by sehqlr** [comment]
1. We could just have `/etc/docker-gc:/etc`. That way, we don't need to change the env for the container. I will test this in a different branch.
2. When I was reading this, I realized that the spotify and martin docker containers were doing different things. I've added them both to the script now, and this should fix the volume problem.

**Comment by eirslett** [comment]
> @eirslett is the space being used in volumes?

No, I have no idea what the space was used for actually...

If you look at the docker issue I linked to, a number of people have written instructions on how to reproduce the problem.

(1) check disk info (2) pull/run docker image (3) check disk info (4) remove docker image (5) check disk info. 

Can you reproduce it in your mantl clusters as well?

**Comment by sehqlr** [comment]
@eirslett I was just running through your process, and I ran an additional step of checking my solution. I can show you the numbers if you want. From my tests, my solution works as expected, and so I plan on getting this RPM package in our repo by the end of today.

**Comment by ndelitski** [comment]
Got 100% of disk usage after running in about a day
```
# df -hT
Filesystem     Type      Size  Used Avail Use% Mounted on
/dev/xvda1     ext4       30G   30G     0 100% /
none           tmpfs     4.0K     0  4.0K   0% /sys/fs/cgroup
udev           devtmpfs  3.9G   12K  3.9G   1% /dev
tmpfs          tmpfs     799M  604K  798M   1% /run
none           tmpfs     5.0M     0  5.0M   0% /run/lock
none           tmpfs     3.9G     0  3.9G   0% /run/shm
none           tmpfs     100M     0  100M   0% /run/user
```
docker directories:
```
91M	/var/lib/docker/volumes/
33G	/var/lib/docker/devicemapper/
59M	/var/lib/docker/containers/
```
Downloaded images allocate about 5-6GB at all, volumes only 91M, where is the rest space?
```
# docker info
Containers: 19
Images: 126
Storage Driver: devicemapper
 Pool Name: docker-202:1-398075-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 29.91 GB
 Data Space Total: 107.4 GB
 Data Space Available: 16.78 MB
 Metadata Space Used: 23.99 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 16.78 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-48-generic
Operating System: Ubuntu 14.04.3 LTS
CPUs: 2
Total Memory: 7.797 GiB
Name: ip-172-30-1-53
ID: T2I6:OT4L:GKDK:D6PL:4GEM:AP6E:ECQQ:OBPU:ZNXD:VCDY:4XOX:2HAF
WARNING: No swap limit support

```

**Comment by sehqlr** [comment]
Hey, @ndelitski. I have a solution for this, but unfortunately, I haven't been able to upload my package to our bintray yet. Here is the contents of the cron.hourly job I'm using for it:
```
docker run -v /var/run/docker.sock:/var/run/docker.sock -v /etc/docker-cleanup:/etc/ --rm spotify/docker-gc
docker run -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker:/var/lib/docker --rm martin/docker-cleanup-volumes
```
Try running this command, and it should be able to clean up your disk.

**Comment by ndelitski** [comment]
thix @sehqlr for sharing this scripts, but this didn't much help me... 
before running scripts
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1       40G   18G   20G  48% /
```
after running first
```
df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1       40G   18G   20G  48% /
```
```
$ du -sh /var/lib/docker/*
82M	/var/lib/docker/containers
33G	/var/lib/docker/devicemapper
14M	/var/lib/docker/graph
16K	/var/lib/docker/linkgraph.db
4.0K	/var/lib/docker/repositories-devicemapper
4.0K	/var/lib/docker/tmp
4.0K	/var/lib/docker/trust
91M	/var/lib/docker/volumes
```
after running second
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1       40G   18G   20G  48% /
$ du -sh /var/lib/docker/*
82M	/var/lib/docker/containers
33G	/var/lib/docker/devicemapper
14M	/var/lib/docker/graph
16K	/var/lib/docker/linkgraph.db
4.0K	/var/lib/docker/repositories-devicemapper
4.0K	/var/lib/docker/tmp
4.0K	/var/lib/docker/trust
91M	/var/lib/docker/volumes
```
ohhh thats crazy devicemapper what you doing with me... 
Hey guys! Maybe anyone could share his experience on what docker storage setup is suitable for production(i mean frequent container restarts, parallel starts, high layers speed)? Maybe i should take a look at `direct-lm`(But i don't wanna to attach 100gb disk on every my host)?

**Comment by stevendborrelli** [comment]
We've addressed this issue in a couple of ways:
1. Docker cleanup for containers, images and volumes has been added to 0.5
2. We're using xfs on our docker filesystem

Please make sure you are using the newest kernel.

**Comment by eirslett** [comment]
> Please make sure you are using the newest kernel.

Maybe the ansible playbook should do a sanity check on this, and fail fast if the kernel is older than what is supported?
