### ISSUE TITLE
Increase no files for root from 1024

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#775]
We've had issues on some clusters where hanging processes have caused root to be unable to fork more processes because we hit the default limit.

**Comment by sehqlr** [comment]
Which process is hitting the limit? Nginx?

**Comment by stevendborrelli** [comment]
Consul checks using curl against chronos.

**Comment by sehqlr** [comment]
I was confused on what this was actually talking about, but I spoke with @stevendborrelli in person and I figured it out how. I made a branch `increase-ulimit-root` to add this to ansible's common role. I set the limit to `65000`, but we can set it to something else

**Comment by sehqlr** [comment]
I'm making a reference to the new PR that is still working on this: #802

**Comment by BrianHicks** [comment]
Anything else that needs to happen on this after CiscoCloud/consul-rpm#1 ?

**Comment by sehqlr** [comment]
No, that should cover it.

**Comment by ryane** [comment]
do we have to update the ansible tasks to use the new version of the rpm?

**Comment by ryane** [comment]
fixed by #823
