### ISSUE TITLE
Add timeouts to consul health checks

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#776]
We're seeing hundreds of hung processes due to curls not finishing. Add connect_timeout and max_timeout to curl commands used in marathon and chronos consul health checks. 

`
consul   16907   775  0 03:09 ?        00:00:00 curl --silent --show-error --fail --dump-header /dev/stderr --retry 2 http://127.0.0.1:14400/ping
`

**Comment by stevendborrelli** [comment]
Testing the following settings on one of our clusters: 
```
--connect-timeout 5 --max-time 5 
```

**Comment by eirslett** [comment]
@armon would it be possible for consul to support check timeouts out of the box, even for scripts? (as opposed to pure HTTP health checks, that are already supported today). With lots of checks, it's easy to forget a timeout here and there, some bulkheading would be nice!

**Comment by stevendborrelli** [comment]
Fixed via #786
