### ISSUE TITLE
Move zookeeper container to host networking

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#777]
We've had a number of issues connecting to zookeeper running on the docker bridged network. In particular checks like:
```
[[ "$(echo ruok | nc "$host" 2181 2>/dev/null)"
```

Tend to be unreliable when trying to get status of the zk process from outside the container. 

We should investigate having the container attach to the host network in order to see if it resolves the issue.

**Comment by stevendborrelli** [comment]
One issue is if we move to host networking we'll have to change the launch script to not bind to localhost: https://github.com/CiscoCloud/docker-zookeeper/blob/master/zookeeper-3.4/zk_launch.sh#L64

**Comment by stevendborrelli** [comment]
I think we need to refactor the whole zookeeper deployment, possibly trying 3.5.1 with dynamic configuration.

**Comment by eirslett** [comment]
I still believe it would make sense to run Zookeeper outside of docker entirely, with Exhibitor. Exhibitor doesn't only configure ZooKeeper, it also takes care of health-checking it and so on. I'd love to stand on the shoulders of Netflix, to be sure that the Zookeeper cluster is up and running!

**Comment by ryane** [comment]
as of #873, zookeeper is no longer running in docker so I will close this issue. we have #765 open regarding exhibitor (or zookeeper 3.5.1)
