### ISSUE TITLE
traefik load balancer

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#783]
We've been using [traefik](traefik.github.com) successfully as a replacement for haproxy-consul. 

While haproxy-consul was a good initial effort, we found many operation issues trying to manage the `marathon->marathon-consul->haproxy-consul->haproxy` process.

Edit, moving SSL/Auth to the feature backlog. 
~~- [ ] update traefik to support Marathon Authentication`~~
~~- [ ] update traefik to support not verifying SSL certificates~~

**Comment by BrianHicks** [comment]
Worked around these issues in #821 by creating the `edge` role. These have moved from blockers to nice-to-haves IMO.

**Comment by stevendborrelli** [comment]
@BrianHicks agree, we'll add the auth and SSL for traefik to the feature backlog, and close this when #821 is merged.

**Comment by stevendborrelli** [comment]
Closing now that #821 is merged.
