### ISSUE TITLE
[k8s] Flanneld startup race condition

### ISSUE THREAD

**Issue by Zogg** [CiscoCloud/microservices-infrastructure#795]
## Problem
Flanneld cannot probperly start because of circular dependency between services. Flanneld is dependent on etcd. Flannel needs to start before Docker, Etcd must be started before Flannel, but currently it is started as Docker container. Hence the lockdown.

## Propositions
* One of the workarounds would be to use etcd package from yum repository and not have it launched as a container.

* The other would be to test extensively the ability for Flanneld to keep restarting and waiting until etcd is launched as a container. There might be a case when etcd is not the first container to be launched and prime containers will not get an IP assigned.

**Comment by stevendborrelli** [comment]
I'm for moving etcd out of docker and into a package. That is what we do with consul. I'd rather not have any system-level processes run in Docker.

**Comment by stevendborrelli** [comment]
Just following up on this, both etcd and flannel are available as Centos packages.

**Comment by Zogg** [comment]
Using etcd as centos package: https://github.com/CiscoCloud/microservices-infrastructure/commit/bd38294ac4a10f9cfe72f164cd3ae436192ff80d

**Comment by stevendborrelli** [comment]
@Zogg do you feel like you have this under control now?

**Comment by ryane** [comment]
@zogg can this be closed with bd38294?

**Comment by Zogg** [comment]
Yes.
