### ISSUE TITLE
Node role names should be standardized 

### ISSUE THREAD

**Issue by corebug** [CiscoCloud/microservices-infrastructure#809]
We have different *worker* role names and related variable names in different Terraform scripts, for example `resource_count` in `terraform/openstack-floating.sample.tf` and `worker_count` in `terraform/aws.sample.tf`.
That adds a fair amount of mess when it comes to configuring Mantl for different cloud providers.
I personally would vote for renaming `worker/resource` nodes to `worker` nodes and refactoring variable names to make that clear.

@stevendborrelli what do you think?

**Comment by stevendborrelli** [comment]
I agree, we should target this for the 0.6 (December 2015) release.

**Comment by eirslett** [comment]
+1 for "worker" everywhere!
