### ISSUE TITLE
Terrform AWS fails due to invalid attachment

### ISSUE THREAD

**Issue by BrianHicks** [CiscoCloud/microservices-infrastructure#819]
Using the default AWS Terraform configuration, I get the following error:

```
Error applying plan:

1 error(s) occurred:

* aws_volume_attachment.mi-worker-nodes-lvm-attachment.2: [WARN] Error attaching volume (vol-df46fb17) to instance (i-5f1190a6), message: "Invalid value 'xvdh' for unixDevice. Attachment point xvdh is already in use", code: "InvalidParameterValue"
```

It's always the second worker, too. I have 2, so perhaps it's just the last one.

**Comment by ryane** [comment]
If you are running with 3 control nodes and 2 workers, it looks like this might be #816 which should be fixed in master.

**Comment by BrianHicks** [comment]
Yep, duplicate. Thanks for your help. :+1:
