### ISSUE TITLE
Feature request: support for Apache CloudStack

### ISSUE THREAD

**Issue by bbaassssiiee** [CiscoCloud/microservices-infrastructure#82]

**Comment by stevendborrelli** [comment]
Our plans are to move to terraform for host/network provisioning (as soon as the openstack provisioner is merged in). 

It looks like Cloudstack is supported in terraform: https://www.terraform.io/docs/providers/cloudstack/index.html 

Would you be interested in helping get a configuration together with Terraform to speed up the integration? I think we might have other cloud backends like AWS & GCE as higher priorities.

**Comment by bbaassssiiee** [comment]
Could this help? https://github.com/bbaassssiiee/simstack

**Comment by keithchambers** [comment]
I've just added Apache CloudStack to the roadmap!

This feature will depend on a few things:
* Migrating this project to use Terraform for provisioning
* Community implement of Terraform templates for CloudStack
* Community testing of Terraform templates for CloudStack

@bbaassssiiee will you be able to help with the implementation and testing?

**Comment by bbaassssiiee** [comment]
Implementation: no
Testing: I would need to ask

Bassie

**Comment by siddharthist** [comment]
We now use Terraform. There is also a Terraform Cloudstack provider: 

https://terraform.io/docs/providers/cloudstack/index.html

**Comment by stevendborrelli** [comment]
Is there any interest in this? I'm going to close this ticket, as we don't have the resources to test against this cloud provider. 

Please reopen if you want to add support via a PR.

**Comment by bbaassssiiee** [comment]
I no longer have test resources.
