### ISSUE TITLE
Simplify Terraform DNS configurations

### ISSUE THREAD

**Issue by BrianHicks** [CiscoCloud/microservices-infrastructure#822]
The current DNS configuration modules reflect an older view of how the project needs to be connected up. Namely, we get records like this:

| type | IP | name |
|-------|-----|---------|
| A | `10.10.10.1` | `shortname-control-01.yourdomain.com` |
| A | `10.10.10.2` | `shortname-control-02.yourdomain.com` |
| A | `10.10.10.3` | `shortname-control-03.yourdomain.com` |
| A | `10.10.10.4` | `shortname-worker-001.yourdomain.com` |
| A | `10.10.10.4` | `*.shortname-lb.yourdomain.com` |

This made sense when we needed to connect to a specific control node for tasks, but since we have Mantl UI now, we can connect to any node. We also don't need to connect to worker nodes anymore as of #821, we now connect to edge nodes.

So I'd propose our DNS config should look like this:

| type | IP | name |
|------|----|------|
| A | `10.10.10.1` | `control.yourdomain.com` |
| A | `10.10.10.2` | `control.yourdomain.com` |
| A | `10.10.10.3` | `control.yourdomain.com` |
| A | `10.10.10.5` (edge-01) | `*.yourdomain.com` |

This should have a configurable subdomain, so if you want `control.mantl.yourdomain.com`, you could have that.

Thoughts?

**Comment by BrianHicks** [comment]
Moving this to 0.5 because when we merge Traefik support, it will mean that the current DNS is invalid. It needs to change *somehow*.

**Comment by BrianHicks** [comment]
Another option inspired by @stevendborrelli:

| type | IP | name |
|------|----|-------|
| A | `10.10.10.1` | `control-01.yourdomain.com` |
| CNAME | `control-01.yourdomain.com` | `control.yourdomain.com`
| A | `10.10.10.5` | `edge-01.yourdomain.com` |
| CNAME | `edge-01.yourdomain.com` | `*.yourdomain.com` |

**Comment by stevendborrelli** [comment]
I don't know if you can CNAME on a wildcard and you can't have a CNAME on multiple A's. 

| type | IP | name |
|------|----|-------|
| A | `10.10.10.1` | `control.yourdomain.com` |
| A | `10.10.10.2` | `control.yourdomain.com` |
| A | `10.10.10.3` | `control.yourdomain.com` |

**Comment by ryane** [comment]
@eirslett any thoughts on this? since you started the dns support for mantl, would love to get your input

**Comment by eirslett** [comment]
We use DNS to SSH into the control/worker/edge nodes as well - that's pretty useful. When there's a DNS record with the same name as `hostname --fqdn` that also plays along well with the Marathon and Mesos UIs, since they give you links based on the hostnames. (For example a direct link to a marathon task running on a worker on some random port)

**Comment by BrianHicks** [comment]
That's a good point. Well, how about these three changes:

1. each node gets their own A record (adding edge)
2. all control nodes have an A record at `control.{domain}`
3. the * record changes to the edge nodes

This combines what we've got now with what's worked before. Any objections.

**Comment by ryane** [comment]
sounds good to me

**Comment by eirslett** [comment]
It's just nr. 3 I'm not so sure about, the wildcard... I think it's too generic/top-level. It will probably conflict with other, existing wildcard records people already have. Someone who runs example.com could register *.example.com and point it to an apache server that is set up with virtualhosts. Then they wouldn't be able to use Mantl because of that conflict.

**Comment by BrianHicks** [comment]
Yes, I agree. That's why I suggested adding a subdomain (forgot to add that to the list in the comment, sorry.) By default this would probably be like "apps" or "mantl". So the records would actually be (for example) `*.mantl.yourdomain.com` and `control.mantl.yourdomain.com`. This has been useful for testing multiple clouds, since I set the subdomain to something like `gce.mantl` or `aws.mantl` for a consistent name for my tests.

**Comment by eirslett** [comment]
That's pretty much what the existing DNS setup does; *.[shortname]-lb.[domain], so we have:
*.mantl-dev1-lb.finn.no
*.mantl-dev2-lb.finn.no
*.mantl-ci1-lb.finn.no
Where the "short names" are "mantl-dev1", "mantl-dev2" etc.
(We have multiple environments where every environment has 2 data centers)
Maybe we could drop the -lb part of it?

Another option is to just skip the wildcard record altogether, and let users define it for themselves. I think that's the best.

**Comment by BrianHicks** [comment]
I'm afraid I'm struggling to understand why you would want it that way. In that case, you would have to define two separate haproxy domains, and have an implementation detail in the name you give to consumers. Having a more generic wildcard resolves that. When you have your consumer app running, you just have to give `app.mantl.example.com` to your user-facing code, and they'll connect regardless of how many edge servers you actually have.

**Comment by eirslett** [comment]
I'm not sure if we're talking about the same thing, or the same use cases.
For routing internal traffic between applications via haproxy/traefik, we would give them an url like "myapp.worker/foo/bar" and ".worker" would be a dnsmasq wildcard record pointing to the local loadbalancer, running on the same worker as the consumer. (That dns record isn't in the upstream code base, maybe it should?) So in this case a consumer would be a microservice talking to another microservice internally. (Are we talking about the same thing here?)

For end users, we want pretty urls, like http://finn.no, http://www.finn.no (and http://dev.finn.no), but http://someotherapp.finn.no might not run on mantl at all. Letting mantl add a top-level wildcard DNS record feels a bit too risky in my opinion, especially in a situation where you already have ~200 DNS records on that level that might conflict.

**Comment by BrianHicks** [comment]
Yeah, we're definitely talking about separate use cases. I'm talking about routing traffic in externally, or through an ELB or equivalent. The edge nodes soak up traffic so the worker nodes don't get saturated.

The internal use case is interesting, and something we should give some consideration. The recommendation now is to use Consul DNS to route to `myapp.service.consul` and so on. Obviously that doesn't do ports, though, so I wonder if we would be able to adapt Traefik to do internal load balancing like that. Could be a good fit, it has nice circuit breakers as well as load balancing. I like the idea of being able to route to `elasticsearch.worker` and having the ports taken care of for me.

I agree that we want pretty URLs for end users, which is why you can override the Host that Traefik matches on. Then it would be a pretty simple matter to put an A record from `dev.finn.no` (in your case) pointing at Traefik on the edge node. So no, the wildcard record is not strictly required, but handy for people to get a start with. I've configured all the providers to be able to specify a subdomain on all the records to avoid collisions. So for example, if you were configuring finn.no with a development cluster, and wanted everything available on dev.mantl.finn.no, the subdomain would be `.dev.mantl` and all the records we've discussed here would be suffixed with that subdomain. (EG `control.dev.mantl.finn.no` and `*.mantl.finn.no`.) Again, Traefik's finer-grained control over routing information is useful here, as we can exclude certain Marathon apps from external routing.

Unfortunately, we don't have conditionals in Terraform. Once (if) they add those in, we should definitely make the wildcard records optional, as they're not useful in all use cases.

**Comment by eirslett** [comment]
> The recommendation now is to use Consul DNS to route to myapp.service.consul and so on.

That works in many cases, but relies on well-behaved clients (they must do load balancing right, honor DNS timeouts etc) and we lose the ability to collect traffic statistics, which in turn means the load balancing algorithms cannot be as smart as haproxy or traefik's.

I lalways assumed that the haproxy/traefik instances running on every worker node was meant for this use case, internal load balancing? I guess I was wrong :stuck_out_tongue:

**Comment by BrianHicks** [comment]
Yeah, they're intended for external routing. The internal case is really
interesting though, like I said. Would you mind please opening a ticket
about that? It seems like it would be a really good thing to have.

**Comment by Zogg** [comment]
One technical nuance: just have in mind, that when serving dns request over udp, the dns server will reply with AT MOST 3 records. Say in the future you want to have 5 control nodes, dns will still reply with 3 records, leaving 2 random servers not listed. In some use-cases this is very much undesirable. 
The remedy is to query dns server over tcp.
