### ISSUE TITLE
Replace consul-rpm with hammer-built package

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#825]
We are currently using: https://github.com/CiscoCloud/consul-rpm to build the consul and consul-ui rpms.

As part of our CI workflow, migrate to using the package built at https://github.com/asteris-llc/consul-packaging

**Comment by stevendborrelli** [comment]
Moving this to 0.6 release as per PR #900.

**Comment by siddharthist** [comment]
Has our RPM been moved to https://github.com/asteris-llc/mantl-packaging? If not, should it be?

**Comment by ryane** [comment]
I *think* this can be closed with #1000 but not 100%. @stevendborrelli @ChrisAubuchon or @BrianHicks can you confirm?

**Comment by ChrisAubuchon** [comment]
It can be closed. https://github.com/CiscoCloud/microservices-infrastructure/pull/1000 uses the hammer built packages
