### ISSUE TITLE
Feature Request: Two tier web app example

### ISSUE THREAD

**Issue by PeterLamar** [CiscoCloud/microservices-infrastructure#83]
Data storage is a challenging topic, a basic django app/mysql backend example would be great for the masses

**Comment by keithchambers** [comment]
I agree with @PeterLamar that we need to start thinking of data services.

Ideally our first data service would be Cassandra since it supports multi-dc replication.

I'm wondering if we'd want to run Cassandra on Marathon or as a proper Mesos framework: e.g., https://github.com/mesosphere/cassandra-mesos/tree/rewrite

@stevendborrelli thoughts?

**Comment by PeterLamar** [comment]
You guys are on top of it! I agree that Cassandra is an awesome tool that tells a beautiful story. I personally would love to use Cassandra for everything. 

MySQL has 10x the usage though :/

http://db-engines.com/en/ranking

Either way, a data service example would be awesome.

**Comment by BrianHicks** [comment]
we might be able to deploy [twissandra](https://github.com/twissandra/twissandra) as part of this, being a well-understood example app.

@keithchambers we'll probably want to run the Cassandra framework inside of Marathon when we add it - better HA story.

**Comment by PeterLamar** [comment]
I am trying to spin up a mysql db. It starts and then just dies, and I don't know have to access the logs. Any ideas?

Hello-mysql.json

{  
   "container":{  
      "type":"DOCKER",
      "docker":{  
         "network":"BRIDGE",
         "image":"mysql",
         "volumes":[  
            {  
               "containerPath":"/var/lib/mysql",
               "hostPath":"/var/lib/mysql",
               "mode":"RW"
            }
         ]
      }
   },
   "args": ["-e MYSQL_ROOT_PASSWORD=mysecretpassword"],
   "id":"mysql",
   "instances":1,
   "cpus":0.1,
   "mem":128
}

**Comment by PeterLamar** [comment]
Hmm, logs:

E0312 22:02:17.386908  4526 slave.cpp:2344] Failed to update resources for container 5b923266-7052-4d8f-a996-3f8c4c885bfe of executor mysql.71267cdd-c903-11e4-94f5-46d4b8ddf076 running task mysql.71267cdd-c903-11e4-94f5-46d4b8ddf076 on status update for terminal task, destroying container: Failed to determine cgroup for the 'cpu' subsystem: Failed to read /proc/30154/cgroup: Failed to open file '/proc/30154/cgroup': No such file or directory

E0312 22:00:25.851837  4524 slave.cpp:2787] Container '2593daa5-4a76-43a7-b28d-35a87734479f' for executor 'mysql.0c
561392-c903-11e4-94f5-46d4b8ddf076' of framework '20150309-042445-2145396653-5050-5298-0000' failed to start:  futu
re discarded
E0312 22:00:25.852169  4524 slave.cpp:2344] Failed to update resources for container 2593daa5-4a76-43a7-b28d-35a877
34479f of executor mysql.0c561392-c903-11e4-94f5-46d4b8ddf076 running task mysql.0c561392-c903-11e4-94f5-46d4b8ddf0
76 on status update for terminal task, destroying container: Failed to 'docker inspect mesos-2593daa5-4a76-43a7-b28
d-35a87734479f': exit status = exited with status 1 stderr = Error: No such image or container: mesos-2593daa5-4a76
-43a7-b28d-35a87734479f

**Comment by keithchambers** [comment]
@PeterLamar are you still working on this enhancement?

**Comment by npateriya** [comment]
@PeterLamar one of sample mysql marathon json that we are deploying on ms-infra. Refer env section, I suspect root password env not set on container leading to crash . Below does not have volume mount though. 
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "mysql",
      "network": "BRIDGE",
      "portMappings": [ { "containerPort": 3306, "protocol": "tcp"} ]
    }
  },
  "id": "shipped-api-mysql",
  "instances": 1,
  "cpus": 1,
  "mem": 1024,
  "env": {
      "MYSQL_ROOT_PASSWORD": "********",
      "MYSQL_DATABASE": "shippeddb",
      "MYSQL_USER": "shippeduser",
      "MYSQL_PASSWORD": "*******"
  }
}

**Comment by keithchambers** [comment]
@BrianHicks I definitely want to add a Cassandra framework in the future.

**Comment by PeterLamar** [comment]
@npateriya Thanks! I managed to get it working with a json almost the same as yours. 

@keithchambers I am working on it, slowly though

**Comment by keithchambers** [comment]
@PeterLamar no rush. :+1:

**Comment by PeterLamar** [comment]
Duplicated elsewhere, closing.

**Comment by ObjectiveJoe** [comment]
I think this area is one of the most important we need to expand in order to be able to offer real customer solutions! I hope this is at the top of someone's list. :)

**Comment by PeterLamar** [comment]
Matt asks for this as well in his issue
https://github.com/CiscoCloud/microservices-infrastructure/issues/475
