### ISSUE TITLE
Question: Vagrant developer env also bumped to 0.5-RC1?

### ISSUE THREAD

**Issue by matjohn2** [CiscoCloud/microservices-infrastructure#840]
@ryane 

Could we ensure the Vagrant deployment covered in the docs is also bumped to 0.5-RC1? 
Interest shown and would like to make sure they can test easily w/the new release.

Is this currently the case or does it involve work?
Matt

**Comment by ryane** [comment]
the vagrant build should work with 0.5-RC1. we pushed an updated vagrant image earlier this morning.

**Comment by ryane** [comment]
@matjohn2 did that answer your question?

**Comment by BrianHicks** [comment]
Instructions for upgrading are in the release notes. I'm going to go ahead and close this.
