### ISSUE TITLE
mantlui: back button doesn't go back from Consul web UI

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/microservices-infrastructure#841]
I'm not sure if there's anything we can do about this, but hitting the back button in Chrome won't return you to the mantlui page if you've gone into the Consul UI from there. Thoughts @ryane?

**Comment by ryane** [comment]
Consul issues a 301 redirect to /ui. So, if you hold down the back button, you should see Mantl as the second entry. I think we can just change the link to go directly to /consul/ui/ to fix it. 

I opened an issue in the mantlui repo: https://github.com/CiscoCloud/nginx-mantlui/issues/3
