### ISSUE TITLE
CentOS 7.2 support

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#846]
See: http://seven.centos.org/2015/11/rhel-7-2-released-today/

Investigate making  CentOS 7.2 the minimum supported distribution. 

Notable features:
Better OverlayFS support 
----------------------------------
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html

⁠Improved performance of Open vSwitch tunneling
------------------------------------------------------------------

The tx-nocache-copy device feature is now disabled by default. The previous default created a significant overhead for many workloads and particularly for OVS tunnels running over a VXLAN.

⁠SELinux policy for Red Hat Gluster Storage has been added 
---------------------------------------------------------------------------------

Previously, SELinux policy for Red Hat Gluster Storage (RHGS) components was missing, and Gluster worked correctly only when SELinux was in permissive mode. With this update, SELinux policy rules for the glusterd (glusterFS Management Service), glusterfsd (NFS sever), smbd, nfsd, rpcd, adn ctdbd processes have been updated providing SELinux support for Gluster.

⁠User namespace 
-----------------------

This feature provides additional security to servers running Linux containers by providing better isolation between the host and the containers. Administrators of a container are no longer able to perform administrative operations on the host, which increases security.

**Comment by stevendborrelli** [comment]
Starting to hit the mirrors, should be announced the week of 12/14: http://mirror.centos.org/centos/7.2.1511/

**Comment by stevendborrelli** [comment]
This is going to be required for 0.6.

**Comment by ryane** [comment]
on gce, switch to 7.2 by default in #1015

**Comment by siddharthist** [comment]
AFAICT, we've supported 7.2 for a while, it is simply a matter for requiring now. We can do so by adding a `fail` task to `terraform.sample.yml`, in the same vein as our discussion on #806.
