### ISSUE TITLE
Update README Graphics

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/microservices-infrastructure#848]
It looks like the graphics in our README are outdated, they still show HAProxy as the proxy layer. We should update them!

Do we want to include more of our newer components in the graphics as well?

**Comment by ryane** [comment]
I think we should. Anyone know if we have the original graphics so we don't have to recreate from scratch?

**Comment by stevendborrelli** [comment]
I have them. They are in Keynote format.

**Comment by ryane** [comment]
please send to me when you get a chance

**Comment by stevendborrelli** [comment]
@ryane they are in the repo under  `docs/_static/diagrams.key`.

**Comment by siddharthist** [comment]
We should consider uploading a more widely used format, while we're at it!
