### ISSUE TITLE
Implement Consul ACLs

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#85]
Create a role to set up initial Consul ACLs

references:
http://www.consul.io/docs/internals/acl.html
http://www.consul.io/docs/agent/http/acl.html
http://python-consul.readthedocs.org/en/latest/#example-uses
https://www.mauras.ch/securing-consul.html

**Comment by stevendborrelli** [comment]
Basic consul ACL's have been added. We're developing a tool that will allow ACL management via command line, which can then be integrated with cluster provisioning.

**Comment by siddharthist** [comment]
Related: PR #603

**Comment by stevendborrelli** [comment]
This is a large enough change we are going to push to 0.5

**Comment by ryane** [comment]
fixed in #603
