### ISSUE TITLE
Review open source licenses

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#858]
Go through each of the components in mantl and understand the license it is released under. 

Create a documentation page that contains each component, license used and a link to its license

**Comment by TanyaCouture** [comment]
Are there components not covered by Apache Version 2.0?

**Comment by stevendborrelli** [comment]
Yes, for example terraform is MPL 2.0. 

https://github.com/hashicorp/terraform/blob/master/LICENSE

**Comment by TanyaCouture** [comment]
#884

**Comment by ryane** [comment]
I believe this is addressed by the merge of #1007.
