### ISSUE TITLE
containers cannot write to glusterfs volumes

### ISSUE THREAD

**Issue by ryane** [CiscoCloud/microservices-infrastructure#867]
On platforms with selinux enforcing, containers cannot write to the glusterfs directory (`/mnt/container-volumes/` by default). Marathon does not currently support using the `:z` or `:Z` [Docker volume labels](https://docs.docker.com/engine/userguide/dockervolumes/#volume-labels).

thanks for pointing this out @siddharthist

**Comment by siddharthist** [comment]
Related: https://github.com/mesosphere/marathon/issues/2497

**Comment by stevendborrelli** [comment]
It looks like this is an issue in the mesos protobuf:
https://github.com/mesosphere/marathon/blob/master/src/main/proto/mesos/mesos.proto#L1323

Which means we have to update mesos itself: 
https://github.com/apache/mesos/blob/master/include/mesos/mesos.proto#L1334

**Comment by stevendborrelli** [comment]
Related: https://issues.apache.org/jira/browse/MESOS-3776?jql=project%20%3D%20MESOS%20AND%20text%20~%20volume

**Comment by justinclift** [comment]
Creating an SELinux rule to allow the access at this filesystem location should work shouldn't it?

From memory (a long time ago), it's not hard to create these rules on at least CentOS/RHEL based systems.

**Comment by ryane** [comment]
I was thinking along the same lines but not having much luck so far:

```
$ sudo chcon -Rt svirt_sandbox_file_t /mnt/container-volumes/
chcon: failed to change context of ‘internal_op’ to ‘system_u:object_r:svirt_sandbox_file_t:s0’: Operation not supported
chcon: failed to change context of ‘.trashcan’ to ‘system_u:object_r:svirt_sandbox_file_t:s0’: Operation not supported
chcon: failed to change context of ‘/mnt/container-volumes/’ to ‘system_u:object_r:svirt_sandbox_file_t:s0’: Operation not supported
```

I suspect we might have to set the context when mounting the volume? But, no luck there either:

```
$ sudo mount -t glusterfs fs.glusterfs.service.consul:/container-volumes /mnt/container-volumes -o context="system_u:object_r:svirt_sandbox_file_t:s0"
Invalid option: context
```

It looks like this [unanswered post](http://www.gluster.org/pipermail/gluster-users.old/2015-January/020014.html) might be related but I'm a little out of my depth on this one. Anybody have any ideas? I will ask on the gluster mailing list as well.

**Comment by ryane** [comment]
looks like it might be a bug: https://bugzilla.redhat.com/show_bug.cgi?id=1252627

**Comment by justinclift** [comment]
That's a bug report, but it doesn't appear to have gotten traction with being looked at. @vbellur, would you be ok to get someone to look at BZ 1252627?

**Comment by ryane** [comment]
@justinclift thanks for helping so much with this

**Comment by ryane** [comment]
"at the moment SElinux contexts on Gluster mount points is not possible yet. ": see http://www.gluster.org/pipermail/gluster-users/2015-November/024456.html

It seems like this is a fundamental problem with GlusterFS and SELinux. Even if marathon/mesos supported `:z`, it wouldn't help us.

**Comment by siddharthist** [comment]
What's the next step? Should we set SELinux to permissive while we wait for upstream changes? Do we (can we) have an Ansible variable like `do_selinux` that enables/disables it with just a switch?

**Comment by justinclift** [comment]
Sounds like permissive is the way to go for now.  Not great. :frowning:

**Comment by stevendborrelli** [comment]
So to summarize, we have 2 SELinux problems now, right? 

1. GlusterFS (this ticket)
2. Docker Volumes + upstream support in Mesos & Marathon.

Is that right? Gluster can be an optional component that turns off SELinux, but I don't think we can work around docker.

**Comment by ryane** [comment]
For 2. We could create a specific directory on the host for docker volumes that has the right Selinux context set. The :z option wouldn't be needed in that case. 

Sent from a mobile device

    _____________________________

**Comment by ryane** [comment]
setting selinux to permissive mode is the only option as of right now: http://www.gluster.org/pipermail/gluster-users/2015-November/024476.html
