### ISSUE TITLE
Move management of secrets out of Ansible

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#87]
Move management of secrets out of Ansible to facilitate migration to HashiCorp Atlas.

Requirements:
* Create a design documentation prior to implementation
* Must include all secrets, keys, certificates or system and user accounts

Miscellaneous notes and considerations:
* The current thinking to move secrets from Ansible to consul with consul-template
* How will we expose secret management with consul? Should we develop our new REST API to abstract consul implementation?  If so, do we need to develop a CLI consumer of the our new REST API to simplify human administration?

**Comment by brism** [comment]
I believe you're familiar but I'll add a note for using Vault, the newly released tool from Hashicorp: https://vaultproject.io. I believe it would integrate well with your current stack.

**Comment by siddharthist** [comment]
We're tracking secret management with vault in #859
