### ISSUE TITLE
terraform use *required*?

### ISSUE THREAD

**Issue by tonybecker** [CiscoCloud/microservices-infrastructure#876]
So, I was going to set this up on three bare-metal nodes, and I don't see a way to specify to the scripts that I'm *not* using a cloud provider. I set provider=metal in my hosts: all / vars section in my playbook just so it wouldn't complain about provider being undefined (which it first encounters in the LVM task.)

However, it bombs out a few steps later with the following error, and I'm not sure how to work around it:

TASK: [docker | configure docker consul dns] ********************************** 
fatal: [10.x.x.x] => One or more undefined variables: 'private_ipv4' is undefined

Am I missing something?

**Comment by stevendborrelli** [comment]
Terraform is not required, but the script in `plugins/inventory/terraform.py` does populate ansible vars. 

You can create a manual ansible inventory file and include the extra vars.  For example:
```
[role=control]
control-01 private_ipv4=192.168.0.10
```

**Comment by siddharthist** [comment]
[Here's the output of terraform.py](http://pastebin.com/raw.php?i=bvXFdu70) for a standard openstack cluster, build recently, in case that's helpful! Some fields have been deleted.

**Comment by stevendborrelli** [comment]
@tonybecker let's track this in #847.
