### ISSUE TITLE
Comprehensive security design and documentation

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#88]
We need to create a holistic design document for microservices-infrastructure project.

The design document needs to include both system level and user level authentication / authorization and encryption.

Below are some high level notes compiled from research and offline conversations:

System level:

* Need to generate all these for each system before initial deploy
  * Automatically called by Ansible before first deployment
  * Where will keys be stored?

* Consul
  * TLS (Self signed)
  * Gossip

* Mesos frameworks and principals
  * Slaves to Master
  * Marathon to Mesos

* ZooKeeper
  * ZK auth
  * stunnel

User level:

  * OS users
    * Admin role

  * Mesos ACL
    * Admin role
    * User role

  * Marathon user auth
    * User role

  * Consul
    * User role
      * read only (Nginx HTTP GET)

How will we expose all of this:

  * Options
    * REST API
    * CLI (that consumes the REST API)
    * Not API (go straight to Consul)

**Comment by keithchambers** [comment]
Comments on Steve's new [security document](https://github.com/CiscoCloud/microservices-infrastructure/blob/0.2-dev/docs/security/security.rst):

* Overall the new security doc looks great.

* Generally speaking how do you feel about our ability to secure the platform against unauthorized remote execution?  You might add a little commentary in this area.

* "Disable consul exec (version 0.2)”: It might be good to add your reasoning to the doc. Perhaps we make it simple to enable/disable consul exec via a parameter exposed in Ansible/Terraform?  I was imagining some powerful use cases for consul exec in the future but I also struggle with the power to do harm at scale since the process runs as root.

* Do you want to create new issues for each of the 0.2 security enhancements not yet implemented to track progress?

**Comment by stevendborrelli** [comment]
1) From what I see the main vectors to running tasks are the mesos leaders, marathon (and any other unsecured frameworks), docker http client and consul exec. I think we can reasonably lock those down for uses behind a firewall. Mesos probably has the weakest controls now, we can put nginx in front of the others and disable consul exec. 

2) For consul exec, I don't really understand the security model around it yet, which is one of the reasons we want to disable it until https://github.com/hashicorp/consul/issues/532 is remediated. 

3) We'll add issues for the fixes that we need to add.

**Comment by keithchambers** [comment]
I'm going to close this issue since we will be merging dev-0.2 in to master any day.  We can iterate on security design documentation as needed going forward. Great job Steve!
