### ISSUE TITLE
cronjobs not added to trigger logrotate

### ISSUE THREAD

**Issue by githubber84** [CiscoCloud/microservices-infrastructure#889]
While logrotate role is added to rotate logs of mesos, docker and zookeeper, cronjobs are not being created. So logrotate does not actually get triggered.

**Comment by sehqlr** [comment]
@githubber84 Hey there. @TanyaCouture and I started looking at this today, and I wanted to apologize for not getting back to you sooner. 

The files in the logrotate role get added to `/etc/logrotate.d` and set to trigger daily. logrotate itself is a cronjob that loads config from that directory and from `/etc/logrotate.conf`. So, the jobs should be triggered daily, based on that configuration. Is that broken on your setup?

**Comment by githubber84** [comment]
Oh yes thats right. My mistake. I missed the "include /etc/logrotate.d" in /etc/logrotate.conf file.
