### ISSUE TITLE
No Mesos debug info on Openstack deployment

### ISSUE THREAD

**Issue by PeterLamar** [CiscoCloud/microservices-infrastructure#89]
I get this:

![screen shot 2015-03-13 at 2 30 24 pm](https://cloud.githubusercontent.com/assets/5984638/6647697/6e5d0f0a-c98e-11e4-9c29-9d171249ecdc.png)

And I was hoping for this:

http://dw8zztroqvu2r.cloudfront.net/assets/learn/debugging/mesos-console-slave-a451a156c6727fc96bd6502275c34787.png

**Comment by stevendborrelli** [comment]
From the screenshot it looks like: 

- no master is elected
- none of the followers have registered as compute resources

We may have to look at a few things to figure out what is going on.

Can you make sure:

1) that zookeeper is running on the control nodes
2) That mesos components can resolve each other's IPs

Log files for both masters and slaves are in `/var/log/mesos`.

**Comment by PeterLamar** [comment]
Found the logs, thanks! I'll return to the UI later, there is plenty of debugging to do at /var/log/mesos.
