### ISSUE TITLE
Move consul to install via rpm

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#90]
There looks to be a pretty solid RPM spec for consul at https://github.com/tomhillable/consul-rpm.git. Let's get rid of the manual install in the consul role and replace it with an rpm. 

- [x] fork and make any changes needed to upstream package repo
- [x] upload rpm to bintray (I have an account set up)
- [x] consul role: change tasks to install rpm
- [x] consul role: change data directory to `/var/lib/consul`
- [x] consul role: change ui directory to `/usr/share/consul-ui`
- [x] consul role: ensure that /etc/sysconfig/consul doesn't conflict with our json settings

**Comment by stevendborrelli** [comment]
Uploaded basic packages to https://bintray.com/asteris/rpm/consul/0.5.0/view

**Comment by ChrisAubuchon** [comment]
Moved to RPM install
