### ISSUE TITLE
Checksum not match when enable GlusterFS community repo

### ISSUE THREAD

**Issue by mcapuccini** [CiscoCloud/microservices-infrastructure#904]
Hi, I am trying to provision my MANTL cluster on OpenStack. However, task "glusterfs | enable community repo" fails. Is that a bug? 

TASK: [glusterfs | enable community repo] ************************************* 
failed: [mi-control-01] => {"failed": true}
msg: The SHA-256 checksum for /etc/yum.repos.d/glusterfs-epel.repo did not match 2e2e85fe728b04d19be098b218bd70e304bc33bdf55cbdb8ab86b9d65e7d8538; it was ee06398d5b09d230fa3ffad4995b83089012a426265741c58a70bf587d14613c.
failed: [mi-control-02] => {"failed": true}
msg: The SHA-256 checksum for /etc/yum.repos.d/glusterfs-epel.repo did not match 2e2e85fe728b04d19be098b218bd70e304bc33bdf55cbdb8ab86b9d65e7d8538; it was ee06398d5b09d230fa3ffad4995b83089012a426265741c58a70bf587d14613c.

FATAL: all hosts have already failed -- aborting

**Comment by stevendborrelli** [comment]
@mcapuccini thanks for opening this issue. Can you do a pull an try again? We just merged in https://github.com/CiscoCloud/microservices-infrastructure/pull/898 a little over an hour ago. 

If you don't want to do a new pull, the checksum is in `roles/glusterfs/defaults/main.yml`. Please update the value to `glusterfs_repo_sha256sum`

**Comment by mcapuccini** [comment]
@stevendborrelli Thanks for the fast answer. I checked out 0.5.0, shall I checkout the master branch before the pull?

**Comment by stevendborrelli** [comment]
You can just update the checksum instead of updating (even though we try to keep master stable). 

With the release of Centos 7.2 today, we're looking at using the new SIG packages https://wiki.centos.org/SpecialInterestGroup/Storage, which should reduce these kinds of issues.

**Comment by stevendborrelli** [comment]
This has been merged into master via #898.

**Comment by mcapuccini** [comment]
After running 

sed -i -e "s/2e2e85fe728b04d19be098b218bd70e304bc33bdf55cbdb8ab86b9d65e7d8538/ee06398d5b09d230fa3ffad4995b83089012a426265741c58a70bf587d14613c/g" roles/glusterfs/defaults/main.yml 

it worked. Thanks!
