### ISSUE TITLE
failing health checks: This account is currently not available

### ISSUE THREAD

**Issue by ryane** [CiscoCloud/microservices-infrastructure#907]
When you build a new cluster, most of the consul health checks fail with the error:

```
This account is currently not available.
```

This appears to be because the shell for the `consul` user is set to `/sbin/nologin`. However, it is not clear why this is suddenly broken so we need to track down what has changed. This is affecting master and previous releases.

**Comment by ryane** [comment]
master is fixed by #908. tagged releases are still broken

**Comment by stevendborrelli** [comment]
Given that 0.5.1 is released, I think we can close this.
