### ISSUE TITLE
Install consul-ui on consul server nodes?

### ISSUE THREAD

**Issue by keithchambers** [CiscoCloud/microservices-infrastructure#93]
I noticed we install consul-ui on consul server and client nodes.  I'm thinking we only want to install consul-ui on consul server nodes.

I'll tag this as a `question` for now but if the team agrees let change this to an `enhancement`.

**Comment by stevendborrelli** [comment]
I think it's a bug. It should only be on servers.

**Comment by keithchambers** [comment]
OK I've switched the tag to `bug` and added it for 0.2.

**Comment by stevendborrelli** [comment]
Fix in https://github.com/CiscoCloud/microservices-infrastructure/commit/58ea198. Initial tests seem good, but keeping this open for further testing.

**Comment by stevendborrelli** [comment]
Marking as closed.
