### ISSUE TITLE
mesos | create zookeeper acl failure 

### ISSUE THREAD

**Issue by Btlyons1** [CiscoCloud/microservices-infrastructure#962]
I am getting errors at the Task: [mesos | create zookeeper acl] on OpenStack instances. 

stderr: 2016-01-06 16:25:09 FATAL zk: could not connect to a server
msg: Task failed as maximum retries was encountered

**Comment by siddharthist** [comment]
I'm sorry you're having difficulties! We'll need some more information to help out. 
1. What version of Mantl/Mesos/ZK are you using? 
2. Is ZooKeeper running on any/all of your control nodes? 
3. Can you try connecting to ZK manually? 
4. Have you made any changes to `terraform.sample.yml`?
5. Are you building a new cluster, or upgrading an existing one?

**Comment by Btlyons1** [comment]
I am using the most current version 0.5.1 and ZooKeeper will be running on all of the control nodes. I have not tried connect manually.  No, I did not make any changes to the terraform.sample.yml. Building a new cluster.

**Comment by siddharthist** [comment]
@Btlyons1 Please try connecting manually to the ZK instance and posting your output here. For an example, see [our health check](https://github.com/CiscoCloud/microservices-infrastructure/blob/master/roles/zookeeper/files/zookeeper_check.sh).

**Comment by Btlyons1** [comment]
I do not have any ZK instances running on my openstack instances.

**Comment by Btlyons1** [comment]
Can anyone else provide any help on this issue?

**Comment by Btlyons1** [comment]
The issue was due to our local DNS not reflecting the right IP addresses for the OpenStack instances. Thus, zookeeper could not connect to the servers. The initial problem was due to some issues with our OpenStack accounting, so we had to redeploy the instances but we kept the same name.
