### ISSUE TITLE
openstack/provision-image.yml appears missing.

### ISSUE THREAD

**Issue by tdeckers** [CiscoCloud/microservices-infrastructure#97]
The [documentation](http://microservices-infrastructure.readthedocs.org/en/latest/getting_started/openstack.html) refers to openstack/provision-image.yml, but it's not in the source tree.

**Comment by corebug** [comment]
To me it looks (https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=provision-image.yml+site:https:%2F%2Fmicroservices-infrastructure.readthedocs.org) that such file is not referred to in the documentation.

**Comment by BrianHicks** [comment]
indeed, this was removed by @keithchambers in #24.
