### ISSUE TITLE
vagrant: update examples documentation

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/microservices-infrastructure#973]
After the changes made in #942, much of the documentation in #906 is outdated. We should update it! Are you interested in helping with this, @larry-svds?

**Comment by larry-svds** [comment]
@siddharthist I can give it a shot this weekend.

**Comment by larry-svds** [comment]
@siddharthist I looked a #975 and it looks like the documentation is done.  Let me know if I'm missing something there.

**Comment by siddharthist** [comment]
@larry-svds yeah, I went ahead and did it :)

**Comment by larry-svds** [comment]
Shouldn't this be closed now?

**Comment by siddharthist** [comment]
We'll close this when #975 is merged.
