### ISSUE TITLE
Cache RPMs before playbook run

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/microservices-infrastructure#980]
In [the Ansible blog about performance tuning](http://www.ansible.com/blog/ansible-performance-tuning), they suggest downloading packages and other large archives to the provisioning machine or one node in your cluster, and having your other nodes pull from there. 

We might be able to do this for docker images as well. 

This might just be pointless when we can use Packer to bake all this in, though.

**Comment by stevendborrelli** [comment]
I'd like to move a much configuration as possible to cloud_init on boot and terraform remote-exec scripts, so that ansible would only be needed for complex tasks and upgrades.
