### ISSUE TITLE
Golang 1.5.3 security advisory

### ISSUE THREAD

**Issue by stevendborrelli** [CiscoCloud/microservices-infrastructure#996]
Go 1.5.3 has been released and includes a security fix. Programs have to be recompiled against 1.5.3  https://groups.google.com/forum/#!topic/golang-announce/MEATuOi_ei4

Note: this bug was introduced in 1.5, so 1.4 builds are not affected.

Hashicorp is rolling out new updated versions of their packages. We'll need to repackage our rpms and containers. 

Please add affected packages to this ticket, we can break out each one separately in other issues:
- [x] consul
- [x] consul-template (PR #1012) 
- <del> [ ] terraform </del> see https://github.com/hashicorp/terraform/issues/4876
- [x] vault PR #1045
- [x] haproxy-consul (updated via https://github.com/CiscoCloud/haproxy-consul/pull/28)
- [x] traefik  https://github.com/emilevauge/traefik/issues/163 Fixed in #1035
- <del> [x] mesos-consul </del> (built on 1.4, not affected)
- <del> [ ] etcd </del>  ( RH/Centos package, built on 1.4, not affected)
- <del> [] zookeepercli </del>  ( currently built on 1.4, not affected)
- <del> [x] mantl-api </del>  ( current version built on 1.4, 0.1.4 built on 1.5.3)

**Comment by stevendborrelli** [comment]
Traefik has been updated: https://github.com/emilevauge/traefik/releases/tag/v1.0.alpha.364
Consul has been updated: https://releases.hashicorp.com/consul/0.6.2/
Vault has been updated: https://releases.hashicorp.com/vault/0.4.1/

**Comment by loshkovskyi** [comment]
`etcd` needs to be updated to [v2.2.4](https://github.com/coreos/etcd/releases)

**Comment by stevendborrelli** [comment]
@loshkovskyi for etcd, we'll have to wait for a RH/Centos fix http://mirror.centos.org/centos/7.2.1511/extras/x86_64/Packages/

**Comment by ryane** [comment]
consul updated to 0.6.3

**Comment by ChrisAubuchon** [comment]
mesos-consul is build with 1.4

**Comment by ChrisAubuchon** [comment]
The [vault-ssl](https://github.com/CiscoCloud/microservices-infrastructure/tree/feature/vault-ssl) branch includes vault 0.4.1 which will take care of vault when it is merged.

**Comment by stevendborrelli** [comment]
etcd is built with 1.4.2 and not affected:

```
# rpm -q etcd
etcd-2.1.1-2.el7.x86_64
# strings /usr/bin/etcd | grep go1
go1.4.2
```

**Comment by stevendborrelli** [comment]
As of 0.6.10, terraform is still built with 1.5.1 on OS X:

```
./terraform --version
Terraform v0.6.10

$ strings ./terraform | grep go1
go1.5.1
```

Given that terraform is run via the cli (and the difficulty of exploring this but on 64 but systems), we're not going to let this block 0.6.

**Comment by stevendborrelli** [comment]
Haproxy container has been updated:

```
docker run ciscocloud/haproxy-consul:latest strings /usr/local/bin/consul-template | grep go1
go1.5.3

```

**Comment by stevendborrelli** [comment]
Awesome work everyone! We the merge of vault #1045 we can close this issue.
